/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class AdapterInfo : IRoot {
	public string? DeviceIdentifier { get; set; } // Offset: 0, Size: 0, Type: String, Id: 1, Class: 
	public int Index { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 1, Class: 
	public string? Driver { get; set; } // Offset: 16, Size: 32, Type: String, Id: 1, Class: 
	[BlackUseNamePool]public string? Description { get; set; } // Offset: 48, Size: 32, Type: WString, Id: 1, Class: 
	public string? DeviceName { get; set; } // Offset: 80, Size: 32, Type: String, Id: 1, Class: 
	public long DriverVersion { get; set; } // Offset: 112, Size: 8, Type: Long, Id: 1, Class: 
	public int VendorID { get; set; } // Offset: 120, Size: 4, Type: Int, Id: 1, Class: 
	public int DeviceID { get; set; } // Offset: 124, Size: 4, Type: Int, Id: 1, Class: 
	public int SubSystemID { get; set; } // Offset: 128, Size: 4, Type: Int, Id: 1, Class: 
	public int Revision { get; set; } // Offset: 128, Size: 4, Type: Int, Id: 1, Class: 
	public string? DriverVersionString { get; set; } // Offset: 152, Size: 32, Type: String, Id: 1, Class: 
	public string? DriverDate { get; set; } // Offset: 184, Size: 32, Type: String, Id: 1, Class: 
	public string? DriverVendor { get; set; } // Offset: 216, Size: 32, Type: String, Id: 1, Class: 
	public bool IsOptimus { get; set; } // Offset: 248, Size: 1, Type: Boolean, Id: 1, Class: 
}
