/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class DisplayModeInfo : IRoot {
	public int Width { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 1, Class: 
	public int Height { get; set; } // Offset: 12, Size: 4, Type: Int, Id: 1, Class: 
	public int RefreshRateNumerator { get; set; } // Offset: 16, Size: 4, Type: Int, Id: 1, Class: 
	public int RefreshRateDenominator { get; set; } // Offset: 20, Size: 4, Type: Int, Id: 1, Class: 
	public int Format { get; set; } // Offset: 24, Size: 4, Type: Int, Id: 513, Class: 
	public int Scaling { get; set; } // Offset: 28, Size: 4, Type: Int, Id: 513, Class: 
}
