/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class SHBuilder : IRoot {
	public double AngleName { get; set; }
	public int NumSteps { get; set; }
	public int MaxBands { get; set; }
	public int MaxCoefficients { get; set; }
}
