/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Allign : IRoot, IBehavior {
	public bool Enabled { get; set; } // Offset: 8, Size: 1, Type: Boolean, Id: 19, Class: 
	public int FramesBetweenUpdates { get; set; } // Offset: 12, Size: 4, Type: Int, Id: 19, Class: 
	public float BehaviorWeight { get; set; } // Offset: 48, Size: 4, Type: Single, Id: 19, Class: 
	public float VisionRange { get; set; } // Offset: 52, Size: 4, Type: Single, Id: 19, Class: 
	public int BehaviorPriority { get; set; } // Offset: 56, Size: 4, Type: Int, Id: 535, Class: 
}
