/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BehaviorGroupBooster : IRoot, IInitialize, INotify {
	public Vector3 BoosterOffset { get; set; } // Offset: 16, Size: 12, Type: FloatArray, Id: 19, Class: 
	public float LightRadius { get; set; } // Offset: 28, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 LightColor { get; set; } // Offset: 32, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public int AtlasIndex0 { get; set; } // Offset: 48, Size: 4, Type: Int, Id: 19, Class: 
	public int AtlasIndex1 { get; set; } // Offset: 52, Size: 4, Type: Int, Id: 19, Class: 
	public bool Display { get; set; } // Offset: 56, Size: 1, Type: Boolean, Id: 19, Class: 
	public IRoot? BoosterEffect { get; set; } // Offset: 64, Size: 8, Type: Object, Id: 19, Class: Tr2Effect
	public IRoot? HaloFlareEffect { get; set; } // Offset: 72, Size: 8, Type: Object, Id: 23, Class: Tr2Effect
	public Vector3 HaloFlareOffset { get; set; } // Offset: 84, Size: 12, Type: FloatArray, Id: 23, Class: 
	public Vector3 HaloFlareScale { get; set; } // Offset: 96, Size: 12, Type: FloatArray, Id: 23, Class: 
	public float HaloFlareBrightness { get; set; } // Offset: 108, Size: 4, Type: Single, Id: 23, Class: 
	public Vector3 HaloFlareColor { get; set; } // Offset: 112, Size: 16, Type: FloatArray, Id: 23, Class: Color
	public float HaloFlareNoiseAmplitude { get; set; } // Offset: 128, Size: 4, Type: Single, Id: 19, Class: 
	public float HaloFlareNoiseSpeed { get; set; } // Offset: 132, Size: 4, Type: Single, Id: 19, Class: 
	public int HaloFlareNoiseOctaves { get; set; } // Offset: 136, Size: 4, Type: Int, Id: 19, Class: 
	public IRoot? AmbientFlareEffect { get; set; } // Offset: 216, Size: 8, Type: Object, Id: 23, Class: Tr2Effect
	public Vector3 AmbientFlareOffset { get; set; } // Offset: 228, Size: 12, Type: FloatArray, Id: 23, Class: 
	public Vector3 AmbientFlareScale { get; set; } // Offset: 240, Size: 12, Type: FloatArray, Id: 23, Class: 
	public float AmbientFlareBrightness { get; set; } // Offset: 252, Size: 4, Type: Single, Id: 23, Class: 
	public Vector3 AmbientFlareColor { get; set; } // Offset: 256, Size: 16, Type: FloatArray, Id: 23, Class: Color
	public float AmbientFlareNoiseAmplitude { get; set; } // Offset: 272, Size: 4, Type: Single, Id: 19, Class: 
	public float AmbientFlareNoiseSpeed { get; set; } // Offset: 276, Size: 4, Type: Single, Id: 19, Class: 
	public int AmbientFlareNoiseOctaves { get; set; } // Offset: 280, Size: 4, Type: Int, Id: 19, Class: 
	public int FlareCount { get; set; } // Offset: 680, Size: 4, Type: Int, Id: 1, Class: 
	public bool DisplayBoosters { get; set; } // Offset: 700, Size: 1, Type: Boolean, Id: 3, Class: 
	public bool DisplayHazeFlare { get; set; } // Offset: 701, Size: 1, Type: Boolean, Id: 3, Class: 
	public bool DisplayAmbientFlare { get; set; } // Offset: 702, Size: 1, Type: Boolean, Id: 3, Class: 
}
