/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class CollisionAvoidance : IRoot, IBehavior {
	public bool Enabled { get; set; }
	public List<IRoot?>? ExclusionVolumes { get; set; }
	public float AvoidanceScalar { get; set; }
	public int BehaviorPriority { get; set; }
}
