/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class DroneAvoidance : IBehavior, IRoot {
	public bool Enabled { get; set; }
	public int FramesBetweenUpdates { get; set; }
	public float BehaviorWeight { get; set; }
	public float VisionRange { get; set; }
	public int BehaviorPriority { get; set; }
}
