/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveBoosterSet2Renderable : IRoot, ITr2Renderable {
	public Vector3 TrailsBoundsMin { get; set; }
	public Vector3 TrailsBoundsMax { get; set; }
	public float BoosterLOD { get; set; }
	public float TrailsLOD { get; set; }
	public float ParentSpeed { get; set; }
	public Vector3 ParentRotation { get; set; }
	public float OverallIntensity { get; set; }
	public float TrailIntensity { get; set; }
	public float TrailsTotalLength { get; set; }
	public float TrailsTimeDelta { get; set; }
}
