/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveBezierCurve : IEveLineSetPath, INotify, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public string? Name { get; set; }
	public Vector3D<float> Point1 { get; set; }
	public Vector3D<float> Point2 { get; set; }
	public Vector3D<float> BezierPoint { get; set; }
	public Vector3D<float> ObjectScale { get; set; }
	public float Completeness { get; set; }
	public float Segments { get; set; }
	public float LineWidth { get; set; }
	public float SegmentOffset { get; set; }
	public float MovementSpeed { get; set; }
	public float AnimValue { get; set; }
	public bool Display { get; set; }
	public bool IsVisible { get; set; }
	public bool ScaleEndpoints { get; set; }
	public bool ScaleSegmentsByCompleteness { get; set; }
	public bool BillboardObjects { get; set; }
}
