/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildSpherePin : EveChildMesh {
	public Vector3 CenterNormal { get; set; }
	public float PinMaxRadius { get; set; }
	public float PinRadius { get; set; }
	public float PinRotation { get; set; }
	public Vector3 PinColor { get; set; }
	public Vector3 Color { get; set; }
	public float PinAlphaThreshold { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
}
