/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildQuad : IEveSpaceObjectChild, IInitialize, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Matrix4X4<float> LocalTransform { get; set; }
	public Matrix4X4<float> WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public string? Name { get; set; }
	public Tr2Effect? Effect { get; set; }
	public float ViewRotation { get; set; }
	public Vector4D<float> Color { get; set; }
	public float Brightness { get; set; }
	public float MinScreenSize { get; set; }
	public float CurrentScreenSize { get; set; }
	public bool Display { get; set; }
	public bool EditMode { get; set; }
}
