/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveCamera : INotify, IRoot {
	[BlackArray] public ITriVectorFunction? Parent { get; set; }
	[BlackArray] public ITriVectorFunction? Interest { get; set; }
	[BlackArray] public IBluePlacementObserver? Audio2Listener { get; set; }
	public float TranslationFromParent { get; set; }
	public Vector4D<float> RotationAroundParent { get; set; }
	public Vector4D<float> RotationOfInterest { get; set; }
	public Vector3D<float> Alignment { get; set; }
	public Vector3D<float> ExtraTranslation { get; set; }
	public bool UseExtraTranslation { get; set; }
	public float FieldOfView { get; set; }
	public float FrontClip { get; set; }
	public float BackClip { get; set; }
	public float Friction { get; set; }
	public float MaxSpeed { get; set; }
	public float MinPitch { get; set; }
	public float MaxPitch { get; set; }
	public float MinYaw { get; set; }
	public float MaxYaw { get; set; }
	public float Yaw { get; set; }
	public float Pitch { get; set; }
	public bool IdleMove { get; set; }
	public float IdleScale { get; set; }
	public float IdleSpeed { get; set; }
	public bool Noise { get; set; }
	public float NoiseScale { get; set; }
	public float NoiseDamp { get; set; }
	public float CenterOffset { get; set; }
	[BlackArray] public ITriScalarFunction? ZoomCurve { get; set; }
	[BlackArray] public ITriScalarFunction? NoiseCurve { get; set; }
	[BlackArray] public ITriScalarFunction? NoiseScaleCurve { get; set; }
	[BlackArray] public ITriScalarFunction? NoiseDampCurve { get; set; }
	public bool Update { get; set; }
	public Vector3D<float> Pos { get; set; }
	public Vector3D<float> Intr { get; set; }
	public Vector3D<float> ViewVec { get; set; }
	public Vector3D<float> RightVec { get; set; }
	public Vector3D<float> UpVec { get; set; }
	[BlackArray] public TriProjection? ProjectionMatrix { get; set; }
	[BlackArray] public TriView? ViewMatrix { get; set; }
	[BlackArray] public IBlueEventListener? ErrorHandler { get; set; }
}
