/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildParticleSphere : IRoot, IEveSpaceObjectChild, ITr2Renderable {
	public bool IsValid { get; set; }
	public Tr2InstancedMesh? Mesh { get; set; }
	public Tr2ParticleSystem? ParticleSystem { get; set; }
	public List<IRoot?>? Generators { get; set; }
	public string? Name { get; set; }
	public float Radius { get; set; }
	public float MovementScale { get; set; }
	public float MaxSpeed { get; set; }
	public float EgoSpeed { get; set; }
	public float PositionShiftMax { get; set; }
	public float PositionShiftMin { get; set; }
	public float PositionShift { get; set; }
	public float PositionShiftIncreaseSpeed { get; set; }
	public float PositionShiftDecreaseSpeed { get; set; }
	public bool UseSpaceObjectData { get; set; }
	public bool Display { get; set; }
}
