/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildCloud2 : IRoot, ITr2VolumetricRenderable, ITr2GeometryProvider, IInitialize, INotify, IEveSpaceObjectChild, ITr2Renderable, EveEntity {
	public bool LightmapDirty { get; set; }
	public IRoot? Effect { get; set; }
	public IRoot? ReflectionEffect { get; set; }
	public int NoiseTextureSize { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector3 Translation { get; set; }
	public Vector3 Rotation { get; set; }
	public List<IRoot?>? Lights { get; set; }
	public IRoot? Lightmap { get; set; }
	public IRoot? Animation { get; set; }
	public int ReflectionMode { get; set; }
	public int MinVisibleQuality { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public bool CastShadows { get; set; }
	public bool ReceiveShadows { get; set; }
	public float SortingModifier { get; set; }
	public float MinScreenSize { get; set; }
	public float LightmapSizeScale { get; set; }
	public Vector3 TextureTiling { get; set; }
	public Vector3 DetailTiling1 { get; set; }
	public Vector3 DetailTiling2 { get; set; }
	public Vector3 MapOffset0 { get; set; }
	public Vector3 MapOffset1 { get; set; }
	public Vector3 MapOffset2 { get; set; }
}
