/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildInstancedMeshes : IEveSpaceObjectChild, EveEntity, IEveShadowCaster, IRoot {
	public string? Name { get; set; }
}
