/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildQuad : IRoot, IEveSpaceObjectChild, IInitialize {
	public Vector3 Translation { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public Matrix4x4 LocalTransform { get; set; }
	public Matrix4x4 WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public string? Name { get; set; }
	public Tr2Effect? Effect { get; set; }
	public float ViewRotation { get; set; }
	public Vector4 Color { get; set; }
	public float Brightness { get; set; }
	public float MinScreenSize { get; set; }
	public float CurrentScreenSize { get; set; }
	public bool Display { get; set; }
	public bool EditMode { get; set; }
}
