/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveCustomMask : IRoot {
	public Vector3D<float> Position { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public byte MaterialIndex { get; set; }
	public Vector4D<float> TargetMaterials { get; set; }
	public bool IsMirrored { get; set; }
	public bool ClampU { get; set; }
	public bool ClampV { get; set; }
}
