/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildCloud : IRoot, ITr2Renderable, ITr2GeometryProvider, IInitialize, INotify, IEveSpaceObjectChild {
	public Vector3 BoundingSphere { get; set; }
	public IRoot? Effect { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector3 Translation { get; set; }
	public Vector3 Rotation { get; set; }
	public int PreTesselationLevel { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public IRoot? Volume { get; set; }
	public float SortingModifier { get; set; }
	public float MinScreenSize { get; set; }
	public float CellScreenSize { get; set; }
	public long CurrentLod { get; set; }
}
