/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildInstanceContainer : IRoot, IEveSpaceObjectChild, ITr2CurveSetOwner, INotify, IEveEffectChildrenOwner, IShaderConfigurer, ITr2ControllerOwner, IListNotify, EveEntity {
	public Vector3 Translation { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public Matrix4x4 LocalTransform { get; set; }
	public Matrix4x4 WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public bool UseStaticRotation { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public bool AlwaysOn { get; set; }
	public EveChildInheritProperties? InheritProperties { get; set; }
	public int Origin { get; set; }
	public IEveSpaceObjectChild? Source { get; set; }
	public List<IRoot?>? Instances { get; set; }
	public bool Reset { get; set; }
	public string? LocatorSet { get; set; }
	[BlackArray]public byte[][]? Transforms { get; set; }
	public List<IRoot?>? TransformModifiers { get; set; }
}
