/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveCloudEditableVolume : IRoot, IListNotify, IInitialize, INotify {
	public IRoot? Texture { get; set; }
	public IRoot? Bitmap { get; set; }
	public List<IRoot?>? Balls { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int Depth { get; set; }
	public bool RenderDebugInfo { get; set; }
	public bool Animated { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
}
