/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveCloudEditableVolume : IListNotify, IInitialize, INotify, IRoot {
	[BlackArray] public TriTextureRes? Texture { get; set; }
	[BlackArray] public Tr2HostBitmap? Bitmap { get; set; }
	public List<IRoot?>? Balls { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int Depth { get; set; }
	public bool RenderDebugInfo { get; set; }
	public bool Animated { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
}
