/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildMesh : EveEntity, IEveSpaceObjectDecalOwner, IEveSpaceObjectChild, ITr2Renderable, IInitialize, INotify, ITr2GrannyAnimationOwner, IEveSpaceObjectAttachmentOwner, ITr2LightOwner, ITr2Pickable, IEveShadowCaster, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Matrix4X4<float> LocalTransform { get; set; }
	public Matrix4X4<float> WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public string? Name { get; set; }
	[BlackArray] public Tr2MeshBase? Mesh { get; set; }
	public List<IRoot?>? TransformModifiers { get; set; }
	[BlackArray] public Tr2GrannyAnimation? AnimationUpdater { get; set; }
	public int LowestLodVisible { get; set; }
	public float MinScreenSize { get; set; }
	public float CurrentScreenSize { get; set; }
	public float CurrentInstanceScreenSize { get; set; }
	public float SortValueOffset { get; set; }
	public float SortValueScale { get; set; }
	public bool Display { get; set; }
	public bool CastShadow { get; set; }
	public bool UpdateAnimation { get; set; }
	public int Origin { get; set; }
	public int ReflectionMode { get; set; }
	public List<IRoot?>? Decals { get; set; }
	public List<IRoot?>? Attachments { get; set; }
	public List<IRoot?>? Lights { get; set; }
}
