/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveCameraFxAttributes : IRoot, IEveFxAttribute {
	public string? Name { get; set; }
	public float DistanceToCamera { get; set; }
	public float LookAngleToObject { get; set; }
	public Vector3 ObjectRotation { get; set; }
	public Vector3 RotationWithChildTransform { get; set; }
	public Vector3 CameraRotation { get; set; }
}
