/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveConnector : IRoot {
	public ITriVectorFunction? SourceObject { get; set; }
	public ITriVectorFunction? DestObject { get; set; }
	public int Type { get; set; }
	public Vector3 SourcePosition { get; set; }
	public Vector3 DestPosition { get; set; }
	public Vector3 PlaneNormal { get; set; }
	public Vector4 Color { get; set; }
	public Vector4 AnimationColor { get; set; }
	public float AnimationSpeed { get; set; }
	public float AnimationScale { get; set; }
	public float LineWidth { get; set; }
	public float Length { get; set; }
	public bool IsAnimated { get; set; }
	public bool AutoScaleAnimation { get; set; }
}
