/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildRef : IRoot, IEveSpaceObjectChild, ITr2CurveSetOwner, IInitialize, INotify, IEveEffectChildrenOwner, IShaderConfigurer, ITr2SoundEmitterOwner, EveEntity {
	public Vector3 Translation { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public Matrix4x4 LocalTransform { get; set; }
	public Matrix4x4 WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public IEveSpaceObjectChild? Child { get; set; }
	public string? Name { get; set; }
	public string? ResPath { get; set; }
	public bool LoadChildAutomatically { get; set; }
	public bool Display { get; set; }
}
