/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildPlug : IRoot, IEveSpaceObjectChild, ITr2CurveSetOwner, IInitialize, IEveEffectChildrenOwner, IShaderConfigurer, ITr2SoundEmitterOwner {
	public List<IRoot?>? Objects { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? Controllers { get; set; }
	public List<IRoot?>? ExternalParameters { get; set; }
	public bool Display { get; set; }
}
