/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildModifierTranslateWithCamera : IRoot, IEveChildTransformModifier {
	public bool AttachedToCamera { get; set; }
}
