/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveCameraFxAttributes : IRoot, IEveFxAttribute {
	public string? Name { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public float DistanceToCamera { get; set; } // Offset: 16, Size: 4, Type: Single, Id: 1, Class: 
	public float LookAngleToObject { get; set; } // Offset: 20, Size: 4, Type: Single, Id: 1, Class: 
	public Vector3 ObjectRotation { get; set; } // Offset: 24, Size: 12, Type: FloatArray, Id: 1, Class: 
	public Vector3 RotationWithChildTransform { get; set; } // Offset: 36, Size: 12, Type: FloatArray, Id: 1, Class: 
	public Vector3 CameraRotation { get; set; } // Offset: 48, Size: 12, Type: FloatArray, Id: 1, Class: 
}
