/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveCloudVolumeTextureParameter : IRoot, ITriEffectResourceParameter {
	public string? Name { get; set; }
	public EveCloudEditableVolume? Volume { get; set; }
	public bool IsUsedByEffect { get; set; }
}
