/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildEnvironment : IRoot, IEveSpaceObjectChild, IInitialize, IListNotify {
	public string? Name { get; set; }
	public List<IRoot?>? Volumes { get; set; }
	public List<IRoot?>? ExclusionVolumes { get; set; }
	public Vector3 BoundingSphere { get; set; }
	public float Intensity { get; set; }
}
