/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveCamera : IRoot, INotify {
	public object? Parent { get; set; }
	public object? Interest { get; set; }
	public object? Audio2Listener { get; set; }
	public float TranslationFromParent { get; set; }
	public Vector4 RotationAroundParent { get; set; }
	public Vector4 RotationOfInterest { get; set; }
	public Vector3 Alignment { get; set; }
	public Vector3 ExtraTranslation { get; set; }
	public bool UseExtraTranslation { get; set; }
	public float FieldOfView { get; set; }
	public float FrontClip { get; set; }
	public float BackClip { get; set; }
	public float Friction { get; set; }
	public float MaxSpeed { get; set; }
	public float MinPitch { get; set; }
	public float MaxPitch { get; set; }
	public float MinYaw { get; set; }
	public float MaxYaw { get; set; }
	public float Yaw { get; set; }
	public float Pitch { get; set; }
	public bool IdleMove { get; set; }
	public float IdleScale { get; set; }
	public float IdleSpeed { get; set; }
	public bool Noise { get; set; }
	public float NoiseScale { get; set; }
	public float NoiseDamp { get; set; }
	public float CenterOffset { get; set; }
	public object? ZoomCurve { get; set; }
	public object? NoiseCurve { get; set; }
	public object? NoiseScaleCurve { get; set; }
	public object? NoiseDampCurve { get; set; }
	public bool Update { get; set; }
	public Vector3 Pos { get; set; }
	public Vector3 Intr { get; set; }
	public Vector3 ViewVec { get; set; }
	public Vector3 RightVec { get; set; }
	public Vector3 UpVec { get; set; }
	public object? ProjectionMatrix { get; set; }
	public object? ViewMatrix { get; set; }
	public object? ErrorHandler { get; set; }
}
