/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildQuad : IRoot, IEveSpaceObjectChild, IInitialize {
	public Vector3 Translation { get; set; } // Offset: 24, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 36, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Matrix4x4 LocalTransform { get; set; } // Offset: 64, Size: 64, Type: FloatArray, Id: 19, Class: Matrix
	public Matrix4x4 WorldTransform { get; set; } // Offset: 128, Size: 64, Type: FloatArray, Id: 1, Class: Matrix
	public bool StaticTransform { get; set; } // Offset: 192, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool UseSRT { get; set; } // Offset: 193, Size: 1, Type: Boolean, Id: 19, Class: 
	public string? Name { get; set; } // Offset: 200, Size: 8, Type: UTFString, Id: 19, Class: 
	public IRoot? Effect { get; set; } // Offset: 208, Size: 8, Type: Object, Id: 19, Class: Tr2Effect
	public float ViewRotation { get; set; } // Offset: 340, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 Color { get; set; } // Offset: 344, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public float Brightness { get; set; } // Offset: 360, Size: 4, Type: Single, Id: 19, Class: 
	public float MinScreenSize { get; set; } // Offset: 364, Size: 4, Type: Single, Id: 19, Class: 
	public float CurrentScreenSize { get; set; } // Offset: 368, Size: 4, Type: Single, Id: 1, Class: 
	public bool Display { get; set; } // Offset: 372, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool EditMode { get; set; } // Offset: 373, Size: 1, Type: Boolean, Id: 3, Class: 
}
