/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildBehaviorSystem : IRoot, IEveSpaceObjectChild, ITr2Renderable {
	public Vector3 Translation { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector3 Rotation { get; set; }
	public Matrix4x4 LocalTransform { get; set; }
	public Matrix4x4 WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public bool Display { get; set; }
	public int VertexCount { get; set; }
	public List<IRoot?>? SplineTunnels { get; set; }
	public List<IRoot?>? BehaviorGroups { get; set; }
}
