/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildSmartLightSet : IEveSpaceObjectChild, ITr2DebugRenderable, INotify, IListNotify, IEveInheritPropertiesOwner, EveEntity, IRoot {
	public bool Display { get; set; }
	public string? Name { get; set; }
	[BlackArray] public IEveDistributionMethod? Distribution { get; set; }
	public List<IRoot?>? LightGroups { get; set; }
}
