/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildLink : EveChildMesh {
	public Vector3 CurrentDirection { get; set; } // Offset: 1776, Size: 12, Type: FloatArray, Id: 1, Class: 
	public float CurrentDistance { get; set; } // Offset: 1788, Size: 4, Type: Single, Id: 1, Class: 
	public float LinkStrength { get; set; } // Offset: 1792, Size: 4, Type: Single, Id: 1, Class: 
	public float LinkBarrier { get; set; } // Offset: 1796, Size: 4, Type: Single, Id: 3, Class: 
	public float TargetRadius { get; set; } // Offset: 1800, Size: 4, Type: Single, Id: 3, Class: 
	public IRoot? Target { get; set; } // Offset: 1808, Size: 8, Type: Object, Id: 3, Class: ITriVectorFunction
	public List<IRoot?>? LinkStrengthBindings { get; set; } // Offset: 1816, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? LinkStrengthCurves { get; set; } // Offset: 1960, Size: 144, Type: Collection, Id: 17, Class: IList
}
