/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildCloud : IRoot, ITr2Renderable, ITr2GeometryProvider, IInitialize, INotify, IEveSpaceObjectChild {
	public Vector3 BoundingSphere { get; set; } // Offset: 184, Size: 16, Type: FloatArray, Id: 1, Class: 
	public IRoot? Effect { get; set; } // Offset: 200, Size: 8, Type: Object, Id: 19, Class: Tr2Material
	public Vector3 Scaling { get; set; } // Offset: 208, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Translation { get; set; } // Offset: 220, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 232, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public int PreTesselationLevel { get; set; } // Offset: 248, Size: 4, Type: Int, Id: 23, Class: 
	public string? Name { get; set; } // Offset: 360, Size: 32, Type: String, Id: 19, Class: 
	public bool Display { get; set; } // Offset: 392, Size: 1, Type: Boolean, Id: 3, Class: 
	public IRoot? Volume { get; set; } // Offset: 400, Size: 8, Type: Object, Id: 19, Class: EveCloudEditableVolume
	public float SortingModifier { get; set; } // Offset: 432, Size: 4, Type: Single, Id: 19, Class: 
	public float MinScreenSize { get; set; } // Offset: 436, Size: 4, Type: Single, Id: 19, Class: 
	public float CellScreenSize { get; set; } // Offset: 440, Size: 4, Type: Single, Id: 19, Class: 
	public long CurrentLod { get; set; } // Offset: 448, Size: 8, Type: Long, Id: 1, Class: 
}
