/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildModifierSRT : IRoot, IEveChildTransformModifier {
	public Vector3 Scaling { get; set; }
	public Vector3 Translation { get; set; }
	public Vector3 Rotation { get; set; }
}
