/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveChildContainer : IRoot, EveEntity, IEveSpaceObjectChild, ITr2CurveSetOwner, IInitialize, IListNotify, INotify, IEveEffectChildrenOwner, IShaderConfigurer, ITr2SoundEmitterOwner, ITr2ControllerOwner, IEveInheritPropertiesOwner, IEveSpaceObjectAttachmentOwner, ITr2Renderable {
	public bool Mute { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 3, Class: 
	public bool IsRendering { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public bool IsUpdating { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public Vector3 Translation { get; set; } // Offset: 128, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 140, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 152, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Matrix4x4 LocalTransform { get; set; } // Offset: 168, Size: 64, Type: FloatArray, Id: 19, Class: Matrix
	public Matrix4x4 WorldTransform { get; set; } // Offset: 232, Size: 64, Type: FloatArray, Id: 1, Class: Matrix
	public bool StaticTransform { get; set; } // Offset: 296, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool UseSRT { get; set; } // Offset: 297, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool UseStaticRotation { get; set; } // Offset: 298, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool UseStaticScale { get; set; } // Offset: 299, Size: 1, Type: Boolean, Id: 19, Class: 
	public List<IRoot?>? Objects { get; set; } // Offset: 304, Size: 144, Type: Collection, Id: 17, Class: IList
	public string? Name { get; set; } // Offset: 448, Size: 8, Type: UTFString, Id: 19, Class: 
	public List<IRoot?>? CurveSets { get; set; } // Offset: 456, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Observers { get; set; } // Offset: 600, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Lights { get; set; } // Offset: 744, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Controllers { get; set; } // Offset: 888, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? TransformModifiers { get; set; } // Offset: 1224, Size: 144, Type: Collection, Id: 17, Class: IList
	public bool Display { get; set; } // Offset: 1388, Size: 1, Type: Boolean, Id: 23, Class: 
	public int DisplayFilter { get; set; } // Offset: 1392, Size: 4, Type: Int, Id: 535, Class: 
	public bool AlwaysOn { get; set; } // Offset: 1396, Size: 1, Type: Boolean, Id: 19, Class: 
	public IRoot? InheritProperties { get; set; } // Offset: 1400, Size: 8, Type: Object, Id: 19, Class: EveChildInheritProperties
	public int Origin { get; set; } // Offset: 1408, Size: 4, Type: Int, Id: 1, Class: 
	public List<IRoot?>? FxAttributes { get; set; } // Offset: 1416, Size: 144, Type: Collection, Id: 17, Class: IList
	public IRoot? AnimationOwner { get; set; } // Offset: 1560, Size: 8, Type: Object, Id: 1, Class: ITr2GrannyAnimationOwner
	public List<IRoot?>? Attachments { get; set; } // Offset: 1568, Size: 144, Type: Collection, Id: 17, Class: IList
}
