/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildModifierSRT : IRoot, IEveChildTransformModifier {
	public Vector3 Scaling { get; set; }
	public Vector3 Translation { get; set; }
	public Vector4 Rotation { get; set; }
}
