/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveChildBehaviorSystem : IEveSpaceObjectChild, ITr2Renderable, INotify, EveEntity, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Matrix4X4<float> LocalTransform { get; set; }
	public Matrix4X4<float> WorldTransform { get; set; }
	public bool StaticTransform { get; set; }
	public bool UseSRT { get; set; }
	public bool Display { get; set; }
	public int InstanceCount { get; set; }
	public List<IRoot?>? SplineTunnels { get; set; }
	public List<IRoot?>? BehaviorGroups { get; set; }
}
