/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionSpawnerBurst : IEveDistributionSpawner, IRoot {
	public float DelayBeforeInitialBurst { get; set; }
	public float Completeness { get; set; }
	public int AdditionalTriggersPerBurst { get; set; }
}
