/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveDistanceField : IRoot, IListNotify, INotify {
	public List<IRoot?>? Objects { get; set; } // Offset: 24, Size: 144, Type: Collection, Id: 5, Class: IList
	public IRoot? CurveSet { get; set; } // Offset: 168, Size: 8, Type: Object, Id: 3, Class: TriCurveSet
	public IRoot? CameraView { get; set; } // Offset: 184, Size: 8, Type: Object, Id: 3, Class: TriView
	public float MinDistance { get; set; } // Offset: 192, Size: 4, Type: Single, Id: 7, Class: 
	public float MaxDistance { get; set; } // Offset: 196, Size: 4, Type: Single, Id: 7, Class: 
	public float Distance { get; set; } // Offset: 200, Size: 4, Type: Single, Id: 3, Class: 
	public float TimeAdjustmentSecondsOut { get; set; } // Offset: 204, Size: 4, Type: Single, Id: 3, Class: 
	public float TimeAdjustmentSecondsIn { get; set; } // Offset: 208, Size: 4, Type: Single, Id: 3, Class: 
	public float DistanceThreshold { get; set; } // Offset: 212, Size: 4, Type: Single, Id: 3, Class: 
	public float MaxXZRatio { get; set; } // Offset: 216, Size: 4, Type: Single, Id: 3, Class: 
	public float MinYRatio { get; set; } // Offset: 220, Size: 4, Type: Single, Id: 3, Class: 
	public Vector3 Midpoint { get; set; } // Offset: 228, Size: 12, Type: FloatArray, Id: 1, Class: 
	public Vector3 Dimensions { get; set; } // Offset: 240, Size: 12, Type: FloatArray, Id: 1, Class: 
}
