/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionSpawnerTriggerSnake : IEveDistributionSpawner, IRoot {
	public int TotalDestinations { get; set; }
	public int DestinationsReached { get; set; }
	public float MinBaseTimeBetweenTriggers { get; set; }
	public float MaxBaseTimeBetweenTriggers { get; set; }
	public float TravelProgress { get; set; }
	public float DistanceToTravelTimeMultiplier { get; set; }
}
