/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionModifierTransformOffset : IEveDistributionModifier, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public ITriVectorFunction? TranslationCurve { get; set; }
	public ITriQuaternionFunction? RotationCurve { get; set; }
	public ITriVectorFunction? ScaleCurve { get; set; }
}
