/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionSpawnerTriggerPlane : IEveDistributionSpawner, IRoot {
	public Vector4D<float> PlaneRotation { get; set; }
	public float DelayBeforeActivation { get; set; }
	public float PlayDuration { get; set; }
	public float TriggerChance { get; set; }
	public bool StartSequenceAtFirstTrigger { get; set; }
	public bool ReversePlaneAnimation { get; set; }
}
