/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionPlacementGeneratorLocators : IEveDistributionPlacementGenerators, IRoot {
	[BlackArray] public byte[][]? Locators { get; set; }
}
