/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveDistanceField : IRoot, IListNotify, INotify {
	public List<IRoot?>? Objects { get; set; }
	public object? CurveSet { get; set; }
	public object? CameraView { get; set; }
	public float MinDistance { get; set; }
	public float MaxDistance { get; set; }
	public float Distance { get; set; }
	public float TimeAdjustmentSecondsOut { get; set; }
	public float TimeAdjustmentSecondsIn { get; set; }
	public float DistanceThreshold { get; set; }
	public float MaxXZRatio { get; set; }
	public float MinYRatio { get; set; }
	public Vector3 Midpoint { get; set; }
	public Vector3 Dimensions { get; set; }
}
