/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistributionPlacementGeneratorParentLocators : IEveDistributionPlacementGenerators, INotify, IRoot {
	public string? LocatorSetName { get; set; }
}
