/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveDistanceField : IListNotify, INotify, IRoot {
	public List<IRoot?>? Objects { get; set; }
	[BlackArray] public TriCurveSet? CurveSet { get; set; }
	[BlackArray] public TriView? CameraView { get; set; }
	public float MinDistance { get; set; }
	public float MaxDistance { get; set; }
	public float Distance { get; set; }
	public float TimeAdjustmentSecondsOut { get; set; }
	public float TimeAdjustmentSecondsIn { get; set; }
	public float DistanceThreshold { get; set; }
	public float MaxXZRatio { get; set; }
	public float MinYRatio { get; set; }
	public Vector3D<float> Midpoint { get; set; }
	public Vector3D<float> Dimensions { get; set; }
}
