/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveEllipsoidVolume : IRoot, IEveVolume, INotify {
	public string? Name { get; set; }
	public Vector3 Position { get; set; }
	public Vector3 Shape { get; set; }
	public Vector3 InnerShape { get; set; }
	public Vector4 Rotation { get; set; }
	public bool DebugShowIntersection { get; set; }
}
