/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveHazeSet : IRoot, IInitialize, IEveSpaceObjectAttachment {
	public bool Display { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? Hazes { get; set; }
	public Tr2Effect? Effect { get; set; }
}
