/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveImpactOverlay : IRoot {
	public string? Name { get; set; }
	public bool Display { get; set; }
	public int Configuration { get; set; }
	public int ImpactDataNextIdx { get; set; }
	public bool DebugForceSpawnDebris { get; set; }
	public int Seed { get; set; }
	public float RenderPriority { get; set; }
	public float OverallShieldImpact { get; set; }
	public int DataTextureBlockID { get; set; }
	public Tr2MeshBase? Mesh { get; set; }
	public bool ShieldIsEllipsoid { get; set; }
	public int MaxShieldImpacts { get; set; }
	public float ShieldImpactColorFade { get; set; }
	public float ShieldImpactParentSize { get; set; }
	public Tr2Effect? ArmorDamageShader { get; set; }
	public long ArmorImpactGoalCount { get; set; }
	public float ArmorImpactParentSize { get; set; }
	public Tr2GpuUniqueEmitter? ArmorImpactEmitter { get; set; }
	public float HullDamageFactor { get; set; }
	public TriPerlinCurve? HullDamageFlickerCurve { get; set; }
	public Tr2GpuUniqueEmitter? HullImpactEmitter { get; set; }
	public Tr2ScalarFader? ShieldHardening { get; set; }
	public Tr2ScalarFader? ShieldBoosting { get; set; }
	public Tr2ScalarFader? ArmorRepairing { get; set; }
	public Tr2ScalarFader? ArmorHardening { get; set; }
	public Tr2ScalarFader? HullRepairing { get; set; }
}
