/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLensflare : IRoot, ITr2ControllerOwner, ITr2CurveSetOwner, IInitialize {
	public string? Name { get; set; } // Offset: 40, Size: 32, Type: String, Id: 19, Class: 
	public bool Display { get; set; } // Offset: 72, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Update { get; set; } // Offset: 73, Size: 1, Type: Boolean, Id: 19, Class: 
	public float CameraFactor { get; set; } // Offset: 76, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 Position { get; set; } // Offset: 144, Size: 12, Type: FloatArray, Id: 19, Class: 
	public List<IRoot?>? DistanceToEdgeCurves { get; set; } // Offset: 176, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DistanceToCenterCurves { get; set; } // Offset: 320, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? RadialAngleCurves { get; set; } // Offset: 464, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? XDistanceToCenter { get; set; } // Offset: 608, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? YDistanceToCenter { get; set; } // Offset: 752, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Bindings { get; set; } // Offset: 896, Size: 144, Type: Collection, Id: 17, Class: IList
	public IRoot? TranslationCurve { get; set; } // Offset: 1040, Size: 8, Type: Object, Id: 3, Class: ITriVectorFunction
	public List<IRoot?>? Flares { get; set; } // Offset: 1048, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Occluders { get; set; } // Offset: 1208, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? BackgroundOccluders { get; set; } // Offset: 1352, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? CurveSets { get; set; } // Offset: 1496, Size: 144, Type: Collection, Id: 17, Class: IList
	public IRoot? Mesh { get; set; } // Offset: 1640, Size: 8, Type: Object, Id: 19, Class: Tr2Mesh
	public List<IRoot?>? Controllers { get; set; } // Offset: 1648, Size: 144, Type: Collection, Id: 17, Class: IList
}
