/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLineContainer : IRoot, IEveSpaceObject2 {
	public string? Name { get; set; }
	public List<IRoot?>? Connectors { get; set; }
	public object? LineSet { get; set; }
	public bool Display { get; set; }
}
