/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveLineChildContainer : IEveLineSetPath, INotify, IListNotify, IRoot {
	public Vector3D<float> Translation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? Lines { get; set; }
	public bool IsVisible { get; set; }
	public bool Display { get; set; }
}
