/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLineSet : IRoot, IInitialize, ITr2Renderable, IEveTransform, IEveSpaceObject2 {
	public string? Name { get; set; }
	public bool Display { get; set; }
	public IRoot? Effect { get; set; }
	public bool RenderTransparent { get; set; }
	public IRoot? TranslationCurve { get; set; }
	public IRoot? RotationCurve { get; set; }
	public Vector3 Scaling { get; set; }
}
