/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLocalPositionCurve : IRoot, ITriVectorFunction {
	public int Behavior { get; set; }
	public IRoot? Parent { get; set; }
	public IRoot? TurretSetObject { get; set; }
	public IRoot? ParentPositionCurve { get; set; }
	public IRoot? ParentRotationCurve { get; set; }
	public IRoot? AlignPositionCurve { get; set; }
	public float Offset { get; set; }
	public int LocatorIndex { get; set; }
	public string? LocatorSetName { get; set; }
	public Vector3 Value { get; set; }
	public Vector3 BoundingSize { get; set; }
	public Vector3 PositionOffset { get; set; }
	public int DamageLocatorIndex { get; set; }
	public float ImpactSize { get; set; }
	public int MuzzleIndex { get; set; }
}
