/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLineChildContainer : IRoot, IEveLineSetPath, INotify, IListNotify {
	public Vector3 Translation { get; set; } // Offset: 24, Size: 12, Type: FloatArray, Id: 23, Class: 
	public Vector3 Scaling { get; set; } // Offset: 36, Size: 12, Type: FloatArray, Id: 23, Class: 
	public Vector3 Rotation { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 23, Class: Rotation
	public string? Name { get; set; } // Offset: 200, Size: 8, Type: UTFString, Id: 19, Class: 
	public List<IRoot?>? Lines { get; set; } // Offset: 208, Size: 144, Type: Collection, Id: 17, Class: IList
	public bool IsVisible { get; set; } // Offset: 433, Size: 1, Type: Boolean, Id: 1, Class: 
	public bool Display { get; set; } // Offset: 434, Size: 1, Type: Boolean, Id: 19, Class: 
}
