/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveLineChildContainer : IRoot, IEveLineSetPath, INotify, IListNotify {
	public Vector3 Translation { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? Lines { get; set; }
	public bool IsVisible { get; set; }
	public bool Display { get; set; }
}
