/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveMeshOverlayEffect : IRoot, IInitialize, IListNotify, ITr2ControllerOwner, ITr2CurveSetOwner {
	public bool Display { get; set; } // Offset: 32, Size: 1, Type: Boolean, Id: 3, Class: 
	public bool Update { get; set; } // Offset: 33, Size: 1, Type: Boolean, Id: 3, Class: 
	public string? Name { get; set; } // Offset: 40, Size: 32, Type: String, Id: 19, Class: 
	public List<IRoot?>? OpaqueEffects { get; set; } // Offset: 72, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DecalEffects { get; set; } // Offset: 216, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? TransparentEffects { get; set; } // Offset: 360, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? AdditiveEffects { get; set; } // Offset: 504, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DistortionEffects { get; set; } // Offset: 648, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Controllers { get; set; } // Offset: 792, Size: 144, Type: Collection, Id: 17, Class: IList
	public IRoot? CurveSet { get; set; } // Offset: 936, Size: 8, Type: Object, Id: 19, Class: TriCurveSet
}
