/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveMultiEffect : IRoot, IEveSpaceObject2, ITr2ControllerOwner, IInitialize, ITr2DynamicBindingOwner, ITr2CurveSetOwner {
	public string? Name { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? Bindings { get; set; }
	public List<IRoot?>? Controllers { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
	public List<IRoot?>? ExternalParameters { get; set; }
}
