/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveMobile : EveSpaceObject2, IEveSpaceObject2, ITr2Renderable, IListNotify {
	public int ActiveTurretCount { get; set; }
	public List<IRoot?>? TurretSets { get; set; }
}
