/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveMeshOverlayEffect : IRoot, IInitialize, IListNotify, ITr2ControllerOwner, ITr2CurveSetOwner {
	public bool Display { get; set; }
	public bool Update { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? OpaqueEffects { get; set; }
	public List<IRoot?>? DecalEffects { get; set; }
	public List<IRoot?>? TransparentEffects { get; set; }
	public List<IRoot?>? AdditiveEffects { get; set; }
	public List<IRoot?>? DistortionEffects { get; set; }
	public List<IRoot?>? Controllers { get; set; }
	public TriCurveSet? CurveSet { get; set; }
}
