/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveOccluder : IRoot {
	public string? Name { get; set; }
	public bool Display { get; set; }
	public List<IRoot?>? Sprites { get; set; }
}
