/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveProjectBracket : IRoot, ITriFunction {
	[BlackUseNamePool]public string? Name { get; set; }
	public IRoot? TrackBall { get; set; }
	public float BallTrackingScaling { get; set; }
	public IRoot? TrackTransform { get; set; }
	public Vector3 TrackPosition { get; set; }
	public bool Dock { get; set; }
	public bool IsVisible { get; set; }
	public bool IsInFront { get; set; }
	public bool IntegerCoordinates { get; set; }
	public float MarginLeft { get; set; }
	public float MarginRight { get; set; }
	public float MarginTop { get; set; }
	public float MarginBottom { get; set; }
	public float MinDispRange { get; set; }
	public float MaxDispRange { get; set; }
	public float CameraDistance { get; set; }
	public float OffsetX { get; set; }
	public float OffsetY { get; set; }
	public IRoot? Parent { get; set; }
	public IRoot? Bracket { get; set; }
	public IRoot? BracketIcon { get; set; }
	public Vector3 ProjectedPosition { get; set; }
	public Vector3 RawProjectedPosition { get; set; }
}
