/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveProceduralMethodAttributeMap : IEveProceduralSelectionMethod, INotify, IRoot {
	public string? ThresholdAttribute { get; set; }
	public string? Seed_temp { get; set; }
	public int SelectedChild { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? DebugVolumes { get; set; }
}
