/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EvePlaneSetItem : IRoot {
	public string? Name { get; set; }
	public Vector3 Position { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public Vector4 Color { get; set; }
	public Vector4 Layer1Transform { get; set; }
	public Vector4 Layer2Transform { get; set; }
	public Vector4 Layer1Scroll { get; set; }
	public Vector4 Layer2Scroll { get; set; }
	public int BoneIndex { get; set; }
	public int MaskAtlasID { get; set; }
}
