/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EvePlanet : EveEffectRoot2, IEveSpaceObject2, ITr2SecondaryLightSource, ITr2CurveSetOwner, IEveEffectChildrenOwner, IShaderConfigurer, ITr2SoundEmitterOwner, IWorldPosition {
	public float EstimatedPixelDiameter { get; set; }
	public float Radius { get; set; }
	public float MinScreenSize { get; set; }
	public Vector4 AlbedoColor { get; set; }
	public Vector4 EmissiveColor { get; set; }
	public EveChildMesh? ZOnlyModel { get; set; }
}
