/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveProceduralMethodAttributeMapParameter : IRoot, INotify, IInitialize {
	public string? Name { get; set; }
	public EveChildRef? Child { get; set; }
}
