/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveProceduralMethodCycling : IRoot, IEveProceduralSelectionMethod, INotify {
	public int SelectedChild { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public bool RandomizeOrder { get; set; }
	public List<IRoot?>? DebugVolumes { get; set; }
	public float StartTimeOffset { get; set; }
}
