/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveProceduralMethodThresholds : IRoot, IEveProceduralSelectionMethod, INotify, IListNotify, IInitialize {
	public string? Name { get; set; }
	public string? ThresholdAttribute { get; set; }
	public float Seed_temp { get; set; }
	public int SelectedChild { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? DebugVolumes { get; set; }
}
