/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EvePlaneSetItem : IRoot {
	public string? Name { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public Vector3 Position { get; set; } // Offset: 16, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 28, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 40, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Vector3 Color { get; set; } // Offset: 56, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 Layer1Transform { get; set; } // Offset: 72, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer2Transform { get; set; } // Offset: 88, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer1Scroll { get; set; } // Offset: 104, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer2Scroll { get; set; } // Offset: 120, Size: 16, Type: FloatArray, Id: 19, Class: 
	public int BoneIndex { get; set; } // Offset: 136, Size: 4, Type: Int, Id: 19, Class: 
	public int MaskAtlasID { get; set; } // Offset: 140, Size: 4, Type: Int, Id: 19, Class: 
}
