/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveRootTransform : Tr2Transform, IEveSpaceObject2, ITriTargetable, ITr2Pickable, IWorldPosition {
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? Observers { get; set; }
	public int LodLevel { get; set; }
	public IRoot? TranslationCurve { get; set; }
	public IRoot? RotationCurve { get; set; }
	public IRoot? ModelRotationCurve { get; set; }
	public IRoot? ModelTranslationCurve { get; set; }
	public float BoundingSphereRadius { get; set; }
}
