/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveRemotePositionCurve : IRoot, ITriVectorFunction {
	public IRoot? StartPositionCurve { get; set; } // Offset: 8, Size: 8, Type: Object, Id: 19, Class: ITriVectorFunction
	public Vector3 Value { get; set; } // Offset: 16, Size: 12, Type: FloatArray, Id: 3, Class: 
	public Vector3 OffsetDir1 { get; set; } // Offset: 28, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 OffsetDir2 { get; set; } // Offset: 40, Size: 12, Type: FloatArray, Id: 19, Class: 
	public float DelayTime { get; set; } // Offset: 64, Size: 4, Type: Single, Id: 19, Class: 
	public float SweepTime { get; set; } // Offset: 68, Size: 4, Type: Single, Id: 19, Class: 
	public bool Cycle { get; set; } // Offset: 72, Size: 1, Type: Boolean, Id: 19, Class: 
}
