/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveRootTransform : Tr2Transform, IEveSpaceObject2, ITriTargetable, ITr2Pickable, IWorldPosition {
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? Observers { get; set; }
	public int LodLevel { get; set; }
	public object? TranslationCurve { get; set; }
	public object? RotationCurve { get; set; }
	public object? ModelRotationCurve { get; set; }
	public object? ModelTranslationCurve { get; set; }
	public float BoundingSphereRadius { get; set; }
}
