/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveRootTransform : Tr2Transform, IEveSpaceObject2, ITriTargetable, ITr2Pickable, IWorldPosition {
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? Observers { get; set; }
	public int LodLevel { get; set; }
	public ITriVectorFunction? TranslationCurve { get; set; }
	public ITriQuaternionFunction? RotationCurve { get; set; }
	public ITriQuaternionFunction? ModelRotationCurve { get; set; }
	public ITriVectorFunction? ModelTranslationCurve { get; set; }
	public float BoundingSphereRadius { get; set; }
}
