/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataArea : IRoot {
	[BlackArray] public EveSOFDataAreaMaterial? Primary { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Glass { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Sails { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Reactor { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Darkhull { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Rock { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Monument { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Ornament { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? SimplePrimary { get; set; }
	[BlackArray] public EveSOFDataAreaMaterial? Turret { get; set; }
}
