/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataDecalIndexBuffer : IRoot, ICustomPersist {
	[BlackArray(4)]public int[]? IndexBuffer { get; set; }
}
