/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataBlinkType : IRoot {
	public EveSOFDataBlink? Blink { get; set; }
	public EveSOFDataBlink? FadeIn { get; set; }
	public EveSOFDataBlink? FadeOut { get; set; }
	public EveSOFDataBlink? Cycle { get; set; }
}
