/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullSpotlightSetItem : IRoot {
	public Matrix4X4<float> Transform { get; set; }
	public int BoneIndex { get; set; }
	public int GroupIndex { get; set; }
	public bool BoosterGainInfluence { get; set; }
	public Vector3D<float> SpriteScale { get; set; }
	public float FlareIntensity { get; set; }
	public float SpriteIntensity { get; set; }
	public float ConeIntensity { get; set; }
	public float Saturation { get; set; }
	public int ColorType { get; set; }
	[BlackArray] public EveSOFDataSpotLightAttachment? Light { get; set; }
}
