/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullLocatorSetGroup : IRoot, IEveSOFDataHullLocatorSet {
	public string? Name { get; set; }
	public List<IRoot?>? LocatorSets { get; set; }
}
