/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataFactionVisibilityGroupSet : IRoot {
	public List<IRoot?>? VisibilityGroups { get; set; } // Offset: 8, Size: 144, Type: Collection, Id: 17, Class: IList
}
