/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSmartLightAttributeModifierExpressionBucket : EveSmartLightBaseAttributeModifier, IEveSmartLightGroupAttributeModifier, IInitialize, IRoot {
	public string? Name { get; set; }
	public List<IRoot?>? AttributeModifiers { get; set; }
	public float CurrentValue { get; set; }
	public string? Expression { get; set; }
	public List<IRoot?>? ExpressionInputs { get; set; }
}
