/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullExtensionPlacementDistributionParentMatch : IEveSOFDataHullExtensionPlacementDistribution, IRoot {
	public string? Name { get; set; }
	[BlackArray] public EveSOFDNADescriptor? ParentDescriptor { get; set; }
}
