/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataBlinkType : IRoot {
	[BlackArray] public EveSOFDataBlink? Blink { get; set; }
	[BlackArray] public EveSOFDataBlink? FadeIn { get; set; }
	[BlackArray] public EveSOFDataBlink? FadeOut { get; set; }
	[BlackArray] public EveSOFDataBlink? Cycle { get; set; }
}
