/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpherePin : IRoot, IInitialize, ITr2Renderable, IEveTransform, IEveSpaceObject2, ITr2Pickable, INotify {
	public string? Name { get; set; } // Offset: 72, Size: 32, Type: String, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 104, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 116, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Vector3 Translation { get; set; } // Offset: 132, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 CenterNormal { get; set; } // Offset: 208, Size: 12, Type: FloatArray, Id: 23, Class: 
	public float PinMaxRadius { get; set; } // Offset: 220, Size: 4, Type: Single, Id: 23, Class: 
	public float PinRadius { get; set; } // Offset: 224, Size: 4, Type: Single, Id: 23, Class: 
	public float PinRotation { get; set; } // Offset: 228, Size: 4, Type: Single, Id: 23, Class: 
	public Vector3 PinColor { get; set; } // Offset: 232, Size: 16, Type: FloatArray, Id: 23, Class: Color
	public Vector3 Color { get; set; } // Offset: 232, Size: 16, Type: FloatArray, Id: 23, Class: Color
	public float PinAlphaThreshold { get; set; } // Offset: 248, Size: 4, Type: Single, Id: 23, Class: 
	public Vector3 UvAtlasScaleOffset { get; set; } // Offset: 252, Size: 16, Type: FloatArray, Id: 23, Class: 
	public string? PinEffectResPath { get; set; } // Offset: 272, Size: 32, Type: String, Id: 23, Class: 
	public IRoot? PinEffect { get; set; } // Offset: 304, Size: 8, Type: Object, Id: 19, Class: Tr2Effect
	public bool EnablePicking { get; set; } // Offset: 312, Size: 1, Type: Boolean, Id: 19, Class: 
	public IRoot? PickEffect { get; set; } // Offset: 320, Size: 8, Type: Object, Id: 1, Class: Tr2Effect
	public string? GeometryResPath { get; set; } // Offset: 328, Size: 32, Type: String, Id: 23, Class: 
	public bool Display { get; set; } // Offset: 384, Size: 1, Type: Boolean, Id: 19, Class: 
	public float SortValueMultiplier { get; set; } // Offset: 388, Size: 4, Type: Single, Id: 19, Class: 
	public List<IRoot?>? CurveSets { get; set; } // Offset: 392, Size: 144, Type: Collection, Id: 17, Class: IList
	public int PrimitiveCount { get; set; } // Offset: 536, Size: 4, Type: Int, Id: 1, Class: 
}
