/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSmartLightAttributeModifierCameraDependency : EveSmartLightAttributeModifierBucket, IEveSmartLightGroupAttributeModifier, IRoot {
	public bool UseCameraDistance { get; set; }
	public bool InverseDistanceFormula { get; set; }
	public bool UseCameraLookAt { get; set; }
	public bool InverselookAtFormula { get; set; }
	public bool UseCameraPlacement { get; set; }
	public bool InversePlacementFormula { get; set; }
	public bool OverwritePosition { get; set; }
	public bool OverwriteObjectDirection { get; set; }
	public float MinimumActivation { get; set; }
	public float MaximumActivation { get; set; }
	public float MinimumDistance { get; set; }
	public float MaximumDistance { get; set; }
	public float LookAtIntensity { get; set; }
	public float LookAtVisionCone { get; set; }
	public float PlacementIntensity { get; set; }
	public Vector3D<float> PositionOverwrite { get; set; }
	public Vector3D<float> AngleOverwrite { get; set; }
}
