/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterString : IEveSocketParameter, IRoot {
	public string? Name { get; set; }
	public string? Value { get; set; }
}
