/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataPatternMaterialOverride : IRoot {
	public bool IsTargetMtl1 { get; set; }
	public bool IsTargetMtl2 { get; set; }
	public bool IsTargetMtl3 { get; set; }
	public bool IsTargetMtl4 { get; set; }
}
