/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataMultiHullDecalIndexBuffers : IRoot {
	public string? CombinedGeometryResPath { get; set; }
	[JsonIgnore] public List<IRoot?>? IndexBuffers { get; set; }
}
