/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHull : IRoot {
	public string? Name { get; set; }
	public string? Description { get; set; }
	public string? Category { get; set; }
	public int BuildClass { get; set; }
	public string? GeometryResFilePath { get; set; }
	public Vector4D<float> BoundingSphere { get; set; }
	public Vector3D<float> ShapeEllipsoidCenter { get; set; }
	public Vector3D<float> ShapeEllipsoidRadius { get; set; }
	public bool IsSkinned { get; set; }
	public bool EnableDynamicBoundingSphere { get; set; }
	public bool CastShadow { get; set; }
	public bool Sof6 { get; set; }
	public List<IRoot?>? OpaqueAreas { get; set; }
	public List<IRoot?>? DecalAreas { get; set; }
	public List<IRoot?>? TransparentAreas { get; set; }
	public List<IRoot?>? AdditiveAreas { get; set; }
	public List<IRoot?>? DistortionAreas { get; set; }
	public EveSOFDataPatternPerHull? DefaultPattern { get; set; }
	public List<IRoot?>? SpriteSets { get; set; }
	public List<IRoot?>? SpotlightSets { get; set; }
	public List<IRoot?>? PlaneSets { get; set; }
	public List<IRoot?>? SpriteLineSets { get; set; }
	public List<IRoot?>? HazeSets { get; set; }
	public List<IRoot?>? Banners { get; set; }
	public List<IRoot?>? BannerSets { get; set; }
	public List<IRoot?>? DecalSets { get; set; }
	public List<IRoot?>? LightSets { get; set; }
	public int ImpactEffectType { get; set; }
	public EveSOFDataHullBooster? Booster { get; set; }
	public Vector3D<float> AudioPosition { get; set; }
	public List<IRoot?>? LocatorTurrets { get; set; }
	public List<IRoot?>? LocatorSets { get; set; }
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? ChildSets { get; set; }
	public List<IRoot?>? InstancedMeshes { get; set; }
	public List<IRoot?>? Animations { get; set; }
	public List<IRoot?>? SoundEmitters { get; set; }
	public List<IRoot?>? Controllers { get; set; }
	public string? ModelRotationCurvePath { get; set; }
	public string? ModelTranslationCurvePath { get; set; }
}
