/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullSpotlightSetItem : IRoot {
	public Matrix4x4 Transform { get; set; }
	public int BoneIndex { get; set; }
	public int GroupIndex { get; set; }
	public bool BoosterGainInfluence { get; set; }
	public Vector3 SpriteScale { get; set; }
	public float FlareIntensity { get; set; }
	public float SpriteIntensity { get; set; }
	public float ConeIntensity { get; set; }
	public float Saturation { get; set; }
	public int ColorType { get; set; }
	public IRoot? Light { get; set; }
}
