/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSocketParameterString : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public string? Value { get; set; }
}
