/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveShip2Builder : IRoot {
	public List<IRoot?>? GrannyResources { get; set; } // Offset: 472, Size: 144, Type: Collection, Id: 1, Class: IList
	public List<IRoot?>? Hulls { get; set; } // Offset: 616, Size: 144, Type: Collection, Id: 1, Class: IList
	public string? OutputFilename { get; set; } // Offset: 760, Size: 32, Type: String, Id: 3, Class: 
}
