/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataBoosterShape : IRoot {
	public float NoiseFunction { get; set; }
	public float NoiseSpeed { get; set; }
	public Vector4 NoiseAmplitureStart { get; set; }
	public Vector4 NoiseAmplitureEnd { get; set; }
	public Vector4 NoiseFrequency { get; set; }
	public Vector4 Color { get; set; }
}
