/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSmartLightAttributeModifierControllerVariableListener : EveSmartLightBaseAttributeModifier, IEveSmartLightGroupAttributeModifier, IInitialize, INotify, IRoot {
	public float CurrentValue { get; set; }
	public string? Expression { get; set; }
	public List<IRoot?>? ExpressionInputs { get; set; }
	public string? VariableName { get; set; }
	public float Value { get; set; }
	public float DefaultValue { get; set; }
	public bool InvertReceivedValue { get; set; }
}
