/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullHazeSetItem : IRoot {
	public Vector3 Position { get; set; }
	public Vector3 Scaling { get; set; }
	public int BoneIndex { get; set; }
	public Vector4 Rotation { get; set; }
	public int ColorType { get; set; }
	public float HazeBrightness { get; set; }
	public float HazeFalloff { get; set; }
	public float SourceSize { get; set; }
	public float SourceBrightness { get; set; }
	public float Saturation { get; set; }
	public bool BoosterGainInfluence { get; set; }
	public List<IRoot?>? Lights { get; set; }
}
