/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveStarfield : IRoot, IInitialize, INotify {
	public bool Display { get; set; } // Offset: 32, Size: 1, Type: Boolean, Id: 19, Class: 
	public int NumStars { get; set; } // Offset: 36, Size: 4, Type: Int, Id: 23, Class: 
	public int Seed { get; set; } // Offset: 40, Size: 4, Type: Int, Id: 23, Class: 
	public float MaxDist { get; set; } // Offset: 44, Size: 4, Type: Single, Id: 23, Class: 
	public float MinDist { get; set; } // Offset: 48, Size: 4, Type: Single, Id: 23, Class: 
	public float MinFlashRate { get; set; } // Offset: 52, Size: 4, Type: Single, Id: 23, Class: 
	public float MaxFlashRate { get; set; } // Offset: 56, Size: 4, Type: Single, Id: 23, Class: 
	public float MinFlashIntensity { get; set; } // Offset: 60, Size: 4, Type: Single, Id: 23, Class: 
	public IRoot? Effect { get; set; } // Offset: 72, Size: 8, Type: Object, Id: 19, Class: Tr2Effect
}
