/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSmartLightBaseGroup : IEveSmartLightGroup, IListNotify, IRoot {
	public Vector4D<float> ActiveColor { get; set; }
	public List<IRoot?>? AttributeModifiers { get; set; }
	public Vector4D<float> CustomColor { get; set; }
	public int FactionColor { get; set; }
	public bool UseFactionColor { get; set; }
}
