/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterVector4 : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public Vector4 Value { get; set; }
}
