/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullSpotlightSetItem : IRoot {
	public Matrix4x4 Transform { get; set; } // Offset: 8, Size: 64, Type: FloatArray, Id: 19, Class: Matrix
	public int BoneIndex { get; set; } // Offset: 72, Size: 4, Type: Int, Id: 19, Class: 
	public int GroupIndex { get; set; } // Offset: 76, Size: 4, Type: Int, Id: 19, Class: 
	public bool BoosterGainInfluence { get; set; } // Offset: 80, Size: 1, Type: Boolean, Id: 19, Class: 
	public Vector3 SpriteScale { get; set; } // Offset: 84, Size: 12, Type: FloatArray, Id: 19, Class: 
	public float FlareIntensity { get; set; } // Offset: 96, Size: 4, Type: Single, Id: 19, Class: 
	public float SpriteIntensity { get; set; } // Offset: 100, Size: 4, Type: Single, Id: 19, Class: 
	public float ConeIntensity { get; set; } // Offset: 104, Size: 4, Type: Single, Id: 19, Class: 
	public float Saturation { get; set; } // Offset: 108, Size: 4, Type: Single, Id: 19, Class: 
	public int ColorType { get; set; } // Offset: 112, Size: 4, Type: Int, Id: 531, Class: 
	public IRoot? Light { get; set; } // Offset: 120, Size: 8, Type: Object, Id: 19, Class: EveSOFDataSpotLightAttachment
}
