/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataFactionColorSet : IRoot {
	public Vector4 Primary { get; set; }
	public Vector4 Secondary { get; set; }
	public Vector4 Tertiary { get; set; }
	public Vector4 Black { get; set; }
	public Vector4 White { get; set; }
	public Vector4 Yellow { get; set; }
	public Vector4 Orange { get; set; }
	public Vector4 Red { get; set; }
	public Vector4 Blue { get; set; }
	public Vector4 Green { get; set; }
	public Vector4 Cyan { get; set; }
	public Vector4 Fire { get; set; }
	public Vector4 Hull { get; set; }
	public Vector4 Glass { get; set; }
	public Vector4 Reactor { get; set; }
	public Vector4 Darkhull { get; set; }
	public Vector4 Booster { get; set; }
	public Vector4 Killmark { get; set; }
	public Vector4 PrimaryLight { get; set; }
	public Vector4 SecondaryLight { get; set; }
	public Vector4 TertiaryLight { get; set; }
	public Vector4 WhiteLight { get; set; }
	public Vector4 PrimaryHologram { get; set; }
	public Vector4 SecondaryHologram { get; set; }
	public Vector4 TertiaryHologram { get; set; }
	public Vector4 State0 { get; set; }
	public Vector4 State1 { get; set; }
	public Vector4 State2 { get; set; }
	public Vector4 State3 { get; set; }
	public Vector4 StateVulnerable { get; set; }
	public Vector4 StateInvulnerable { get; set; }
	public Vector4 PrimaryForcefield { get; set; }
	public Vector4 SecondaryForcefield { get; set; }
	public Vector4 PrimaryBanner { get; set; }
	public Vector4 PrimaryFx { get; set; }
	public Vector4 SecondaryFx { get; set; }
	public Vector4 PrimarySpotlight { get; set; }
	public Vector4 SecondarySpotlight { get; set; }
	public Vector4 TertiarySpotlight { get; set; }
	public Vector4 PrimaryBillboard { get; set; }
	public Vector4 PrimaryWarpFx { get; set; }
	public Vector4 PrimaryAttackFX { get; set; }
	public Vector4 PrimarySiegeFX { get; set; }
	public Vector4 PrimaryDockedFX { get; set; }
}
