/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionPlacementDistributionDepletionCounter : IRoot, IEveSOFDataHullExtensionPlacementDistribution {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public List<IRoot?>? DepletionCounters { get; set; } // Offset: 40, Size: 144, Type: Collection, Id: 17, Class: IList
}
