/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpaceObjectDecal : IRoot, INotify, IInitialize, ITr2Renderable, ITr2Pickable {
	public bool HasStaticIndexBuffers { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public string? Name { get; set; } // Offset: 48, Size: 32, Type: String, Id: 19, Class: 
	public bool Display { get; set; } // Offset: 80, Size: 1, Type: Boolean, Id: 3, Class: 
	public IRoot? DecalEffect { get; set; } // Offset: 200, Size: 8, Type: Object, Id: 19, Class: Tr2Effect
	public Vector3 Position { get; set; } // Offset: 208, Size: 12, Type: FloatArray, Id: 23, Class: 
	public Vector3 Rotation { get; set; } // Offset: 220, Size: 16, Type: FloatArray, Id: 23, Class: Rotation
	public Vector3 Scaling { get; set; } // Offset: 236, Size: 12, Type: FloatArray, Id: 23, Class: 
	public int ParentBoneIndex { get; set; } // Offset: 248, Size: 4, Type: Int, Id: 19, Class: 
	public float MinScreenSize { get; set; } // Offset: 576, Size: 4, Type: Single, Id: 19, Class: 
}
