/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataGenericShader : IRoot {
	public string? Shader { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public string? TransparencyTextureName { get; set; } // Offset: 16, Size: 8, Type: UTFString, Id: 19, Class: 
	public bool DoGenerateDepthArea { get; set; } // Offset: 24, Size: 1, Type: Boolean, Id: 19, Class: 
	public List<IRoot?>? Parameters { get; set; } // Offset: 32, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DefaultTextures { get; set; } // Offset: 176, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DefaultParameters { get; set; } // Offset: 320, Size: 144, Type: Collection, Id: 17, Class: IList
}
