/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataBlinkType : IRoot {
	public IRoot? Blink { get; set; }
	public IRoot? FadeIn { get; set; }
	public IRoot? FadeOut { get; set; }
	public IRoot? Cycle { get; set; }
}
