/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataInstancedMesh : IRoot {
	public string? Name { get; set; }
	public int LowestLodVisible { get; set; }
	public int DisplayModifier { get; set; }
	public string? GeometryResPath { get; set; }
	[BlackArray]public byte[][]? Instances { get; set; }
	public string? Shader { get; set; }
	public List<IRoot?>? Textures { get; set; }
}
