/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataFactionChild : IRoot {
	public int GroupIndex { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 19, Class: 
	public bool IsVisible { get; set; } // Offset: 12, Size: 1, Type: Boolean, Id: 19, Class: 
	public string? Name { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
}
