/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataGenericShader : IRoot {
	public string? Shader { get; set; }
	public string? TransparencyTextureName { get; set; }
	public bool DoGenerateDepthArea { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? DefaultTextures { get; set; }
	public List<IRoot?>? DefaultParameters { get; set; }
}
