/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSocketParameterFloat : IRoot, IEveSocketParameter {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public float Value { get; set; } // Offset: 184, Size: 4, Type: Single, Id: 19, Class: 
}
