/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataGenericHullDamage : IRoot {
	public float HullParticleRate { get; set; }
	public float HullParticleInnerAngle { get; set; }
	public float HullParticleAngle { get; set; }
	public float HullParticleColorMidpoint { get; set; }
	public Vector2D<float> HullParticleMinMaxSpeed { get; set; }
	public Vector2D<float> HullParticleMinMaxLifeTime { get; set; }
	public Vector4D<float> HullParticleSizes { get; set; }
	public Vector4D<float> HullParticleColor0 { get; set; }
	public Vector4D<float> HullParticleColor1 { get; set; }
	public Vector4D<float> HullParticleColor2 { get; set; }
	public Vector4D<float> HullParticleColor3 { get; set; }
	public int HullParticleTextureIndex { get; set; }
	public float HullParticleVelocityStretchRotation { get; set; }
	public float HullParticleDrag { get; set; }
	public float HullParticleTurbulenceAmplitude { get; set; }
	public int HullParticleTurbulenceFrequency { get; set; }
}
