/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpotlightSetItem : IRoot {
	public string? Name { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public Matrix4x4 Transform { get; set; } // Offset: 16, Size: 64, Type: FloatArray, Id: 19, Class: Matrix
	public Vector3 SpriteScale { get; set; } // Offset: 80, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 ConeColor { get; set; } // Offset: 92, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 SpriteColor { get; set; } // Offset: 108, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 FlareColor { get; set; } // Offset: 124, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public int BoneIndex { get; set; } // Offset: 140, Size: 4, Type: Int, Id: 19, Class: 
	public bool BoosterGainInfluence { get; set; } // Offset: 144, Size: 1, Type: Boolean, Id: 19, Class: 
}
