/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullDecalSet : IRoot {
	public string? Name { get; set; }
	public string? VisibilityGroup { get; set; }
	public List<IRoot?>? Items { get; set; }
}
