/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionPlacementDistributionParentMatch : IRoot, IEveSOFDataHullExtensionPlacementDistribution {
	public string? Name { get; set; }
	public object? ParentDescriptor { get; set; }
}
