/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullSpriteSetItem : IRoot {
	public Vector3D<float> Position { get; set; }
	public float BlinkRate { get; set; }
	public float BlinkPhase { get; set; }
	public float MinScale { get; set; }
	public float MaxScale { get; set; }
	public float Falloff { get; set; }
	public float Intensity { get; set; }
	public float Saturation { get; set; }
	public int BoneIndex { get; set; }
	public int ColorType { get; set; }
	public EveSOFDataPointLightAttachment? Light { get; set; }
}
