/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataBoosterShape : IRoot {
	public float NoiseFunction { get; set; }
	public float NoiseSpeed { get; set; }
	public Vector3 NoiseAmplitureStart { get; set; }
	public Vector3 NoiseAmplitureEnd { get; set; }
	public Vector3 NoiseFrequency { get; set; }
	public Vector3 Color { get; set; }
}
