/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveShip2 : EveMobile, IEveSpaceObject2, ITr2Renderable, IListNotify {
	public object? AudioSpeedParameter { get; set; }
	public float MaxSpeed { get; set; }
	public object? Speed { get; set; }
	public object? Boosters { get; set; }
	public int DisplayKillCounterValue { get; set; }
}
