/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionPlacementDistributionRandomChance : IRoot, IEveSOFDataHullExtensionPlacementDistribution {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public float ChanceOfUsage { get; set; } // Offset: 40, Size: 4, Type: Single, Id: 19, Class: 
}
