/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullLocatorSetGroup : IRoot, IEveSOFDataHullLocatorSet {
	public string? Name { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public List<IRoot?>? LocatorSets { get; set; } // Offset: 16, Size: 144, Type: Collection, Id: 17, Class: IList
}
