/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataFaction : IRoot {
	public string? Description { get; set; }
	public string? Name { get; set; }
	public string? ResPathInsert { get; set; }
	public List<IRoot?>? SpotlightSets { get; set; }
	public List<IRoot?>? PlaneSets { get; set; }
	public List<IRoot?>? Children { get; set; }
	[BlackArray] public EveSOFDataFactionVisibilityGroupSet? VisibilityGroupSet { get; set; }
	[BlackArray] public EveSOFDataFactionColorSet? ColorSet { get; set; }
	[BlackArray] public EveSOFDataLogoSet? LogoSet { get; set; }
	public int MaterialUsageMtl1 { get; set; }
	public int MaterialUsageMtl2 { get; set; }
	public int MaterialUsageMtl3 { get; set; }
	public int MaterialUsageMtl4 { get; set; }
	[BlackArray] public EveSOFDataArea? AreaTypes { get; set; }
	[BlackArray] public EveSOFDataPatternLayer? DefaultPattern { get; set; }
	public string? DefaultPatternLayer1MaterialName { get; set; }
	public string? DefaultPatternLayer2MaterialName { get; set; }
	public string? DefaultPatternName { get; set; }
}
