/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullExtensionPlacement : IEveSOFDataHullExtensionPlacement, IRoot {
	public string? Name { get; set; }
	public string? LocatorSetName { get; set; }
	public bool Enabled { get; set; }
	public bool IsInstanced { get; set; }
	public bool IsShared { get; set; }
	public bool ExtendsShieldEllipsoid { get; set; }
	public bool ExtendsBoundingSphere { get; set; }
	public Vector3D<float> Offset { get; set; }
	[BlackArray] public EveSOFDataHullExtensionPlacementDistributionPlacement? Distribution { get; set; }
	public List<IRoot?>? DistributionConditions { get; set; }
	[BlackArray] public EveSOFDNADescriptor? Descriptor { get; set; }
}
