/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveStretch : IRoot, IEveTransform, IEveSpaceObject2, IEveFiringEffectElement, ITr2DebugRenderable, ITr2LightOwner {
	public int LodLevel { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public bool Update { get; set; }
	public bool UseCurveLod { get; set; }
	public object? Source { get; set; }
	public object? Dest { get; set; }
	public object? SourceObject { get; set; }
	public object? DestObject { get; set; }
	public object? StretchObject { get; set; }
	public object? MoveObject { get; set; }
	public List<IRoot?>? SourceLights { get; set; }
	public List<IRoot?>? DestLights { get; set; }
	public object? ProgressCurve { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
	public object? MoveCompletion { get; set; }
	public bool MoveCompleted { get; set; }
	public bool Moving { get; set; }
	public long StartTime { get; set; }
	public object? Length { get; set; }
	public object? Audio { get; set; }
}
