/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSprite2dBracketRenderer : Tr2SpriteObject {
	public List<IRoot?>? Brackets { get; set; }
	public object? IconAtlas { get; set; }
}
