/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullPlaneSetItem : IRoot {
	public Vector3 Position { get; set; }
	public Vector3 Scaling { get; set; }
	public Vector4 Rotation { get; set; }
	public Vector4 Color { get; set; }
	public int ColorType { get; set; }
	public float Intensity { get; set; }
	public float Saturation { get; set; }
	public Vector4 Layer1Transform { get; set; }
	public Vector4 Layer2Transform { get; set; }
	public Vector4 Layer1Scroll { get; set; }
	public Vector4 Layer2Scroll { get; set; }
	public int BoneIndex { get; set; }
	public int GroupIndex { get; set; }
	public int MaskMapAtlasIndex { get; set; }
	public float BlinkRate { get; set; }
	public float BlinkPhase { get; set; }
	public int BlinkMode { get; set; }
	public List<IRoot?>? Lights { get; set; }
}
