/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionBucket : IRoot {
	public string? Name { get; set; }
	public List<IRoot?>? DepletionCounters { get; set; }
	public List<IRoot?>? Placements { get; set; }
}
