/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullChild : IRoot {
	public string? Name { get; set; }
	public string? RedFilePath { get; set; }
	public int LowestLodVisible { get; set; }
	public Vector3 Translation { get; set; }
	public Vector3 Rotation { get; set; }
	public Vector3 Scaling { get; set; }
	public int Id { get; set; }
	public int GroupIndex { get; set; }
	public int BuildFilter { get; set; }
}
