/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionPlacementGroup : IRoot, IEveSOFDataHullExtensionPlacement {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public bool Enabled { get; set; } // Offset: 40, Size: 1, Type: Boolean, Id: 19, Class: 
	public List<IRoot?>? DepletionCounters { get; set; } // Offset: 48, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? Placements { get; set; } // Offset: 192, Size: 144, Type: Collection, Id: 17, Class: IList
	public List<IRoot?>? DistributionConditions { get; set; } // Offset: 336, Size: 144, Type: Collection, Id: 17, Class: IList
}
