/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullDecalSet : IRoot {
	public string? Name { get; set; }
	public string? VisibilityGroup { get; set; }
	public List<IRoot?>? Items { get; set; }
}
