/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataPatternLayer : IRoot {
	public string? TextureName { get; set; } // Offset: 8, Size: 8, Type: UTFString, Id: 19, Class: 
	public string? TextureResFilePath { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
	public int ProjectionTypeU { get; set; } // Offset: 48, Size: 4, Type: Int, Id: 531, Class: 
	public int ProjectionTypeV { get; set; } // Offset: 52, Size: 4, Type: Int, Id: 531, Class: 
	public int MaterialSource { get; set; } // Offset: 56, Size: 4, Type: Int, Id: 531, Class: 
	public bool IsTargetMtl1 { get; set; } // Offset: 60, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl2 { get; set; } // Offset: 61, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl3 { get; set; } // Offset: 62, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl4 { get; set; } // Offset: 63, Size: 1, Type: Boolean, Id: 19, Class: 
}
