/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpaceObject2 : IRoot, EveEntity, IEveShadowCaster, IInitialize, ITr2Pickable, ITriTargetable, IWorldPosition, ITr2ShLightingReceiver, INotify, ITr2SecondaryLightSource, ITr2ImpostorSource, ITr2CurveSetOwner, IEveEffectChildrenOwner, IShaderConfigurer, ITr2SoundEmitterOwner, ITr2ControllerOwner, ITr2GrannyAnimationOwner, IEveInheritPropertiesOwner, IEveSpaceObjectDecalOwner, ITr2LightOwner, IEveSpaceObjectAttachmentOwner {
	public bool Mute { get; set; }
	public float ActivationStrength { get; set; }
	public string? Name { get; set; }
	public string? Dna { get; set; }
	public bool Update { get; set; }
	public bool Display { get; set; }
	public bool IsPickable { get; set; }
	public bool IsAnimated { get; set; }
	public bool CastShadow { get; set; }
	public Vector3 WorldPosition { get; set; }
	public Vector3 WorldRotation { get; set; }
	public float ModelScale { get; set; }
	public IRoot? Mesh { get; set; }
	public IRoot? MeshLod { get; set; }
	public int LodLevel { get; set; }
	public float ClipSphereFactor { get; set; }
	public Vector3 ClipSphereCenter { get; set; }
	public float EstimatedPixelDiameter { get; set; }
	public float EstimatedPixelDiameterWithChildren { get; set; }
	public IRoot? AnimationUpdater { get; set; }
	public Vector3 BoundingSphereCenter { get; set; }
	public float BoundingSphereRadius { get; set; }
	public Vector3 ModelWorldPosition { get; set; }
	public Vector3 ShapeEllipsoidCenter { get; set; }
	public Vector3 ShapeEllipsoidRadius { get; set; }
	public Vector3 GeneratedShapeEllipsoidCenter { get; set; }
	public Vector3 GeneratedShapeEllipsoidRadius { get; set; }
	public List<IRoot?>? OverlayEffects { get; set; }
	public List<IRoot?>? Decals { get; set; }
	public List<IRoot?>? Locators { get; set; }
	public IRoot? ImpactOverlay { get; set; }
	public int LastDamageLocatorHit { get; set; }
	public List<IRoot?>? Observers { get; set; }
	public IRoot? TranslationCurve { get; set; }
	public IRoot? RotationCurve { get; set; }
	public IRoot? ModelRotationCurve { get; set; }
	public IRoot? ModelTranslationCurve { get; set; }
	public List<IRoot?>? LocatorSets { get; set; }
	public List<IRoot?>? Lights { get; set; }
	public Vector3 AlbedoColor { get; set; }
	public float SecondaryLightingSphereRadius { get; set; }
	public List<IRoot?>? Attachments { get; set; }
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? EffectChildren { get; set; }
	public IRoot? InheritProperties { get; set; }
	public List<IRoot?>? CustomMasks { get; set; }
	public float DirtLevel { get; set; }
	public IRoot? PositionDelta { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
	public bool DynamicBoundingSphereEnabled { get; set; }
	public List<IRoot?>? ExternalParameters { get; set; }
	public List<IRoot?>? Controllers { get; set; }
	public int ReflectionMode { get; set; }
}
