/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpotlightSet : IRoot, IInitialize, IEveSpaceObjectAttachment {
	public bool Display { get; set; }
	public bool Skinned { get; set; }
	public string? Name { get; set; }
	public float Intensity { get; set; }
	public List<IRoot?>? SpotlightItems { get; set; }
	public object? ConeEffect { get; set; }
	public object? GlowEffect { get; set; }
}
