/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterBool : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public bool Value { get; set; }
}
