/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullExtensionPlacementDistributionPlacement : IRoot {
	public string? Name { get; set; }
	public float Completeness { get; set; }
	public Vector3 PlacementBias { get; set; }
	public float CenterBias { get; set; }
	public int Cap { get; set; }
	public Vector4 RandomRotationStepSizeYPR { get; set; }
	public Vector3 RandomRotationMaxSteps { get; set; }
	public Vector3 RandomScaleMin { get; set; }
	public Vector3 RandomScaleMax { get; set; }
	public bool UniformScale { get; set; }
	public bool OccupyLocators { get; set; }
}
