/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullLocatorSetGroup : IRoot, IEveSOFDataHullLocatorSet {
	public string? Name { get; set; }
	public List<IRoot?>? LocatorSets { get; set; }
}
