/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullSpriteLineSetItem : IRoot {
	public Vector3D<float> Position { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public float Spacing { get; set; }
	public float BlinkRate { get; set; }
	public float BlinkPhase { get; set; }
	public float BlinkPhaseShift { get; set; }
	public float MinScale { get; set; }
	public float MaxScale { get; set; }
	public float Falloff { get; set; }
	public float Intensity { get; set; }
	public float Saturation { get; set; }
	public int BoneIndex { get; set; }
	public bool IsCircle { get; set; }
	public int ColorType { get; set; }
	public EveSOFDataPointLightAttachment? Light { get; set; }
}
