/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataBooster : IRoot {
	public float GlowScale { get; set; } // Offset: 8, Size: 4, Type: Single, Id: 19, Class: 
	public float SymHaloScale { get; set; } // Offset: 12, Size: 4, Type: Single, Id: 19, Class: 
	public float HaloScaleX { get; set; } // Offset: 16, Size: 4, Type: Single, Id: 19, Class: 
	public float HaloScaleY { get; set; } // Offset: 20, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 GlowColor { get; set; } // Offset: 24, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 HaloColor { get; set; } // Offset: 40, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 TrailColor { get; set; } // Offset: 56, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 WarpGlowColor { get; set; } // Offset: 72, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 WarpHalpColor { get; set; } // Offset: 88, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 TrailSize { get; set; } // Offset: 104, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Scale { get; set; } // Offset: 120, Size: 16, Type: FloatArray, Id: 19, Class: 
	public IRoot? Shape0 { get; set; } // Offset: 136, Size: 8, Type: Object, Id: 19, Class: EveSOFDataBoosterShape
	public IRoot? Shape1 { get; set; } // Offset: 144, Size: 8, Type: Object, Id: 19, Class: EveSOFDataBoosterShape
	public IRoot? WarpShape0 { get; set; } // Offset: 152, Size: 8, Type: Object, Id: 19, Class: EveSOFDataBoosterShape
	public IRoot? WarpShape1 { get; set; } // Offset: 160, Size: 8, Type: Object, Id: 19, Class: EveSOFDataBoosterShape
	public string? ShapeAtlasResPath { get; set; } // Offset: 168, Size: 32, Type: String, Id: 19, Class: 
	public string? Gradient0ResPath { get; set; } // Offset: 200, Size: 32, Type: String, Id: 19, Class: 
	public string? Gradient1ResPath { get; set; } // Offset: 232, Size: 32, Type: String, Id: 19, Class: 
	public int ShapeAtlasHeight { get; set; } // Offset: 264, Size: 4, Type: Int, Id: 19, Class: 
	public int ShapeAtlasCount { get; set; } // Offset: 268, Size: 4, Type: Int, Id: 19, Class: 
	public float LightOffset { get; set; } // Offset: 272, Size: 4, Type: Single, Id: 19, Class: 
	public float LightRadius { get; set; } // Offset: 276, Size: 4, Type: Single, Id: 19, Class: 
	public float LightWarpRadius { get; set; } // Offset: 280, Size: 4, Type: Single, Id: 19, Class: 
	public float LightFlickerAmplitude { get; set; } // Offset: 284, Size: 4, Type: Single, Id: 19, Class: 
	public float LightFlickerFrequency { get; set; } // Offset: 288, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 LightColor { get; set; } // Offset: 292, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 LightWarpColor { get; set; } // Offset: 308, Size: 16, Type: FloatArray, Id: 19, Class: Color
}
