/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullPlaneSetItem : IRoot {
	public Vector3 Position { get; set; } // Offset: 8, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 20, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 32, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Vector3 Color { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public int ColorType { get; set; } // Offset: 64, Size: 4, Type: Int, Id: 531, Class: 
	public float Intensity { get; set; } // Offset: 68, Size: 4, Type: Single, Id: 19, Class: 
	public float Saturation { get; set; } // Offset: 72, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 Layer1Transform { get; set; } // Offset: 76, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer2Transform { get; set; } // Offset: 92, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer1Scroll { get; set; } // Offset: 108, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 Layer2Scroll { get; set; } // Offset: 124, Size: 16, Type: FloatArray, Id: 19, Class: 
	public int BoneIndex { get; set; } // Offset: 140, Size: 4, Type: Int, Id: 19, Class: 
	public int GroupIndex { get; set; } // Offset: 144, Size: 4, Type: Int, Id: 19, Class: 
	public int MaskMapAtlasIndex { get; set; } // Offset: 148, Size: 4, Type: Int, Id: 19, Class: 
	public float BlinkRate { get; set; } // Offset: 152, Size: 4, Type: Single, Id: 19, Class: 
	public float BlinkPhase { get; set; } // Offset: 156, Size: 4, Type: Single, Id: 19, Class: 
	public int BlinkMode { get; set; } // Offset: 164, Size: 4, Type: Int, Id: 531, Class: 
	public List<IRoot?>? Lights { get; set; } // Offset: 168, Size: 144, Type: Collection, Id: 17, Class: IList
}
