/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataGenericHullDamage : IRoot {
	public float HullParticleRate { get; set; }
	public float HullParticleInnerAngle { get; set; }
	public float HullParticleAngle { get; set; }
	public float HullParticleColorMidpoint { get; set; }
	public Vector2 HullParticleMinMaxSpeed { get; set; }
	public Vector2 HullParticleMinMaxLifeTime { get; set; }
	public Vector4 HullParticleSizes { get; set; }
	public Vector4 HullParticleColor0 { get; set; }
	public Vector4 HullParticleColor1 { get; set; }
	public Vector4 HullParticleColor2 { get; set; }
	public Vector4 HullParticleColor3 { get; set; }
	public int HullParticleTextureIndex { get; set; }
	public float HullParticleVelocityStretchRotation { get; set; }
	public float HullParticleDrag { get; set; }
	public float HullParticleTurbulenceAmplitude { get; set; }
	public int HullParticleTurbulenceFrequency { get; set; }
}
