/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSpriteSet : IRoot, IInitialize, IEveSpaceObjectAttachment {
	public bool Display { get; set; }
	public bool Skinned { get; set; }
	public string? Name { get; set; }
	public float Intensity { get; set; }
	public List<IRoot?>? Sprites { get; set; }
	public Tr2Effect? Effect { get; set; }
}
