/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullSpriteLineSet : IRoot {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public string? VisibilityGroup { get; set; } // Offset: 40, Size: 8, Type: UTFString, Id: 19, Class: 
	public bool Skinned { get; set; } // Offset: 48, Size: 1, Type: Boolean, Id: 19, Class: 
	public List<IRoot?>? Items { get; set; } // Offset: 56, Size: 144, Type: Collection, Id: 17, Class: IList
}
