/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSprite2dBracketRenderer : Tr2SpriteObject {
	public List<IRoot?>? Brackets { get; set; }
	public Tr2AtlasTexture? IconAtlas { get; set; }
}
