/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataFactionChild : IRoot {
	public int GroupIndex { get; set; }
	public bool IsVisible { get; set; }
	public string? Name { get; set; }
}
