/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFData : IRoot {
	public IRoot? Generic { get; set; }
	public List<IRoot?>? Hull { get; set; }
	public List<IRoot?>? Faction { get; set; }
	public List<IRoot?>? Race { get; set; }
	public List<IRoot?>? Material { get; set; }
	public List<IRoot?>? Pattern { get; set; }
	public List<IRoot?>? Layout { get; set; }
}
