/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterVector4 : IEveSocketParameter, IRoot {
	public string? Name { get; set; }
	public Vector4D<float> Value { get; set; }
}
