/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataRace : IRoot {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public IRoot? Booster { get; set; } // Offset: 40, Size: 8, Type: Object, Id: 19, Class: EveSOFDataBooster
	public int HullPrimaryHeatColorType { get; set; } // Offset: 48, Size: 4, Type: Int, Id: 531, Class: 
	public int HullReactorHeatColorType { get; set; } // Offset: 52, Size: 4, Type: Int, Id: 531, Class: 
	public IRoot? Damage { get; set; } // Offset: 56, Size: 8, Type: Object, Id: 19, Class: EveSOFDataRaceDamage
}
