/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullExtensionPlacementDistributionMapGraphicSettings : IEveSOFDataHullExtensionPlacementDistribution, IRoot {
	public string? Name { get; set; }
	public int DisplayFilter { get; set; }
}
