/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSocketParameterColor : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public Vector4 Value { get; set; }
}
