/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataRaceDamage : IRoot {
	public List<IRoot?>? ArmorImpactParameters { get; set; }
	public List<IRoot?>? ArmorImpactTextures { get; set; }
	public List<IRoot?>? ShieldImpactParameters { get; set; }
	public List<IRoot?>? ShieldImpactTextures { get; set; }
}
