/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataFactionPlaneSet : IRoot {
	public int GroupIndex { get; set; }
	public string? Name { get; set; }
	public Vector3 Color { get; set; }
}
