/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullPlaneSetItem : IRoot {
	public Vector3D<float> Position { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Vector4D<float> Color { get; set; }
	public int ColorType { get; set; }
	public float Intensity { get; set; }
	public float Saturation { get; set; }
	public Vector4D<float> Layer1Transform { get; set; }
	public Vector4D<float> Layer2Transform { get; set; }
	public Vector4D<float> Layer1Scroll { get; set; }
	public Vector4D<float> Layer2Scroll { get; set; }
	public int BoneIndex { get; set; }
	public int GroupIndex { get; set; }
	public int MaskMapAtlasIndex { get; set; }
	public float BlinkRate { get; set; }
	public float BlinkPhase { get; set; }
	public int BlinkMode { get; set; }
	public List<IRoot?>? Lights { get; set; }
}
