/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataAreaMaterial : IRoot {
	public string? Material1 { get; set; }
	public string? Material2 { get; set; }
	public string? Material3 { get; set; }
	public string? Material4 { get; set; }
	public int ColorType { get; set; }
}
