/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataPatternLayerProperties : IRoot {
	public int ProjectionTypeU { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 531, Class: 
	public int ProjectionTypeV { get; set; } // Offset: 12, Size: 4, Type: Int, Id: 531, Class: 
	public bool IsTargetMtl1 { get; set; } // Offset: 16, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl2 { get; set; } // Offset: 17, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl3 { get; set; } // Offset: 18, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsTargetMtl4 { get; set; } // Offset: 19, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Primary { get; set; } // Offset: 20, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Glass { get; set; } // Offset: 21, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Sails { get; set; } // Offset: 22, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Reactor { get; set; } // Offset: 23, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Darkhull { get; set; } // Offset: 24, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Rock { get; set; } // Offset: 26, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Monument { get; set; } // Offset: 27, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Ornament { get; set; } // Offset: 28, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool SimplePrimary { get; set; } // Offset: 29, Size: 1, Type: Boolean, Id: 19, Class: 
}
