/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullController : IRoot {
	public string? Name { get; set; }
	public string? Path { get; set; }
	public int BuildFilter { get; set; }
}
