/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullExtensionPlacement : IRoot, IEveSOFDataHullExtensionPlacement {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public string? LocatorSetName { get; set; } // Offset: 40, Size: 32, Type: String, Id: 19, Class: 
	public bool Enabled { get; set; } // Offset: 72, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool IsInstanced { get; set; } // Offset: 73, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool ExtendsShieldEllipsoid { get; set; } // Offset: 74, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool ExtendsBoundingSphere { get; set; } // Offset: 75, Size: 1, Type: Boolean, Id: 19, Class: 
	public Vector3 Offset { get; set; } // Offset: 76, Size: 12, Type: FloatArray, Id: 19, Class: 
	public IRoot? Distribution { get; set; } // Offset: 88, Size: 8, Type: Object, Id: 19, Class: EveSOFDataHullExtensionPlacementDistributionPlacement
	public List<IRoot?>? DistributionConditions { get; set; } // Offset: 96, Size: 144, Type: Collection, Id: 17, Class: IList
	public IRoot? Descriptor { get; set; } // Offset: 240, Size: 8, Type: Object, Id: 19, Class: EveSOFDNADescriptor
}
