/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveStretch2 : IRoot, ITr2Renderable, IEveFiringEffectElement, IInitialize, INotify, ITr2LightOwner {
	public IRoot? Effect { get; set; }
	public IRoot? Start { get; set; }
	public IRoot? Loop { get; set; }
	public IRoot? End { get; set; }
	public IRoot? SourceLight { get; set; }
	public IRoot? DestinationLight { get; set; }
	public IRoot? SourceEmitter { get; set; }
	public IRoot? DestinationEmitter { get; set; }
	public IRoot? SourceObserver { get; set; }
	public IRoot? DestinationObserver { get; set; }
	public string? Name { get; set; }
	public int QuadCount { get; set; }
	public float BoundingRadius { get; set; }
}
