/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataGenericDamage : IRoot {
	public float FlickerPerlinSpeed { get; set; }
	public float FlickerPerlinAlpha { get; set; }
	public float FlickerPerlinBeta { get; set; }
	public int FlickerPerlinN { get; set; }
	public float ArmorParticleRate { get; set; }
	public float ArmorParticleAngle { get; set; }
	public Vector2 ArmorParticleMinMaxSpeed { get; set; }
	public Vector2 ArmorParticleMinMaxLifeTime { get; set; }
	public Vector4 ArmorParticleSizes { get; set; }
	public Vector4 ArmorParticleColor0 { get; set; }
	public Vector4 ArmorParticleColor1 { get; set; }
	public Vector4 ArmorParticleColor2 { get; set; }
	public Vector4 ArmorParticleColor3 { get; set; }
	public int ArmorParticleTextureIndex { get; set; }
	public float ArmorParticleVelocityStretchRotation { get; set; }
	public float ArmorParticleDrag { get; set; }
	public float ArmorParticleTurbulenceAmplitude { get; set; }
	public int ArmorParticleTurbulenceFrequency { get; set; }
	public float ArmorParticleColorMidPoint { get; set; }
	public string? ArmorShader { get; set; }
	public string? ShieldShaderEllipsoid { get; set; }
	public string? ShieldShaderHull { get; set; }
	public string? ShieldGeometryResFilePath { get; set; }
}
