/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSceneStaticParticles : IRoot, IInitialize {
	public float MinSize { get; set; }
	public float MaxSize { get; set; }
	public long MaxParticleCount { get; set; }
	public float ClusterParticleDensity { get; set; }
	public float ClusterParticleDensityAdjust { get; set; }
	public EveTransform? Transform { get; set; }
}
