/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataHullLocator : IRoot {
	public string? Name { get; set; }
	public Matrix4x4 Transform { get; set; }
}
