/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSpotlightSetItem : IRoot {
	public string? Name { get; set; }
	public Matrix4X4<float> Transform { get; set; }
	public Vector3D<float> SpriteScale { get; set; }
	public Vector4D<float> ConeColor { get; set; }
	public Vector4D<float> SpriteColor { get; set; }
	public Vector4D<float> FlareColor { get; set; }
	public int BoneIndex { get; set; }
	public bool BoosterGainInfluence { get; set; }
}
