/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterFloat : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public float Value { get; set; }
}
