/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataFactionSpotlightSet : IRoot {
	public int GroupIndex { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 19, Class: 
	public string? Name { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
	public Vector3 ConeColor { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 SpriteColor { get; set; } // Offset: 64, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 FlareColor { get; set; } // Offset: 80, Size: 16, Type: FloatArray, Id: 19, Class: Color
}
