/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullSoundEmitter : IRoot {
	public float AttenuationScalingFactor { get; set; }
	public string? Name { get; set; }
	[BlackUseNamePool] public string? Prefix { get; set; }
	public Vector3D<float> Position { get; set; }
	public Vector4D<float> Rotation { get; set; }
}
