/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataGenericDecalShader : IRoot {
	public string? Shader { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? DefaultTextures { get; set; }
	public List<IRoot?>? ParentTextures { get; set; }
}
