/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterVector2 : IEveSocketParameter, IRoot {
	public string? Name { get; set; }
	public Vector2D<float> Value { get; set; }
}
