/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSocketParameterInt : IRoot, IEveSocketParameter {
	public string? Name { get; set; }
	public int Value { get; set; }
}
