/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveSOFDataPatternApplicationGroup : IRoot {
	public string? Name { get; set; }
	public IRoot? Layer1Properties { get; set; }
	public IRoot? Layer2Properties { get; set; }
	public List<IRoot?>? Projections { get; set; }
}
