/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSmartLightMesh : EveChildInstanceMeshRenderer, IEveSmartLightGroup, ITr2Renderable, IInitialize, INotify, IEveShadowCaster, IRoot {
	public bool CastShadows { get; set; }
	public List<IRoot?>? AttributeModifiers { get; set; }
	public Vector4D<float> CustomColor { get; set; }
	public int FactionColor { get; set; }
	public bool UseFactionColor { get; set; }
	public string? ShaderParamColorName { get; set; }
}
