/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveSOFDataHullLightSetSpotLight : EveSOFDataHullLightSetItem, IRoot {
	public Vector4D<float> Rotation { get; set; }
	public float InnerAngle { get; set; }
	public float OuterAngle { get; set; }
}
