/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveTurretSet : EveEntity, IInitialize, INotify, ITr2Renderable, IRoot {
	[BlackArray] public ITriTargetable? TargetObject { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public bool DisplayEffects { get; set; }
	public bool IsOnline { get; set; }
	public bool UpdatePitchPose { get; set; }
	public int VisibleCount { get; set; }
	public float EstimatedPixelDiameter { get; set; }
	public int LodLevel { get; set; }
	public string? LocatorName { get; set; }
	public int SlotNumber { get; set; }
	public int SwarmID { get; set; }
	public bool UseDynamicBounds { get; set; }
	public Vector4D<float> BoundingSphere { get; set; }
	public float BottomClipHeight { get; set; }
	[BlackArray] public Tr2Effect? TurretEffect { get; set; }
	public string? GeometryResPath { get; set; }
	[BlackArray] public TriGeometryRes? GeometryResource { get; set; }
	[BlackArray] public EveTurretTarget? Target { get; set; }
	public bool LaserMissBehaviour { get; set; }
	public bool ProjectileMissBehaviour { get; set; }
	public float ImpactSize { get; set; }
	public int ImpactBehaviour { get; set; }
	public float TrackingInfluence { get; set; }
	public float MaxTrackingTime { get; set; }
	public bool UseRandomFiringDelay { get; set; }
	public float RandomFiringDelay { get; set; }
	public int MaxCyclingFirePos { get; set; }
	public int CyclingFireGroupCount { get; set; }
	public int CurrentCyclingFiresPos { get; set; }
	public float SysBoneHeight { get; set; }
	public float SysBonePitchOffset { get; set; }
	public float SysBonePitchFactor { get; set; }
	public float SysBonePitchMin { get; set; }
	public float SysBonePitchMax { get; set; }
	public float SysBonePitch01Offset { get; set; }
	public float SysBonePitch01Factor { get; set; }
	public float SysBonePitch02Offset { get; set; }
	public float SysBonePitch02Factor { get; set; }
	public float SysBonePitch03Offset { get; set; }
	public float SysBonePitch03Factor { get; set; }
	public int State { get; set; }
	public string? FiringEffectResPath { get; set; }
	[BlackArray] public EveTurretFiringFX? FiringEffect { get; set; }
	public bool UseLowLodFiringTransform { get; set; }
	public Vector3D<float> LowLodFiringEffectTranslation { get; set; }
	public Vector3D<float> LowLodFiringEffectScale { get; set; }
	public Vector4D<float> LowLodFiringEffectRotation { get; set; }
	public bool ChooseRandomLocator { get; set; }
	public bool RandomizeExplosionRotation { get; set; }
	[BlackArray] public IEveSpaceObjectChild? AmbientEffect { get; set; }
	[BlackArray] public EveChildInstanceContainer? GeneratedDistributedAmbientEffect { get; set; }
	public bool AmbientEffectEditingMode { get; set; }
	public bool PlayMovementSound { get; set; }
	[BlackArray] public TriObserverLocal? TurretMovementObserver { get; set; }
	[BlackUseNamePool] public string? IdleToTargetingMovementAudioEvent { get; set; }
	[BlackUseNamePool] public string? TargetingToIdleMovementAudioEvent { get; set; }
}
