/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveTacticalOverlayTrackObject : IRoot {
	public ITriVectorFunction? TranslationCurve { get; set; }
	public Vector3D<float> Position { get; set; }
	public float Radius { get; set; }
	public bool IsAggressive { get; set; }
	public bool ShowVelocity { get; set; }
}
