/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveTurretFiringFX : IInitialize, INotify, IListNotify, ITr2ControllerOwner, EveEntity, IRoot {
	public float FiringDuration { get; set; }
	public float FiringPeakTime { get; set; }
	public float FiringDurationOverride { get; set; }
	public bool ScaleEffectTarget { get; set; }
	public float MinRadius { get; set; }
	public float MaxRadius { get; set; }
	public float MinScale { get; set; }
	public float MaxScale { get; set; }
	public bool Display { get; set; }
	public string? Name { get; set; }
	public Vector3D<float> EndPosition { get; set; }
	public bool UseMuzzleTransform { get; set; }
	public bool IsFiring { get; set; }
	public bool IsLoopFiring { get; set; }
	public string? BoneName { get; set; }
	public float FiringDelay1 { get; set; }
	public float FiringDelay2 { get; set; }
	public float FiringDelay3 { get; set; }
	public float FiringDelay4 { get; set; }
	public float FiringDelay5 { get; set; }
	public float FiringDelay6 { get; set; }
	public float FiringDelay7 { get; set; }
	public float FiringDelay8 { get; set; }
	public float FiringDelay9 { get; set; }
	public float FiringDelay10 { get; set; }
	public float FiringDelay11 { get; set; }
	public float FiringDelay12 { get; set; }
	public List<IRoot?>? Stretch { get; set; }
	[BlackArray] public TriCurveSet? StartCurveSet { get; set; }
	[BlackArray] public TriCurveSet? StopCurveSet { get; set; }
	[BlackArray] public TriObserverLocal? SourceObserver { get; set; }
	[BlackArray] public TriObserverLocal? DestinationObserver { get; set; }
}
