/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourVector3MoveBetween : EveVirtualCameraBehaviourVector3Base, INotify {
	public Vector3 Start { get; set; }
	public Vector3 End { get; set; }
	public Tr2CurveScalar? InterpolationCurve { get; set; }
	public bool Proportional { get; set; }
	public bool World { get; set; }
}
