/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourVector3Base : IRoot, INotify {
	public string? Name { get; set; }
	public bool Active { get; set; }
}
