/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourFloatNoise : EveVirtualCameraBehaviourFloatBase, INotify {
	public float PerlineScale { get; set; }
	public int Octaves { get; set; }
	public float Magnitude { get; set; }
	public Tr2CurveScalar? MagnitudeCurve { get; set; }
}
