/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourVector3Orbit : EveVirtualCameraBehaviourVector3Base, INotify {
	public float Start { get; set; }
	public float End { get; set; }
	public float Distance { get; set; }
	public object? DistanceScalarCurve { get; set; }
	public object? OrbitCurve { get; set; }
	public bool Proportional { get; set; }
	public bool World { get; set; }
}
