/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourVector3MoveForward : EveVirtualCameraBehaviourVector3Base, INotify {
	public float Value { get; set; }
	public object? ScaleCurve { get; set; }
	public bool Proportional { get; set; }
}
