/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourVector3Damping : EveVirtualCameraBehaviourVector3Base, INotify, IRoot {
	public float M_dampingRatio { get; set; }
}
