/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourFloatDamping : EveVirtualCameraBehaviourFloatBase, INotify, IRoot {
	public float DampingFactor { get; set; }
}
