/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourVector3Inertia : EveVirtualCameraBehaviourVector3Base, INotify, IRoot {
	public float InertiaFactor { get; set; }
}
