/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourVector3Shake : EveVirtualCameraBehaviourVector3Base, INotify {
	public float PerlineScale { get; set; }
	public int Octaves { get; set; }
	public Vector3 Magnitude { get; set; }
	public Tr2CurveScalar? MagnitudeCurve { get; set; }
	public bool ScaleByView { get; set; }
}
