/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class EveVirtualCameraBehaviourFloatBase : IRoot, INotify {
	public string? Name { get; set; }
	public bool Active { get; set; }
}
