/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourVector3Damping : EveVirtualCameraBehaviourVector3Base, INotify {
	public float M_dampingRatio { get; set; } // Offset: 60, Size: 4, Type: Single, Id: 19, Class: 
}
