/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class EveVirtualCameraBehaviourVector3MoveRight : EveVirtualCameraBehaviourVector3MoveForward, INotify { }
