/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Formation : IRoot, IBehavior {
	public bool Enabled { get; set; } // Offset: 8, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool InFormation { get; set; } // Offset: 72, Size: 1, Type: Boolean, Id: 1, Class: 
	public float MaxFormationVelocityScaler { get; set; } // Offset: 88, Size: 4, Type: Single, Id: 19, Class: 
	public int FramesBetweenUpdates { get; set; } // Offset: 92, Size: 4, Type: Int, Id: 19, Class: 
	public int Stubbornness { get; set; } // Offset: 100, Size: 4, Type: Int, Id: 19, Class: 
	public int BehaviorPriority { get; set; } // Offset: 108, Size: 4, Type: Int, Id: 535, Class: 
	public float BehaviorWeight { get; set; } // Offset: 112, Size: 4, Type: Single, Id: 19, Class: 
}
