/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class InclusionVolume : IRoot, IBehavior {
	public bool Enabled { get; set; }
	public List<IRoot?>? InclusionVolumes { get; set; }
	public int BehaviorPriority { get; set; }
	public int FramesBetweenUpdates { get; set; }
	public float BehaviorWeight { get; set; }
}
