/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class PlayFX : IRoot, IBehavior {
	public bool Enabled { get; set; }
	public float BehaviorWeight { get; set; }
	public int Sec { get; set; }
	public int BehaviorPriority { get; set; }
	public IEveFiringEffectElement? FiringEffect { get; set; }
	public List<IRoot?>? GeneratedFiringEffects { get; set; }
}
