/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class PlayFX : IRoot, IBehavior {
	public bool Enabled { get; set; }
	public float BehaviorWeight { get; set; }
	public int Sec { get; set; }
	public int BehaviorPriority { get; set; }
	public IRoot? FiringEffect { get; set; }
	public List<IRoot?>? GeneratedFiringEffects { get; set; }
}
