/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class ProcessLifetime : IRoot, IBehavior, INotify, IInitialize {
	public float FirstAgentLifetime { get; set; }
	public List<IRoot?>? SplineTunnels { get; set; }
	public float BehaviorWeight { get; set; }
	public float ReturningAge { get; set; }
	public bool RespawnAgentsOnDeath { get; set; }
	public bool Exit { get; set; }
	public bool FirstSpawnAtRandomPlaces { get; set; }
	public int BehaviorPriority { get; set; }
	public float WanderAmount { get; set; }
}
