/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Range : IRoot {
	public float CenterPoint { get; set; }
	public float MinRangePoint { get; set; }
	public float MaxRangePoint { get; set; }
	public bool IsUniform { get; set; }
}
