/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class SeekTarget : IBehavior, IRoot {
	public bool Enabled { get; set; }
	public bool Exit { get; set; }
	public bool Repair { get; set; }
	public int BehaviorPriority { get; set; }
	public float TotalRepairTime { get; set; }
	public float BehaviorWeight { get; set; }
	public float ArrivedRadius { get; set; }
	public float SlowDownRadius { get; set; }
	public float DistFromOrigin { get; set; }
	public float SecondsToTurn { get; set; }
	[BlackArray] public EveSpaceObject2? Target { get; set; }
	public string? LocatorSetName { get; set; }
	public bool FirstSpawnAtRandomPlaces { get; set; }
	[BlackArray] public EveLocatorSets? LocatorSet { get; set; }
}
