/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class SplineTunnelGroup : IRoot, INotify {
	public int TunnelGroupType { get; set; } // Offset: 16, Size: 4, Type: Int, Id: 535, Class: 
	public int BreakPoints { get; set; } // Offset: 20, Size: 4, Type: Int, Id: 23, Class: 
	public List<IRoot?>? CurveSets { get; set; } // Offset: 48, Size: 144, Type: Collection, Id: 21, Class: IList
	public float TunnelWidth { get; set; } // Offset: 256, Size: 4, Type: Single, Id: 23, Class: 
	public float EntrancePullSize { get; set; } // Offset: 260, Size: 4, Type: Single, Id: 23, Class: 
	public float EntrySize { get; set; } // Offset: 264, Size: 4, Type: Single, Id: 23, Class: 
}
