/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionAnimateCurveSet : ITr2ControllerAction, ITr2Updateable, INotify, IRoot {
	public bool IsExpressionValid { get; set; }
	public string? Value { get; set; }
	public TriCurveSet? CurveSet { get; set; }
}
