/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionSpawnParticles : IRoot, ITr2ControllerAction {
	public Tr2DynamicEmitter? Emitter { get; set; }
	public float Rate { get; set; }
}
