/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ActionCallback : IRoot, ITr2ControllerAction {
	public string? CallbackName { get; set; }
}
