/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ActionAnimateValue : IRoot, ITr2ControllerAction, ITr2Updateable, INotify {
	public bool IsBindingValid { get; set; }
	public bool IsExpressionValid { get; set; }
	public string? Path { get; set; }
	public object? Destination { get; set; }
	public string? Attribute { get; set; }
	public string? Value { get; set; }
	public object? Curve { get; set; }
	public bool DelayBinding { get; set; }
}
