/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionSetAttenuationScaling : IRoot, ITr2ControllerAction {
	public float FinalScalingFactor { get; set; }
	public string? Emitter { get; set; }
	public string? ControllerVariable { get; set; }
	public float ScalingFactor { get; set; }
}
