/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionResetClipSphereCenter : IRoot, ITr2ControllerAction {
	public string? LocatorSetName { get; set; }
	public int LocatorIndex { get; set; }
	public int ResetBehavior { get; set; }
}
