/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ActionSetAudioEmitterPrefix : IRoot, ITr2ControllerAction {
	public string? Emitter { get; set; }
	[BlackUseNamePool]public string? Prefix { get; set; }
}
