/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionPlayCurveSet : ITr2ControllerAction, IRoot {
	public string? CurveSetName { get; set; }
	public string? RangeName { get; set; }
	public bool SyncToRange { get; set; }
}
