/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ActionPlayCurveSet : IRoot, ITr2ControllerAction {
	public string? CurveSetName { get; set; }
	public string? RangeName { get; set; }
	public bool SyncToRange { get; set; }
}
