/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionPlaySound : IRoot, ITr2ControllerAction {
	public string? Emitter { get; set; }
	public string? Event { get; set; }
	public string? Target { get; set; }
	public bool BypassPrefix { get; set; }
}
