/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionSetAudioEmitterPrefix : IRoot, ITr2ControllerAction {
	public string? Emitter { get; set; }
	[BlackUseNamePool]public string? Prefix { get; set; }
}
