/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ActionSetValue : ITr2ControllerAction, INotify, IRoot {
	public bool IsExpressionValid { get; set; }
	public bool IsBindingValid { get; set; }
	public string? Path { get; set; }
	public object? Destination { get; set; }
	public string? Attribute { get; set; }
	public string? Value { get; set; }
	public bool DelayBinding { get; set; }
}
