/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ControllerReference : IRoot, IInitialize, INotify, ITr2Controller {
	public IRoot? Controller { get; set; }
	public string? Path { get; set; }
}
