/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2CapsuleShapeAttributeGenerator : IRoot, ITr2AttributeGenerator {
	public string? Name { get; set; }
	public Vector3 PositionStart { get; set; }
	public Vector3 PositionEnd { get; set; }
	public Vector3 RotationStart { get; set; }
	public Vector3 RotationEnd { get; set; }
	public float MinPhi { get; set; }
	public float MaxPhi { get; set; }
	public float MinTheta { get; set; }
	public float MaxTheta { get; set; }
	public float MinRadius { get; set; }
	public float MaxRadius { get; set; }
	public bool ControlVelocity { get; set; }
	public float MinSpeed { get; set; }
	public float MaxSpeed { get; set; }
	public float ParentVelocityFactor { get; set; }
	public bool Valid { get; set; }
}
