/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveCombiner : ITriFunction, ITriVectorFunction, ITriCurveLength, IRoot {
	public string? Name { get; set; }
	public List<IRoot?>? Curves { get; set; }
	public Vector3D<float> CurrentValue { get; set; }
}
