/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2CurveColorMixer : IRoot, ITriColorFunction, ITriFunction, ITriCurveLength {
	public string? Name { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
	public Vector3 ConvertedLinearValue { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 1, Class: Color
	public Vector3 Color1 { get; set; } // Offset: 64, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 Color2 { get; set; } // Offset: 80, Size: 16, Type: FloatArray, Id: 19, Class: Color
	public Vector3 CurrentValue { get; set; } // Offset: 96, Size: 16, Type: FloatArray, Id: 1, Class: Color
	public float LerpValue { get; set; } // Offset: 112, Size: 4, Type: Single, Id: 19, Class: 
	public float Saturation { get; set; } // Offset: 116, Size: 4, Type: Single, Id: 19, Class: 
	public float Brightness { get; set; } // Offset: 120, Size: 4, Type: Single, Id: 19, Class: 
}
