/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveConstant : IRoot, ITriScalarFunction, ITriVectorFunction, ITriQuaternionFunction, ITriColorFunction, ITriFunction {
	public string? Name { get; set; }
	public Vector4 CurrentValue { get; set; }
	public Vector4 Value { get; set; }
}
