/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Controller : IRoot, ITr2Controller, IListNotify {
	public long CallbackCount { get; set; }
	public string? Name { get; set; }
	public List<IRoot?>? StateMachines { get; set; }
	public List<IRoot?>? Variables { get; set; }
	public List<IRoot?>? EventHandlers { get; set; }
	public bool IsPlaying { get; set; }
	public bool IsShared { get; set; }
}
