/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2CapsuleShapeAttributeGenerator : IRoot, ITr2AttributeGenerator {
	public string? Name { get; set; } // Offset: 0, Size: 0, Type: String, Id: 1, Class: 
	public Vector3 PositionStart { get; set; } // Offset: 8, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 PositionEnd { get; set; } // Offset: 20, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 RotationStart { get; set; } // Offset: 32, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Vector3 RotationEnd { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public float MinPhi { get; set; } // Offset: 64, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxPhi { get; set; } // Offset: 68, Size: 4, Type: Single, Id: 19, Class: 
	public float MinTheta { get; set; } // Offset: 72, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxTheta { get; set; } // Offset: 76, Size: 4, Type: Single, Id: 19, Class: 
	public float MinRadius { get; set; } // Offset: 80, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxRadius { get; set; } // Offset: 84, Size: 4, Type: Single, Id: 19, Class: 
	public bool ControlVelocity { get; set; } // Offset: 88, Size: 1, Type: Boolean, Id: 19, Class: 
	public float MinSpeed { get; set; } // Offset: 92, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxSpeed { get; set; } // Offset: 96, Size: 4, Type: Single, Id: 19, Class: 
	public float ParentVelocityFactor { get; set; } // Offset: 100, Size: 4, Type: Single, Id: 19, Class: 
	public bool Valid { get; set; } // Offset: 136, Size: 1, Type: Boolean, Id: 1, Class: 
}
