/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveColorMixer : ITriColorFunction, ITriFunction, ITriCurveLength, IRoot {
	public string? Name { get; set; }
	public Vector4D<float> ConvertedLinearValue { get; set; }
	public Vector4D<float> Color1 { get; set; }
	public Vector4D<float> Color2 { get; set; }
	public Vector4D<float> CurrentValue { get; set; }
	public float LerpValue { get; set; }
	public float Saturation { get; set; }
	public float Brightness { get; set; }
}
