/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveVector3Expression : ITriColorFunction, ITriVectorFunction, ITriFunction, IInitialize, IRoot {
	public string? Name { get; set; }
	public string? ExpressionX { get; set; }
	public string? ExpressionY { get; set; }
	public string? ExpressionZ { get; set; }
	public List<IRoot?>? Inputs { get; set; }
	public Vector3D<float> CurrentValue { get; set; }
	public float Input1 { get; set; }
	public float Input2 { get; set; }
	public float Input3 { get; set; }
	public float Input4 { get; set; }
}
