/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveScalar : ITriScalarFunction, ITriFunction, ITriCurveLength, IRoot {
	[BlackArray] public byte[][]? Keys { get; set; }
	public string? Name { get; set; }
	public float TimeOffset { get; set; }
	public float TimeScale { get; set; }
	public float CurrentValue { get; set; }
	public int ExtrapolationBefore { get; set; }
	public int ExtrapolationAfter { get; set; }
}
