/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CapsuleShapeAttributeGenerator : ITr2AttributeGenerator, IRoot {
	public string? Name { get; set; }
	public Vector3D<float> PositionStart { get; set; }
	public Vector3D<float> PositionEnd { get; set; }
	public Vector4D<float> RotationStart { get; set; }
	public Vector4D<float> RotationEnd { get; set; }
	public float MinPhi { get; set; }
	public float MaxPhi { get; set; }
	public float MinTheta { get; set; }
	public float MaxTheta { get; set; }
	public float MinRadius { get; set; }
	public float MaxRadius { get; set; }
	public bool ControlVelocity { get; set; }
	public float MinSpeed { get; set; }
	public float MaxSpeed { get; set; }
	public float ParentVelocityFactor { get; set; }
	public bool Valid { get; set; }
}
