/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ControllerFloatVariable : IRoot, IInitialize, INotify {
	public string? Name { get; set; }
	public string? EnumValues { get; set; }
	public int VariableType { get; set; }
	public float Value { get; set; }
	public float DefaultValue { get; set; }
}
