/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveEulerRotation : ITriQuaternionFunction, ITriFunction, ITriCurveLength, IRoot {
	public string? Name { get; set; }
	public Tr2CurveScalar? Yaw { get; set; }
	public Tr2CurveScalar? Pitch { get; set; }
	public Tr2CurveScalar? Roll { get; set; }
	public Vector4D<float> CurrentValue { get; set; }
}
