/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2CurveCombiner : IRoot, ITriFunction, ITriVectorFunction, ITriCurveLength {
	public string? Name { get; set; }
	public List<IRoot?>? Curves { get; set; }
	public Vector3 CurrentValue { get; set; }
}
