/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ControllerEventHandler : IListNotify, IRoot {
	public string? Name { get; set; }
	public List<IRoot?>? Actions { get; set; }
}
