/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2CurveLineSet : ITr2Renderable, INotify, ITr2Pickable, IRoot {
	[BlackArray] public Tr2Material? LineEffect { get; set; }
	[BlackArray] public Tr2Material? PickEffect { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Vector3D<float> Translation { get; set; }
	public string? Name { get; set; }
	public bool Display { get; set; }
	public bool Additive { get; set; }
	public float LineWidthFactor { get; set; }
	public float DepthOffset { get; set; }
}
