/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Denoiser : INotify, IRoot {
	public int Radius { get; set; }
	public int StepSize { get; set; }
	public float DepthWeight { get; set; }
	public float NormalWeight { get; set; }
	public float PlaneWeight { get; set; }
	public bool Bypass { get; set; }
}
