/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Denoiser : IRoot, INotify {
	public Tr2RenderTarget? NoiseEstimate { get; set; }
	public Tr2RenderTarget? Intermediate { get; set; }
	public Tr2RenderTarget? Result { get; set; }
	public int Radius { get; set; }
	public int StepSize { get; set; }
	public float DepthWeight { get; set; }
	public float NormalWeight { get; set; }
	public float PlaneWeight { get; set; }
	public bool Bypass { get; set; }
}
