/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2DirectInstanceData : ITr2InstanceData, IRoot {
	public int Count { get; set; }
	public Vector3D<float> AabbMin { get; set; }
	public Vector3D<float> AabbMax { get; set; }
}
