/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Effect : IRoot, Tr2Material, INotify, IInitialize, IListNotify {
	public string? Name { get; set; }
	public string? EffectFilePath { get; set; }
	public string? ActualEffectFilePath { get; set; }
	public IRoot? EffectResource { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public List<IRoot?>? Resources { get; set; }
	[BlackArray]public byte[][]? ConstParameters { get; set; }
	[BlackArray]public byte[][]? SamplerOverrides { get; set; }
	[BlackArray]public byte[][]? Options { get; set; }
}
