/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2FontManager : IRoot {
	public int NumGlyphsInUse { get; set; }
	public int NumGlyphsCached { get; set; }
	public int LoadFlag { get; set; }
	public long TotalGlyphsCachedSize { get; set; }
	public long GlyphCacheBudget { get; set; }
}
