/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ForceSphereVolume : IRoot, ITr2ParticleForce {
	public List<IRoot?>? Forces { get; set; }
	public Vector3 Position { get; set; }
	public float Radius { get; set; }
	public float Exponent { get; set; }
}
