/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2FactionLight : Tr2Light, IEveInheritPropertiesOwner, IInitialize, INotify {
	public Vector4 SelectedColor { get; set; }
	public Vector3 Position { get; set; }
	public float Brightness { get; set; }
	public float NoiseAmplitude { get; set; }
	public float NoiseFrequency { get; set; }
	public int NoiseOctaves { get; set; }
	public float Radius { get; set; }
	public float InnerRadius { get; set; }
	public Vector4 Rotation { get; set; }
	public float OuterAngle { get; set; }
	public float InnerAngle { get; set; }
	public int BoneIndex { get; set; }
	public short Flags { get; set; }
	public int CastsShadows { get; set; }
	public bool IsVolumetric { get; set; }
	public string? Name { get; set; }
	public Tr2LightProfileRes? LightProfile { get; set; }
	[BlackUseNamePool] public string? LightProfilePath { get; set; }
	public float Saturation { get; set; }
	public bool IsSpotlight { get; set; }
	public int FactionColor { get; set; }
}
