/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2GpuUniqueEmitter : Tr2GpuSharedEmitter, IRoot {
	public float AttractorStrength { get; set; }
	public Vector3D<float> AttractorPosition { get; set; }
	public bool ScaledByParent { get; set; }
}
