/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2GpuBuffer : IRoot, INotify, IInitialize, ITr2GpuBuffer {
	public bool IsValid { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public int Count { get; set; } // Offset: 48, Size: 4, Type: Int, Id: 23, Class: 
	public int Format { get; set; } // Offset: 52, Size: 4, Type: Int, Id: 535, Class: 
	public int CreationFlags { get; set; } // Offset: 56, Size: 4, Type: Int, Id: 23, Class: 
}
