/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2GpuParticleSystem : IRoot, IInitialize, INotify {
	public float EmitTime { get; set; }
	public float UpdateTime { get; set; }
	public float SortTime { get; set; }
	public float RenderTime { get; set; }
	public bool HasParticles { get; set; }
	public object? Emit { get; set; }
	public object? Update { get; set; }
	public object? Render { get; set; }
	public object? Clear { get; set; }
	public object? SetDrawParameters { get; set; }
	public object? SetSortParameters { get; set; }
	public object? Sort { get; set; }
	public object? SortStep { get; set; }
	public object? SortInner { get; set; }
	public int MaxParticles { get; set; }
	public bool EnableEmit { get; set; }
	public bool EnableUpdate { get; set; }
	public bool EnableSort { get; set; }
	public bool Display { get; set; }
	public bool UpdateVisibleCount { get; set; }
	public int VisibleCount { get; set; }
}
