/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2GrannyIntersectionResult : IRoot {
	public Vector3D<float> Position { get; set; }
	public Vector3D<float> Normal { get; set; }
	public Vector2D<float> Uv { get; set; }
	public int MeshIndex { get; set; }
	public int AreaIndex { get; set; }
	public int BoneIndex { get; set; }
	public bool HasPosition { get; set; }
	public bool HasNormal { get; set; }
	public bool HasUv { get; set; }
	public bool HasBoneIndex { get; set; }
}
