/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2GpuStructuredBuffer : IRoot, INotify, IInitialize, ITr2GpuBuffer {
	public bool IsValid { get; set; }
	public int Count { get; set; }
	public int Stride { get; set; }
	public int CreationFlags { get; set; }
}
