/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2GpuSharedEmitter : IRoot, IInitialize, INotify, ITr2GenericEmitter {
	public string? Name { get; set; }
	public float Rate { get; set; }
	public float InheritVelocity { get; set; }
	public float EmissionDensity { get; set; }
	public float MaxEmissionDensity { get; set; }
	public float MaxDisplacement { get; set; }
	public Vector3 Position { get; set; }
	public Vector3 Direction { get; set; }
	public float Radius { get; set; }
	public float Angle { get; set; }
	public float MinSpeed { get; set; }
	public float MaxSpeed { get; set; }
	public float InnerAngle { get; set; }
	public float MinLifeTime { get; set; }
	public float MaxLifeTime { get; set; }
	public int TextureIndex { get; set; }
	public float ColorMidpoint { get; set; }
	public Vector4 Color0 { get; set; }
	public Vector4 Color1 { get; set; }
	public Vector4 Color2 { get; set; }
	public Vector4 Color3 { get; set; }
	public Vector3 Sizes { get; set; }
	public float SizeVariance { get; set; }
	public float Drag { get; set; }
	public float TurbulenceAmplitude { get; set; }
	public int TurbulenceFrequency { get; set; }
	public float Gravity { get; set; }
	public float VelocityStretchRotation { get; set; }
	public bool ContinuousEmitter { get; set; }
}
