/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2GStateAnimation : IInitialize, ITr2AnimationUpdater, IRoot {
	public string? ResPath { get; set; }
	public string? GStateResPath { get; set; }
	public string? Model { get; set; }
	public string? ResPath_ { get; set; }
	public string? GStateResPath_ { get; set; }
	public string? Model_ { get; set; }
	public TriGrannyRes? GrannyRes { get; set; }
	public bool DebugRenderSkeleton { get; set; }
	public bool DebugRenderJointNames { get; set; }
	public bool AnimationEnabled { get; set; }
	public IBlueEventListener? EventListener { get; set; }
	public List<IRoot?>? Parameters { get; set; }
}
