/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2GrannyTrack : IRoot, ITriFunction, IInitialize, INotify {
	public bool Cycle { get; set; }
	public float Duration { get; set; }
	public string? Name { get; set; }
	public string? Group { get; set; }
	public string? GrannyResPath { get; set; }
	public IRoot? GrannyRes { get; set; }
}
