/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2HostBitmap : IRoot {
	public bool IsValid { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public int Width { get; set; } // Offset: 16, Size: 4, Type: Int, Id: 1, Class: 
	public int Height { get; set; } // Offset: 20, Size: 4, Type: Int, Id: 1, Class: 
	public int MipCount { get; set; } // Offset: 28, Size: 4, Type: Int, Id: 1, Class: 
	public int ImageType { get; set; } // Offset: 36, Size: 4, Type: Int, Id: 1, Class: 
	public int Format { get; set; } // Offset: 40, Size: 4, Type: Int, Id: 1, Class: 
	public string? Name { get; set; } // Offset: 48, Size: 32, Type: String, Id: 19, Class: 
}
