/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2InstancedMesh : Tr2Mesh {
	public string? InstanceGeometryResPath { get; set; }
	public ITr2InstanceData? InstanceGeometryResource { get; set; }
	public int InstanceMeshIndex { get; set; }
	public int BoundsMethod { get; set; }
	public Vector3 MinBounds { get; set; }
	public Vector3 MaxBounds { get; set; }
	public float MaxInstanceSize { get; set; }
}
