/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2LineGraph : IRoot, ICcpStatisticsAccumulator {
	public string? Name { get; set; }
	public Vector4 Color { get; set; }
}
