/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Matrix4Parameter : ITriEffectParameter, ITriReroutable, IRoot {
	public Matrix4X4<float> Value { get; set; }
	public string? Name { get; set; }
	public bool UsedByCurrentTechnique { get; set; }
	public bool UsedByCurrentEffect { get; set; }
}
