/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MaterialMesh : IRoot {
	[BlackExperimental]public Dictionary<IRoot, IRoot?>? Areas { get; set; }
}
