/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MatrixKey : IRoot {
	public float Time { get; set; }
	public Matrix4x4 Value { get; set; }
}
