/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MatrixKey : IRoot {
	public float Time { get; set; } // Offset: 8, Size: 4, Type: Single, Id: 19, Class: 
	public Matrix4x4 Value { get; set; } // Offset: 12, Size: 64, Type: FloatArray, Id: 19, Class: Matrix
}
