/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MaterialRes : IRoot {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	[BlackExperimental]public Dictionary<IRoot, IRoot?>? Meshes { get; set; } // Offset: 40, Size: 320, Type: Collection, Id: 17, Class: IBlueDict
}
