/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MeshArea : IRoot {
	public object? Effect { get; set; }
	public string? Name { get; set; }
	public int Index { get; set; }
	public int Count { get; set; }
	public bool Display { get; set; }
	public bool Reversed { get; set; }
	public bool UseSHLighting { get; set; }
}
