/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MainWindow : IRoot {
	public int Width { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int Height { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	[BlackUseNamePool]public string? Title { get; set; } // Offset: 0, Size: 0, Type: WString, Id: 3, Class: 
	public bool Active { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public IRoot? MouseCursor { get; set; } // Offset: 0, Size: 0, Type: Object, Id: 3, Class: Tr2MouseCursor
	public long Hwnd { get; set; } // Offset: 0, Size: 0, Type: Long, Id: 1, Class: 
}
