/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2MaterialParameterStore : IRoot, INotify, IInitialize {
	public string? Name { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
	public string? ParentPath { get; set; } // Offset: 48, Size: 32, Type: String, Id: 23, Class: 
	public IRoot? Parent { get; set; } // Offset: 80, Size: 8, Type: Object, Id: 1, Class: Tr2MaterialParameterStore
	[BlackExperimental]public Dictionary<IRoot, IRoot?>? Parameters { get; set; } // Offset: 88, Size: 320, Type: Collection, Id: 17, Class: IBlueDict
}
