/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2MeshArea : IRoot {
	public Tr2Effect? Effect { get; set; }
	public string? Name { get; set; }
	public int Index { get; set; }
	public int Count { get; set; }
	public bool Display { get; set; }
	public bool Reversed { get; set; }
	public bool UseSHLighting { get; set; }
}
