/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2NamedPipeListener : IRoot {
	public string? PipeName { get; set; }
	public int Size { get; set; }
	public int Waiting { get; set; }
}
