/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ObjectFollowCurveKey : ITr2FollowCurveKey, INotify, IInitialize, IRoot {
	public string? Name { get; set; }
	public float Time { get; set; }
	public Vector3D<float> LeftTangent { get; set; }
	public Vector3D<float> RightTangent { get; set; }
	public Vector3D<float> RotatedLeftTangent { get; set; }
	public Vector3D<float> RotatedRightTangent { get; set; }
	public int Interpolation { get; set; }
	public object? Object { get; set; }
	public string? OffsetLocatorName { get; set; }
	public Vector3D<float> Offset { get; set; }
	public int RotationSetting { get; set; }
}
