/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPEffect : IRoot, INotify {
	public bool Display { get; set; }
	public bool Dirty { get; set; }
}
