/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPDesaturateEffect : Tr2PPEffect {
	public float Intensity { get; set; } // Offset: 16, Size: 4, Type: Single, Id: 23, Class: 
}
