/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PlatformInfo : IRoot {
	public string? PlatformName { get; set; }
	public int PlatformID { get; set; }
	public bool IsLowPerformance { get; set; }
}
