/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ParticleSpring : ITr2ParticleForce, IRoot {
	public float SpringConstant { get; set; }
	public Vector3D<float> Position { get; set; }
}
