/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PPTonemappingEffect : Tr2PPEffect {
	public float ShoulderStrength { get; set; }
	public float LinearStrength { get; set; }
	public float LinearAngle { get; set; }
	public float ToeStrength { get; set; }
	public float ToeNumerator { get; set; }
	public float ToeDenominator { get; set; }
	public float WhiteScale { get; set; }
}
