/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPDesaturateEffect : Tr2PPEffect {
	public float Intensity { get; set; }
}
