/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PPTaaEffect : Tr2PPEffect, IRoot {
	public int Quality { get; set; }
	public bool ShowMotionVectors { get; set; }
	public bool ShowEarlyOutMask { get; set; }
	public float EarlyOutThreshold { get; set; }
}
