/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PointLight : Tr2Light, IInitialize, INotify, IRoot {
	public Vector3D<float> Position { get; set; }
	public Vector4D<float> Color { get; set; }
	public float Brightness { get; set; }
	public float NoiseAmplitude { get; set; }
	public float NoiseFrequency { get; set; }
	public int NoiseOctaves { get; set; }
	public float Radius { get; set; }
	public float InnerRadius { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public int BoneIndex { get; set; }
	public short Flags { get; set; }
	public int CastsShadows { get; set; }
	public bool IsVolumetric { get; set; }
	public string? Name { get; set; }
	[BlackArray] public Tr2LightProfileRes? LightProfile { get; set; }
	[BlackUseNamePool] public string? LightProfilePath { get; set; }
}
