/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PPFilmGrainEffect : Tr2PPEffect, IRoot {
	public bool Colored { get; set; }
	public float ColorAmount { get; set; }
	public float GrainSize { get; set; }
	public float Intensity { get; set; }
	public float GrainDensity { get; set; }
	public float GrainContrast { get; set; }
	public float BrightnessModifier { get; set; }
}
