/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PresentParameters : IRoot {
	public int BackBufferWidth { get; set; }
	public int BackBufferHeight { get; set; }
	public bool Windowed { get; set; }
	public bool Software { get; set; }
}
