/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPFogEffect : Tr2PPEffect {
	public Vector4 Color { get; set; }
	public float NebulaInfluence { get; set; }
	public float NebulaBlur { get; set; }
	public float OriginalBrightenOnly { get; set; }
	public float ColorInfluence { get; set; }
	public float TotalAmount { get; set; }
	public float TotalPower { get; set; }
	public float BackgroundOcclusion { get; set; }
	public float Intensity { get; set; }
	public float BrightnessThreshold0 { get; set; }
	public float BrightnessThreshold1 { get; set; }
	public float BrightnessAdjustmentAmount { get; set; }
	public float BlendDistance0 { get; set; }
	public float BlendBias0 { get; set; }
	public float BlendAmount0 { get; set; }
	public float BlendPower0 { get; set; }
	public float BlendDistance1 { get; set; }
	public float BlendBias1 { get; set; }
	public float BlendAmount1 { get; set; }
	public float BlendPower1 { get; set; }
	public float BlendDistance2 { get; set; }
	public float BlendBias2 { get; set; }
	public float BlendAmount2 { get; set; }
	public float BlendPower2 { get; set; }
	public Vector3 AreaSize { get; set; }
	public Vector2 AreaScale { get; set; }
	public Vector3 AreaCenter { get; set; }
}
