/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2PPGodRaysEffect : Tr2PPEffect {
	public Vector4 GodRayColor { get; set; }
	public float Intensity { get; set; }
	public string? NoiseTexturePath { get; set; }
}
