/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PostProcess2 : IRoot {
	public IRoot? SignalLoss { get; set; }
	public IRoot? GodRays { get; set; }
	public IRoot? Bloom { get; set; }
	public IRoot? DynamicExposure { get; set; }
	public IRoot? FidelityFX { get; set; }
	public IRoot? FilmGrain { get; set; }
	public IRoot? Desaturate { get; set; }
	public IRoot? Fade { get; set; }
	public IRoot? Lut { get; set; }
	public IRoot? Vignette { get; set; }
	public IRoot? Fog { get; set; }
	public IRoot? Taa { get; set; }
	public IRoot? DepthOfField { get; set; }
}
