/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ParticleAttractorForce : ITr2ParticleForce, IRoot {
	public float Magnitude { get; set; }
	public Vector3D<float> Position { get; set; }
}
