/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ParticleAttractorForce : IRoot, ITr2ParticleForce {
	public float Magnitude { get; set; } // Offset: 8, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 Position { get; set; } // Offset: 12, Size: 12, Type: FloatArray, Id: 19, Class: 
}
