/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ParticleAttractorForce : IRoot, ITr2ParticleForce {
	public float Magnitude { get; set; }
	public Vector3 Position { get; set; }
}
