/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ParticleTurbulenceForce : IRoot, ITr2ParticleForce {
	public Vector3 Amplitude { get; set; }
	public Vector4 Frequency { get; set; }
	public int NoiseLevel { get; set; }
	public float NoiseRatio { get; set; }
}
