/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPDepthOfFieldEffect : Tr2PPEffect {
	public float FocalDistance { get; set; } // Offset: 16, Size: 4, Type: Single, Id: 23, Class: 
	public float FocalLength { get; set; } // Offset: 20, Size: 4, Type: Single, Id: 23, Class: 
	public float Scale { get; set; } // Offset: 24, Size: 4, Type: Single, Id: 23, Class: 
	public bool ForegroundBlurNeeded { get; set; } // Offset: 28, Size: 1, Type: Boolean, Id: 23, Class: 
	public int Debug { get; set; } // Offset: 32, Size: 4, Type: Int, Id: 515, Class: 
	public float CocScale { get; set; } // Offset: 36, Size: 4, Type: Single, Id: 3, Class: 
	public int BokehShape { get; set; } // Offset: 40, Size: 4, Type: Int, Id: 535, Class: 
	public bool UseTAAFriendlyBokeh { get; set; } // Offset: 44, Size: 1, Type: Boolean, Id: 7, Class: 
}
