/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPLutEffect : Tr2PPEffect {
	public float Influence { get; set; }
	public string? Path { get; set; }
}
