/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ParticleSpring : IRoot, ITr2ParticleForce {
	public float SpringConstant { get; set; }
	public Vector3 Position { get; set; }
}
