/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ParticleVortexForce : IRoot, ITr2ParticleForce {
	public float Magnitude { get; set; }
	public Vector3 Position { get; set; }
	public Vector3 Axis { get; set; }
}
