/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PostProcess2 : IRoot {
	public IRoot? SignalLoss { get; set; } // Offset: 8, Size: 8, Type: Object, Id: 19, Class: Tr2PPSignalLossEffect
	public IRoot? GodRays { get; set; } // Offset: 16, Size: 8, Type: Object, Id: 19, Class: Tr2PPGodRaysEffect
	public IRoot? Bloom { get; set; } // Offset: 24, Size: 8, Type: Object, Id: 19, Class: Tr2PPBloomEffect
	public IRoot? DynamicExposure { get; set; } // Offset: 32, Size: 8, Type: Object, Id: 19, Class: Tr2PPDynamicExposureEffect
	public IRoot? FidelityFX { get; set; } // Offset: 40, Size: 8, Type: Object, Id: 19, Class: Tr2PPFidelityFXEffect
	public IRoot? FilmGrain { get; set; } // Offset: 48, Size: 8, Type: Object, Id: 19, Class: Tr2PPFilmGrainEffect
	public IRoot? Desaturate { get; set; } // Offset: 56, Size: 8, Type: Object, Id: 19, Class: Tr2PPDesaturateEffect
	public IRoot? Fade { get; set; } // Offset: 64, Size: 8, Type: Object, Id: 19, Class: Tr2PPFadeEffect
	public IRoot? Lut { get; set; } // Offset: 72, Size: 8, Type: Object, Id: 19, Class: Tr2PPLutEffect
	public IRoot? Vignette { get; set; } // Offset: 80, Size: 8, Type: Object, Id: 19, Class: Tr2PPVignetteEffect
	public IRoot? Fog { get; set; } // Offset: 88, Size: 8, Type: Object, Id: 19, Class: Tr2PPFogEffect
	public IRoot? Taa { get; set; } // Offset: 96, Size: 8, Type: Object, Id: 19, Class: Tr2PPTaaEffect
	public IRoot? DepthOfField { get; set; } // Offset: 104, Size: 8, Type: Object, Id: 19, Class: Tr2PPDepthOfFieldEffect
}
