/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PostProcess2 : IRoot {
	public object? SignalLoss { get; set; }
	public object? GodRays { get; set; }
	public object? Bloom { get; set; }
	public object? DynamicExposure { get; set; }
	public object? FidelityFX { get; set; }
	public object? FilmGrain { get; set; }
	public object? Desaturate { get; set; }
	public object? Fade { get; set; }
	public object? Lut { get; set; }
	public object? Vignette { get; set; }
	public object? Fog { get; set; }
	public object? Taa { get; set; }
	public object? DepthOfField { get; set; }
}
