/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PPTaaEffect : Tr2PPEffect {
	public int Quality { get; set; }
	public bool ApplyMipBias { get; set; }
	public bool ShowMotionVectors { get; set; }
	public bool ShowEarlyOutMask { get; set; }
	public float EarlyOutThreshold { get; set; }
}
