/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2PrimitiveText : IRoot {
	public string? Text { get; set; }
	public Vector3 Position { get; set; }
	public int Font { get; set; }
	public bool Display { get; set; }
}
