/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2QuaternionLerpCurve : IRoot, ITriFunction, ITriQuaternionFunction, ITriCurveLength {
	public long Start { get; set; }
	public float Length { get; set; }
	public Vector4 Value { get; set; }
	public ITriQuaternionFunction? StartCurve { get; set; }
	public ITriQuaternionFunction? EndCurve { get; set; }
}
