/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2QuadRenderer : IRoot {
	public int InstanceBufferSize { get; set; }
	public int InstanceDataSize { get; set; }
}
