/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RuntimeTextureParameter : IRoot, ITriEffectResourceParameter, INotify {
	public string? Name { get; set; } // Offset: 16, Size: 8, Type: UTFString, Id: 19, Class: 
	public IRoot? Texture { get; set; } // Offset: 24, Size: 8, Type: Object, Id: 23, Class: ITr2TextureProvider
	public int UavMipLevel { get; set; } // Offset: 60, Size: 4, Type: Int, Id: 19, Class: 
}
