/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RandomUniformAttributeGenerator : IRoot, ITr2AttributeGenerator {
	public string? Name { get; set; } // Offset: 0, Size: 0, Type: String, Id: 1, Class: 
	public int Dimension { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int ElementType { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 531, Class: 
	public string? CustomName { get; set; } // Offset: 16, Size: 32, Type: String, Id: 19, Class: 
	public Vector3 MinRange { get; set; } // Offset: 48, Size: 16, Type: FloatArray, Id: 19, Class: 
	public Vector3 MaxRange { get; set; } // Offset: 64, Size: 16, Type: FloatArray, Id: 19, Class: 
	public bool Valid { get; set; } // Offset: 96, Size: 1, Type: Boolean, Id: 1, Class: 
}
