/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RotationTool : Tr2ManipulationTool {
	public float Precision { get; set; }
	public Vector4 Rotation { get; set; }
}
