/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RenderTarget : IRoot, ITr2TextureProvider {
	public string? Name { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int MipCount { get; set; }
	public int MultiSampleType { get; set; }
	public int MultiSampleQuality { get; set; }
	public int Format { get; set; }
	public int Type { get; set; }
	public bool IsValid { get; set; }
	public bool IsReadable { get; set; }
}
