/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RandomDirectionAttributeGenerator : IRoot, ITr2AttributeGenerator {
	public string? Name { get; set; }
	public int Dimension { get; set; }
	public int ElementType { get; set; }
	public string? CustomName { get; set; }
	public bool Valid { get; set; }
}
