/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RuntimeInstanceData : IRoot, ITr2InstanceData, ITr2GenericEmitter, ITr2GpuBuffer {
	public int Count { get; set; }
	public string? Name { get; set; }
	public Vector3 AabbMin { get; set; }
	public Vector3 AabbMax { get; set; }
	public IRoot? ParticleSystem { get; set; }
}
