/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2RenderJobs : IRoot {
	public List<IRoot?>? Recurring { get; set; }
	public List<IRoot?>? Once { get; set; }
	public List<IRoot?>? Chained { get; set; }
	public List<IRoot?>? UpdateRecurring { get; set; }
}
