/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2RotationAdapter : ITriQuaternionFunction, IRoot {
	public ITriQuaternionFunction? Curve { get; set; }
	public Vector4D<float> Value { get; set; }
	public Vector4D<float> CurrentValue { get; set; }
}
