/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2RotationAdapter : IRoot, ITriQuaternionFunction {
	public ITriQuaternionFunction? Curve { get; set; }
	public Vector4 Value { get; set; }
	public Vector4 CurrentValue { get; set; }
}
