/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ReflectionProbe : IRoot, INotify {
	public bool LockPosition { get; set; }
	public Vector3 Position { get; set; }
	public int ReflectionSize { get; set; }
	public Tr2RenderTarget? UnfilteredTexture { get; set; }
	public Tr2RenderTarget? ReflectionTexture { get; set; }
	public ITriTextureRes? CustomSourceTexture { get; set; }
	public bool HdrOutput { get; set; }
	public int RenderFrequency { get; set; }
	public byte CurrentFrame { get; set; }
	public bool HollywoodMode { get; set; }
	public Vector4 BacklightColor { get; set; }
	public float BacklightContrast { get; set; }
}
