/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RuntimeTextureParameter : IRoot, ITriEffectResourceParameter, INotify {
	public string? Name { get; set; }
	public ITr2TextureProvider? Texture { get; set; }
	public int UavMipLevel { get; set; }
}
