/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ReflectionProbe : IRoot, INotify {
	public bool LockPosition { get; set; }
	public Vector3 Position { get; set; }
	public int ReflectionSize { get; set; }
	public object? UnfilteredTexture { get; set; }
	public object? ReflectionTexture { get; set; }
	public object? CustomSourceTexture { get; set; }
	public bool HdrOutput { get; set; }
	public int RenderFrequency { get; set; }
	public byte CurrentFrame { get; set; }
	public bool HollywoodMode { get; set; }
	public Vector4 BacklightColor { get; set; }
	public float BacklightContrast { get; set; }
}
