/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2RenderNodeSprite2dScene : ITr2RenderNode, IRoot {
	public Tr2Sprite2dScene? Scene { get; set; }
	public ITr2RenderNode? Background { get; set; }
}
