/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2RotationAdapter : IRoot, ITriQuaternionFunction {
	public IRoot? Curve { get; set; }
	public Vector3 Value { get; set; }
	public Vector3 CurrentValue { get; set; }
}
