/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Sprite2d : Tr2TexturedSpriteObject, INotify, IRoot {
	public float PickRadius { get; set; }
	public bool UseSizeFromTexture { get; set; }
	public float Saturation { get; set; }
	public float EffectOpacity { get; set; }
}
