/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Sprite2dTexture : IRoot, ITr2Sprite2dTexture, IInitialize, INotify {
	public string? ResPath { get; set; }
	public float SrcX { get; set; }
	public float SrcY { get; set; }
	public float SrcWidth { get; set; }
	public float SrcHeight { get; set; }
	public bool TileX { get; set; }
	public bool TileY { get; set; }
	public int RepeatMode { get; set; }
	public Tr2AtlasTexture? AtlasTexture { get; set; }
	[BlackUseNamePool] public string? Name { get; set; }
	public bool UseTransform { get; set; }
	public Vector2 Translation { get; set; }
	public Vector2 RotationCenter { get; set; }
	public float Rotation { get; set; }
	public Vector2 ScalingCenter { get; set; }
	public float ScalingRotation { get; set; }
	public Vector2 Scale { get; set; }
}
