/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dFrame : Tr2TexturedSpriteObject {
	public int CornerSize { get; set; }
	public float CornerScale { get; set; }
	public int Offset { get; set; }
	public bool FillCenter { get; set; }
}
