/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Sprite2dScene : ITr2Scene, ITr2Updateable, INotify, IRoot {
	public bool UseLinearColorSpace { get; set; }
	public bool GammaCorrectText { get; set; }
	[BlackUseNamePool] public string? Name { get; set; }
	public bool Display { get; set; }
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? Background { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
	public Tr2Effect? Ubershader2d { get; set; }
	public Tr2Effect? Ubershader3d { get; set; }
	public bool DefaultTextureUpdates { get; set; }
	public Vector3D<float> Translation { get; set; }
	public float DisplayX { get; set; }
	public float DisplayY { get; set; }
	public Vector4D<float> Rotation { get; set; }
	public Vector3D<float> Scaling { get; set; }
	public float DepthMin { get; set; }
	public float DepthMax { get; set; }
	public float DisplayWidth { get; set; }
	public float DisplayHeight { get; set; }
	public Vector4D<float> BackgroundColor { get; set; }
	public Vector2D<float> LastPickPos { get; set; }
	public int PickState { get; set; }
	public bool DrawWireFrame { get; set; }
	public bool IsFullscreen { get; set; }
	public bool Is2dRender { get; set; }
	public bool Is2dPick { get; set; }
	public bool ClearBackground { get; set; }
	public bool ClearFinishedCurveSets { get; set; }
	public bool IgnoreClip { get; set; }
	public int CaptureIndexDataCapacity { get; set; }
	public int MaxItemsToRender { get; set; }
	public int MaxDrawCallsToRender { get; set; }
	public int MaxSpriteCount { get; set; }
}
