/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2StateMachine : IRoot, IListNotify, INotify {
	public string? Name { get; set; }
	public List<IRoot?>? States { get; set; }
	public IRoot? StartState { get; set; }
	public IRoot? CurrentState { get; set; }
}
