/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dContainerBase : Tr2SpriteObjectBase, ITr2SpriteObject, IListNotify {
	public float Opacity { get; set; }
	public List<IRoot?>? Children { get; set; }
	public List<IRoot?>? Background { get; set; }
}
