/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dArc : Tr2SpriteObject {
	public IRoot? TexturePrimary { get; set; } // Offset: 200, Size: 8, Type: Object, Id: 7, Class: ITr2Sprite2dTexture
	public IRoot? TextureSecondary { get; set; } // Offset: 208, Size: 8, Type: Object, Id: 7, Class: ITr2Sprite2dTexture
	public float Radius { get; set; } // Offset: 320, Size: 4, Type: Single, Id: 7, Class: 
	public float StartAngle { get; set; } // Offset: 324, Size: 4, Type: Single, Id: 7, Class: 
	public float EndAngle { get; set; } // Offset: 328, Size: 4, Type: Single, Id: 7, Class: 
	public float LineWidth { get; set; } // Offset: 332, Size: 4, Type: Single, Id: 7, Class: 
	public Vector3 LineColor { get; set; } // Offset: 336, Size: 16, Type: FloatArray, Id: 7, Class: Color
	public bool Fill { get; set; } // Offset: 352, Size: 1, Type: Boolean, Id: 7, Class: 
}
