/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2d : Tr2TexturedSpriteObject, INotify {
	public float PickRadius { get; set; }
	public bool UseSizeFromTexture { get; set; }
	public float Saturation { get; set; }
	public float EffectOpacity { get; set; }
}
