/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2StreamingBitmapSaver : IRoot {
	public bool HasStartedBatch { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int Format { get; set; }
	public int CurrentOffset { get; set; }
}
