/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ShLightingManager : IRoot {
	public float SecondaryIntensity { get; set; }
	public float PrimaryIntensity { get; set; }
	public int Quality { get; set; }
	public List<IRoot?>? Lights { get; set; }
}
