/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2SSAO : IRoot, INotify {
	public bool Enabled { get; set; }
	public int Quality { get; set; }
	public bool Downsampled { get; set; }
	public float ZoomLevel { get; set; }
	public float Radius { get; set; }
	public float ShadowMultiplier { get; set; }
	public float ShadowPower { get; set; }
	public float ShadowClamp { get; set; }
	public float Sharpness { get; set; }
	public object? DeinterleavedDepthTarget { get; set; }
	public object? DeinterleavedNormalTarget { get; set; }
	public object? SsaoWorkerTargetA { get; set; }
	public object? SsaoWorkerTargetB { get; set; }
	public object? ImportanceTargetA { get; set; }
	public object? ImportanceTargetB { get; set; }
	public object? OutputTarget { get; set; }
}
