/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dTriangle : IRoot {
	public short Index0 { get; set; }
	public short Index1 { get; set; }
	public short Index2 { get; set; }
}
