/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Sprite2dLineTraceVertex : IRoot {
	public string? Name { get; set; }
	public Vector2 Position { get; set; }
	public Vector4 Color { get; set; }
}
