/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2SkinnedModel : Tr2Model, IInitialize, INotify, IRoot {
	public string? GeometryResPath { get; set; }
	public TriGeometryRes? GeometryRes { get; set; }
	public string? SkeletonName { get; set; }
	public Vector3D<float> SkinScale { get; set; }
}
