/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2StreamingBitmapSaver : IRoot {
	public bool HasStartedBatch { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 1, Class: 
	public int Width { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 1, Class: 
	public int Height { get; set; } // Offset: 12, Size: 4, Type: Int, Id: 1, Class: 
	public int Format { get; set; } // Offset: 16, Size: 4, Type: Int, Id: 1, Class: 
	public int CurrentOffset { get; set; } // Offset: 28, Size: 4, Type: Int, Id: 1, Class: 
}
