/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2ScalarExprKey : IRoot, IInitialize, INotify {
	public float Time { get; set; } // Offset: 16, Size: 4, Type: Single, Id: 23, Class: 
	public float Value { get; set; } // Offset: 20, Size: 4, Type: Single, Id: 23, Class: 
	public int Interpolation { get; set; } // Offset: 24, Size: 4, Type: Int, Id: 531, Class: 
	public float Left { get; set; } // Offset: 28, Size: 4, Type: Single, Id: 23, Class: 
	public float Right { get; set; } // Offset: 32, Size: 4, Type: Single, Id: 23, Class: 
	public string? TimeExpression { get; set; } // Offset: 72, Size: 32, Type: String, Id: 23, Class: 
	public string? ValueExpression { get; set; } // Offset: 136, Size: 32, Type: String, Id: 23, Class: 
	public string? LeftTangentExpression { get; set; } // Offset: 200, Size: 32, Type: String, Id: 23, Class: 
	public string? RightTangentExpression { get; set; } // Offset: 264, Size: 32, Type: String, Id: 23, Class: 
	public float Input1 { get; set; } // Offset: 320, Size: 4, Type: Single, Id: 23, Class: 
	public float Input2 { get; set; } // Offset: 324, Size: 4, Type: Single, Id: 23, Class: 
	public float Input3 { get; set; } // Offset: 328, Size: 4, Type: Single, Id: 23, Class: 
	public float Input4 { get; set; } // Offset: 332, Size: 4, Type: Single, Id: 23, Class: 
	public float RandomConstant { get; set; } // Offset: 336, Size: 4, Type: Single, Id: 1, Class: 
	public float RandomMin { get; set; } // Offset: 340, Size: 4, Type: Single, Id: 23, Class: 
	public float RandomMax { get; set; } // Offset: 344, Size: 4, Type: Single, Id: 23, Class: 
	public float PrevKeyTime { get; set; } // Offset: 348, Size: 4, Type: Single, Id: 1, Class: 
	public float PrevKeyValue { get; set; } // Offset: 352, Size: 4, Type: Single, Id: 1, Class: 
}
