/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dPickingMask : IRoot {
	[BlackUseNamePool]public string? MaskPath { get; set; }
	public object? Mask { get; set; }
	public int Channel { get; set; }
	public float Threshold { get; set; }
	public int LeftEdge { get; set; }
	public int TopEdge { get; set; }
	public int RightEdge { get; set; }
	public int BottomEdge { get; set; }
}
