/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2SpriteObjectBase : IRoot, ITr2SpriteObject, INotify {
	public bool Display { get; set; } // Offset: 0, Size: 0, Type: Boolean, Id: 3, Class: 
	public bool IsDirty { get; set; } // Offset: 16, Size: 1, Type: Boolean, Id: 3, Class: 
	public IRoot? AuxMouseover { get; set; } // Offset: 32, Size: 8, Type: Object, Id: 1, Class: ITr2SpriteObject
	public float DisplayX { get; set; } // Offset: 40, Size: 4, Type: Single, Id: 7, Class: 
	public float DisplayY { get; set; } // Offset: 44, Size: 4, Type: Single, Id: 7, Class: 
	public float DisplayWidth { get; set; } // Offset: 48, Size: 4, Type: Single, Id: 7, Class: 
	public float DisplayHeight { get; set; } // Offset: 52, Size: 4, Type: Single, Id: 7, Class: 
	[BlackUseNamePool]public string? Name { get; set; } // Offset: 56, Size: 32, Type: WString, Id: 3, Class: 
	public int PickState { get; set; } // Offset: 92, Size: 4, Type: Int, Id: 531, Class: 
	public IRoot? PickingMask { get; set; } // Offset: 96, Size: 8, Type: Object, Id: 3, Class: Tr2Sprite2dPickingMask
}
