/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2SyncToAnimation : IRoot, ITr2StateMachineStateFinalizer {
	public string? Mask { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
}
