/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Sprite2dVertex : IRoot {
	public Vector4 Color { get; set; }
	public Vector3 Position { get; set; }
}
