/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2ScalarExprKey : IRoot, IInitialize, INotify {
	public float Time { get; set; }
	public float Value { get; set; }
	public int Interpolation { get; set; }
	public float Left { get; set; }
	public float Right { get; set; }
	public string? TimeExpression { get; set; }
	public string? ValueExpression { get; set; }
	public string? LeftTangentExpression { get; set; }
	public string? RightTangentExpression { get; set; }
	public float Input1 { get; set; }
	public float Input2 { get; set; }
	public float Input3 { get; set; }
	public float Input4 { get; set; }
	public float RandomConstant { get; set; }
	public float RandomMin { get; set; }
	public float RandomMax { get; set; }
	public float PrevKeyTime { get; set; }
	public float PrevKeyValue { get; set; }
}
