/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2Sprite2dLayer : Tr2Sprite2dContainer {
	public ITr2Sprite2dTexture? TextureSecondary { get; set; }
	public Vector4 BackgroundColor { get; set; }
	public Vector4 Color { get; set; }
	public bool ClearBackground { get; set; }
	public int BlendMode { get; set; }
	public int SpriteEffect { get; set; }
}
