/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2SkinnedObject : IRoot, ITr2Renderable, IWorldPosition, IListNotify {
	public IRoot? Translation { get; set; }
	public IRoot? Rotation { get; set; }
	public IRoot? Scaling { get; set; }
	public int CurrentLod { get; set; }
	public IRoot? AnimationUpdater { get; set; }
	public IRoot? WorldTransformUpdater { get; set; }
	public string? Name { get; set; }
	public TriMatrix? Transform { get; set; }
	public IRoot? VisualModel { get; set; }
	public int FrameDelay { get; set; }
	public int SkinningMatrixCount { get; set; }
	public int RenderRigBoneCount { get; set; }
	public bool Display { get; set; }
	public IRoot? HighDetailModel { get; set; }
	public IRoot? LowDetailModel { get; set; }
	public IRoot? MediumDetailModel { get; set; }
	public float EstimatedPixelDiameter { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
	public bool UseDynamicBounds { get; set; }
	public bool UseExplicitBounds { get; set; }
	public Vector3 ExplicitMinBounds { get; set; }
	public Vector3 ExplicitMaxBounds { get; set; }
	public float UpdatePeriod { get; set; }
}
