/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2SwapChain : IRoot {
	public int Width { get; set; }
	public int Height { get; set; }
	public Tr2RenderTarget? BackBuffer { get; set; }
	public Tr2DepthStencil? DepthStencilBuffer { get; set; }
}
