/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturePipelineStepLoad : IRoot, ITr2TexturePipelineStep {
	[BlackUseNamePool]public string? Path { get; set; }
}
