/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2TexturePipelineStepCompress : IRoot, ITr2TexturePipelineStep {
	public int Format { get; set; }
	public float R { get; set; }
	public float G { get; set; }
	public float B { get; set; }
}
