/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TextureReference : IRoot, ITr2TextureProvider {
	public int Width { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int Height { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int Depth { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int Type { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int MipCount { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int Format { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int ArraySize { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
}
