/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturePipelineStepPack : IRoot, ITr2TexturePipelineStep {
	public int Format { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 531, Class: 
	public Tr2TexturePackChannel? R { get; set; } // Offset: 16, Size: 64, Type: Collection, Id: 17, Class: Tr2TexturePackChannel
	public Tr2TexturePackChannel? G { get; set; } // Offset: 80, Size: 64, Type: Collection, Id: 17, Class: Tr2TexturePackChannel
	public Tr2TexturePackChannel? B { get; set; } // Offset: 144, Size: 64, Type: Collection, Id: 17, Class: Tr2TexturePackChannel
	public Tr2TexturePackChannel? A { get; set; } // Offset: 208, Size: 64, Type: Collection, Id: 17, Class: Tr2TexturePackChannel
}
