/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturePipelineStepLimitSize : IRoot, ITr2TexturePipelineStep {
	public int MaxWidth { get; set; }
	public int MaxHeight { get; set; }
}
