/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturedSpriteObject : Tr2SpriteObject {
	public IRoot? TexturePrimary { get; set; }
	public IRoot? TextureSecondary { get; set; }
}
