/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2TextureAtlas : IRoot, ITr2TextureProvider {
	public int MultiSampleType { get; set; }
	public int MultiSampleQuality { get; set; }
	public int TexturesInAtlasCount { get; set; }
	public int TexturesOutsideAtlasCount { get; set; }
	public int Format { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int Margin { get; set; }
	public bool OptimizeOnRemoval { get; set; }
	public bool PaintEmptyAreas { get; set; }
	public int MipCount { get; set; }
}
