/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturePipelineStepPack : IRoot, ITr2TexturePipelineStep {
	public int Format { get; set; }
	public Tr2TexturePackChannel? R { get; set; }
	public Tr2TexturePackChannel? G { get; set; }
	public Tr2TexturePackChannel? B { get; set; }
	public Tr2TexturePackChannel? A { get; set; }
}
