/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2TexturedSpriteObject : Tr2SpriteObject {
	public ITr2Sprite2dTexture? TexturePrimary { get; set; }
	public ITr2Sprite2dTexture? TextureSecondary { get; set; }
}
