/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2TexturePackChannel : IRoot {
	[BlackUseNamePool] public string? Path { get; set; }
	public byte Channel { get; set; }
	public byte Fill { get; set; }
}
