/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TextureReference : IRoot, ITr2TextureProvider {
	public int Width { get; set; }
	public int Height { get; set; }
	public int Depth { get; set; }
	public int Type { get; set; }
	public int MipCount { get; set; }
	public int Format { get; set; }
	public int ArraySize { get; set; }
}
