/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2Transform : IRoot, ITr2Renderable {
	public string? Name { get; set; } // Offset: 8, Size: 32, Type: String, Id: 19, Class: 
	public Vector3 Scaling { get; set; } // Offset: 40, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Vector3 Rotation { get; set; } // Offset: 52, Size: 16, Type: FloatArray, Id: 19, Class: Rotation
	public Vector3 Translation { get; set; } // Offset: 68, Size: 12, Type: FloatArray, Id: 19, Class: 
	public Matrix4x4 LocalTransform { get; set; } // Offset: 80, Size: 64, Type: FloatArray, Id: 1, Class: Matrix
	public Matrix4x4 WorldTransform { get; set; } // Offset: 144, Size: 64, Type: FloatArray, Id: 1, Class: Matrix
	public int Modifier { get; set; } // Offset: 208, Size: 4, Type: Int, Id: 531, Class: 
	public bool UseDistanceBasedScale { get; set; } // Offset: 212, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Display { get; set; } // Offset: 213, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool Update { get; set; } // Offset: 214, Size: 1, Type: Boolean, Id: 19, Class: 
	public float DistanceBasedScaleArg1 { get; set; } // Offset: 216, Size: 4, Type: Single, Id: 19, Class: 
	public float DistanceBasedScaleArg2 { get; set; } // Offset: 220, Size: 4, Type: Single, Id: 19, Class: 
	public IRoot? Mesh { get; set; } // Offset: 224, Size: 8, Type: Object, Id: 19, Class: Tr2MeshBase
	public List<IRoot?>? CurveSets { get; set; } // Offset: 232, Size: 144, Type: Collection, Id: 17, Class: IList
	public float SortValueMultiplier { get; set; } // Offset: 376, Size: 4, Type: Single, Id: 19, Class: 
}
