/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2TexturePipelineStepLimitSize : IRoot, ITr2TexturePipelineStep {
	public int MaxWidth { get; set; } // Offset: 8, Size: 4, Type: Int, Id: 19, Class: 
	public int MaxHeight { get; set; } // Offset: 12, Size: 4, Type: Int, Id: 19, Class: 
}
