/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2TextureAnimationParameter : IRoot, ITriEffectResourceParameter, INotify {
	public string? Name { get; set; }
	public string? Channel { get; set; }
	public Tr2TextureAnimation? Animation { get; set; }
}
