/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class Tr2VectorFunctionModifier : ITriVectorFunction, IRoot {
	public ITriVectorFunction? ClientBall { get; set; }
	public Vector3D<float> OffsetPosition { get; set; }
	public float ScaleModifier { get; set; }
	public bool UseViewSpace { get; set; }
}
