/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2VideoAdapter : IRoot {
	public string? DeviceIdentifier { get; set; }
	public int Index { get; set; }
	public string? Driver { get; set; }
	[BlackUseNamePool]public string? Description { get; set; }
	public string? DeviceName { get; set; }
	public long DriverVersion { get; set; }
	public int VendorID { get; set; }
	public int DeviceID { get; set; }
	public int SubSystemID { get; set; }
	public int Revision { get; set; }
}
