/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Tr2VolumetricsRenderer : IRoot {
	public IRoot? VolumeSlices { get; set; }
	public IRoot? DownsampledDepth { get; set; }
	public IRoot? BlurScratch { get; set; }
	public int Quality { get; set; }
	public float ScaleFactor { get; set; }
	public bool Blur { get; set; }
	public bool CastShadows { get; set; }
	public bool ReceiveShadows { get; set; }
}
