/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriColor : IRoot, ITriColor, IPythonMethods {
	public float R { get; set; }
	public float G { get; set; }
	public float B { get; set; }
	public float A { get; set; }
}
