/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriDevice : IRoot, ITriDevice {
	public bool DisableGeometryLoad { get; set; }
	public bool DisableTextureLoad { get; set; }
	public bool DisableAsyncLoad { get; set; }
	public ITr2Scene? Scene { get; set; }
	public int Width { get; set; }
	public int Height { get; set; }
	public int SwapEffect { get; set; }
	public int BackBufferCount { get; set; }
	public int AdapterWidth { get; set; }
	public int AdapterHeight { get; set; }
	public int AdapterRefreshRate { get; set; }
	public TriViewport? Viewport { get; set; }
	public int TickInterval { get; set; }
	public int DeviceType { get; set; }
	public int Adapter { get; set; }
	public int MultiSampleType { get; set; }
	public int MultiSampleQuality { get; set; }
	public int PresentationInterval { get; set; }
	public float AnimationTime { get; set; }
	public float AnimationTimeScale { get; set; }
	public int MipLevelSkipCount { get; set; }
	public int ThrottlingState { get; set; }
	public bool AllowThrottling { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
}
