/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriEventCurve : IRoot, ITriFunction, IInitialize, ITriCurveLength {
	public string? Name { get; set; }
	public double Time { get; set; }
	public float LocalTime { get; set; }
	[BlackUseNamePool]public string? Value { get; set; }
	public float Length { get; set; }
	public int Extrapolation { get; set; }
	public List<IRoot?>? Keys { get; set; }
	public IRoot? EventListener { get; set; }
}
