/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriFloatArrayParameter : IRoot, ITriEffectParameter, INotify, IInitialize {
	public List<IRoot?>? Value { get; set; }
	public string? Name { get; set; }
	public bool UsedByCurrentTechnique { get; set; }
	public bool UsedByCurrentEffect { get; set; }
}
