/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriFloatArrayParameter : IRoot, ITriEffectParameter, INotify, IInitialize {
	public List<IRoot?>? Value { get; set; }
	public string? Name { get; set; }
	public bool UsedByCurrentTechnique { get; set; }
	public bool UsedByCurrentEffect { get; set; }
}
