/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriFloatArrayParameter : IRoot, ITriEffectParameter, INotify, IInitialize {
	public List<IRoot?>? Value { get; set; } // Offset: 24, Size: 144, Type: Collection, Id: 21, Class: IList
	public string? Name { get; set; } // Offset: 168, Size: 8, Type: UTFString, Id: 23, Class: 
	public bool UsedByCurrentTechnique { get; set; } // Offset: 176, Size: 1, Type: Boolean, Id: 1, Class: 
	public bool UsedByCurrentEffect { get; set; } // Offset: 176, Size: 1, Type: Boolean, Id: 1, Class: 
}
