/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriGeometryRes : BlueAsyncRes, IBlueResource, ICacheable, ITr2InstanceData, ITr2GpuBuffer {
	public int ModelCount { get; set; }
	public int MeshCount { get; set; }
	public int AnimationCount { get; set; }
	public string? Name { get; set; }
	public int ForcedLodIndex { get; set; }
	public bool ForceLod { get; set; }
}
