/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriGrannyRes : BlueAsyncRes, IBlueResource, ICacheable {
	public int ModelCount { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int MeshCount { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
	public int AnimationCount { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
}
