/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriGrannyRes : BlueAsyncRes, IBlueResource, ICacheable {
	public int ModelCount { get; set; }
	public int MeshCount { get; set; }
	public int AnimationCount { get; set; }
}
