/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriLineSet : IRoot {
	public Matrix4x4 Transform { get; set; }
	public bool ZEnable { get; set; }
}
