/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriObserverLocal : IRoot, ITriObserverLocal {
	public bool Mute { get; set; }
	public string? Name { get; set; }
	public Vector3 Front { get; set; }
	public Vector3 Position { get; set; }
	public IBluePlacementObserver? Observer { get; set; }
}
