/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriObserverLocal : ITriObserverLocal, IRoot {
	public bool Mute { get; set; }
	public string? Name { get; set; }
	public Vector3D<float> Front { get; set; }
	public Vector3D<float> Position { get; set; }
	[BlackArray] public IBluePlacementObserver? Observer { get; set; }
}
