/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriQuaternion : ITriQuaternion, IPythonMethods, IRoot {
	public float X { get; set; }
	public float Y { get; set; }
	public float Z { get; set; }
	public float W { get; set; }
}
