/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriRigidOrientation : IRoot, ITriFunction, ITriQuaternionFunction {
	[BlackUseNamePool]public string? Name { get; set; }
	public long Start { get; set; }
	public float I { get; set; }
	public float Drag { get; set; }
	public Vector4 Value { get; set; }
	public List<IRoot?>? States { get; set; }
}
