/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriRect : IRoot, IPythonMethods {
	public int Left { get; set; }
	public int Top { get; set; }
	public int Right { get; set; }
	public int Bottom { get; set; }
}
