/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepPushDepthStencil : TriRenderStep, IRoot {
	public Tr2DepthStencil? DepthStencil { get; set; }
	public bool PushCurrent { get; set; }
}
