/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderPostProcess : TriRenderStep, INotify {
	public IRoot? RenderTarget { get; set; }
	public IRoot? BloomHighPassFilter { get; set; }
	public IRoot? GodrayEffect { get; set; }
	public IRoot? SignalLossEffect { get; set; }
	public IRoot? DynamicExposureCreateHistogramShader { get; set; }
	public IRoot? DynamicExposureMergeHistogramShader { get; set; }
	public IRoot? DynamicExposureMeasureExposureShader { get; set; }
	public IRoot? DepthOfFieldCoCShader { get; set; }
	public IRoot? DepthOfFieldBokehBlurShader { get; set; }
	public IRoot? DepthOfFieldBokehFillShader { get; set; }
	public IRoot? FsrEasuShader { get; set; }
	public IRoot? FsrRCASShader { get; set; }
	public IRoot? FogColorEffect { get; set; }
	public IRoot? FogCompositeEffect { get; set; }
	public IRoot? TaaEffect { get; set; }
	public IRoot? AccumulationBuffer0 { get; set; }
	public IRoot? AccumulationBuffer1 { get; set; }
	public IRoot? TonemappingEffect { get; set; }
	public IRoot? Scene { get; set; }
	public IRoot? RenderInfo { get; set; }
	public int Quality { get; set; }
}
