/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepRenderAtlas : TriRenderStep, IRoot {
	public Tr2TextureAtlas? Atlas { get; set; }
	public Tr2AtlasTexture? Focus { get; set; }
	public Vector2D<float> TlTexCoord { get; set; }
	public Vector2D<float> BrTexCoord { get; set; }
	public bool ShowFree { get; set; }
	public bool ShowUsed { get; set; }
	public Vector4D<float> BorderColour { get; set; }
	public Vector4D<float> FocusColour { get; set; }
	public Vector4D<float> FreeColour { get; set; }
}
