/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepSetView : TriRenderStep {
	public IRoot? View { get; set; }
	public IRoot? Camera { get; set; }
}
