/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderTexture : TriRenderStep {
	public object? Texture { get; set; }
	public object? RenderTarget { get; set; }
	public object? DepthStencil { get; set; }
	public Vector2 TlTexCoord { get; set; }
	public Vector2 BrTexCoord { get; set; }
	public Vector2 TextureSize { get; set; }
	public int FailClearColor { get; set; }
}
