/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderLineGraph : TriRenderStep {
	public List<IRoot?>? LineGraphs { get; set; }
	public float LegendScale { get; set; }
	public float Scale { get; set; }
	public float MaxLegend { get; set; }
	public bool AutoScale { get; set; }
	public bool ShowLegend { get; set; }
}
