/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepSetView : TriRenderStep, IRoot {
	[BlackArray] public TriView? View { get; set; }
	[BlackArray] public EveCamera? Camera { get; set; }
}
