/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderPostProcess : TriRenderStep, INotify {
	public IRoot? RenderTarget { get; set; } // Offset: 0, Size: 0, Type: Object, Id: 3, Class: Tr2RenderTarget
	public IRoot? BloomHighPassFilter { get; set; } // Offset: 144, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? GodrayEffect { get; set; } // Offset: 152, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? SignalLossEffect { get; set; } // Offset: 160, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DynamicExposureCreateHistogramShader { get; set; } // Offset: 208, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DynamicExposureMergeHistogramShader { get; set; } // Offset: 216, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DynamicExposureMeasureExposureShader { get; set; } // Offset: 224, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DepthOfFieldCoCShader { get; set; } // Offset: 232, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DepthOfFieldBokehBlurShader { get; set; } // Offset: 240, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? DepthOfFieldBokehFillShader { get; set; } // Offset: 248, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? FsrEasuShader { get; set; } // Offset: 280, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? FsrRCASShader { get; set; } // Offset: 288, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? FogColorEffect { get; set; } // Offset: 296, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? FogCompositeEffect { get; set; } // Offset: 304, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? TaaEffect { get; set; } // Offset: 320, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? AccumulationBuffer0 { get; set; } // Offset: 336, Size: 8, Type: Object, Id: 3, Class: Tr2RenderTarget
	public IRoot? AccumulationBuffer1 { get; set; } // Offset: 344, Size: 8, Type: Object, Id: 3, Class: Tr2RenderTarget
	public IRoot? TonemappingEffect { get; set; } // Offset: 384, Size: 8, Type: Object, Id: 3, Class: Tr2Effect
	public IRoot? Scene { get; set; } // Offset: 400, Size: 8, Type: Object, Id: 3, Class: EveSpaceScene
	public IRoot? RenderInfo { get; set; } // Offset: 408, Size: 8, Type: Object, Id: 3, Class: Tr2PostProcessRenderInfo
	public int Quality { get; set; } // Offset: 416, Size: 4, Type: Int, Id: 519, Class: 
}
