/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderEffect : TriRenderStep {
	public Tr2Effect? Effect { get; set; }
	public Tr2ShaderBuffer? ShaderBuffer { get; set; }
	public Vector2 TlTexCoord { get; set; }
	public Vector2 BrTexCoord { get; set; }
}
