/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepSetDepthStencil : TriRenderStep {
	public IRoot? DepthStencil { get; set; }
}
