/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepGenerateMipMaps : TriRenderStep {
	public IRoot? RenderTarget { get; set; } // Offset: 136, Size: 8, Type: Object, Id: 19, Class: Tr2RenderTarget
}
