/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepClearUav : TriRenderStep {
	public ITr2GpuBuffer? Buffer { get; set; }
	public bool ClearWithFloat { get; set; }
	public Vector4 FloatValue { get; set; }
	public int BitValue0 { get; set; }
	public int BitValue1 { get; set; }
	public int BitValue2 { get; set; }
	public int BitValue3 { get; set; }
}
