/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepCopyRenderTarget : TriRenderStep, IRoot {
	public Tr2RenderTarget? Destination { get; set; }
	public Tr2RenderTarget? Source { get; set; }
	public TriTextureRes? DestinationTexture { get; set; }
	public TriViewport? SourceViewport { get; set; }
	public TriViewport? DestinationViewport { get; set; }
}
