/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepSetRenderState : TriRenderStep {
	public int State { get; set; }
	public int Value { get; set; }
}
