/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepClear : TriRenderStep, IRoot {
	public Vector4D<float> Color { get; set; }
	public float Depth { get; set; }
	public int Stencil { get; set; }
	public bool IsColorCleared { get; set; }
	public bool IsDepthCleared { get; set; }
	public bool IsStencilCleared { get; set; }
}
