/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderEffect : TriRenderStep {
	public object? Effect { get; set; }
	public object? ShaderBuffer { get; set; }
	public Vector2 TlTexCoord { get; set; }
	public Vector2 BrTexCoord { get; set; }
}
