/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepFilterVisibilityResults : TriRenderStep {
	public int EventFilter { get; set; }
	public int FilterType { get; set; }
	public List<IRoot?>? Objects { get; set; }
	public object? InputResults { get; set; }
	public object? OutputResults { get; set; }
}
