/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderAtlas : TriRenderStep {
	public IRoot? Atlas { get; set; } // Offset: 152, Size: 8, Type: Object, Id: 3, Class: Tr2TextureAtlas
	public IRoot? Focus { get; set; } // Offset: 160, Size: 8, Type: Object, Id: 3, Class: Tr2AtlasTexture
	public Vector3 TlTexCoord { get; set; } // Offset: 168, Size: 8, Type: FloatArray, Id: 3, Class: 
	public Vector3 BrTexCoord { get; set; } // Offset: 176, Size: 8, Type: FloatArray, Id: 3, Class: 
	public bool ShowFree { get; set; } // Offset: 184, Size: 1, Type: Boolean, Id: 3, Class: 
	public bool ShowUsed { get; set; } // Offset: 185, Size: 1, Type: Boolean, Id: 3, Class: 
	public Vector3 BorderColour { get; set; } // Offset: 188, Size: 16, Type: FloatArray, Id: 3, Class: 
	public Vector3 FocusColour { get; set; } // Offset: 204, Size: 16, Type: FloatArray, Id: 3, Class: 
	public Vector3 FreeColour { get; set; } // Offset: 220, Size: 16, Type: FloatArray, Id: 3, Class: 
}
