/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepTestBlocking : TriRenderStep {
	public bool InProgress { get; set; }
}
