/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderPass : TriRenderStep {
	public int PassType { get; set; }
	public ITr2MultiPassScene? Scene { get; set; }
}
