/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepSetViewport : TriRenderStep {
	public object? Viewport { get; set; }
}
