/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepPresentSwapChain : TriRenderStep {
	public IRoot? SwapChain { get; set; }
}
