/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepRenderPass : TriRenderStep, IRoot {
	public int PassType { get; set; }
	public ITr2MultiPassScene? Scene { get; set; }
}
