/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepUpdate : TriRenderStep {
	public ITr2Updateable? Object { get; set; }
}
