/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepRenderLineGraph : TriRenderStep, IRoot {
	public List<IRoot?>? LineGraphs { get; set; }
	public float LegendScale { get; set; }
	public float Scale { get; set; }
	public float MaxLegend { get; set; }
	public bool AutoScale { get; set; }
	public bool ShowLegend { get; set; }
}
