/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepSetProjection : TriRenderStep {
	public object? Projection { get; set; }
}
