/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderLineGraph : TriRenderStep {
	public List<IRoot?>? LineGraphs { get; set; } // Offset: 136, Size: 144, Type: Collection, Id: 1, Class: IList
	public float LegendScale { get; set; } // Offset: 280, Size: 4, Type: Single, Id: 19, Class: 
	public float Scale { get; set; } // Offset: 284, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxLegend { get; set; } // Offset: 288, Size: 4, Type: Single, Id: 19, Class: 
	public bool AutoScale { get; set; } // Offset: 292, Size: 1, Type: Boolean, Id: 19, Class: 
	public bool ShowLegend { get; set; } // Offset: 293, Size: 1, Type: Boolean, Id: 19, Class: 
}
