/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepGenerateMipMaps : TriRenderStep {
	public IRoot? RenderTarget { get; set; }
}
