/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriStepRenderPostProcess : TriRenderStep, INotify {
	public object? RenderTarget { get; set; }
	public object? BloomHighPassFilter { get; set; }
	public object? GodrayEffect { get; set; }
	public object? SignalLossEffect { get; set; }
	public object? DynamicExposureCreateHistogramShader { get; set; }
	public object? DynamicExposureMergeHistogramShader { get; set; }
	public object? DynamicExposureMeasureExposureShader { get; set; }
	public object? DepthOfFieldCoCShader { get; set; }
	public object? DepthOfFieldBokehBlurShader { get; set; }
	public object? DepthOfFieldBokehFillShader { get; set; }
	public object? FsrEasuShader { get; set; }
	public object? FsrRCASShader { get; set; }
	public object? FogColorEffect { get; set; }
	public object? FogCompositeEffect { get; set; }
	public object? TaaEffect { get; set; }
	public object? AccumulationBuffer0 { get; set; }
	public object? AccumulationBuffer1 { get; set; }
	public object? TonemappingEffect { get; set; }
	public object? Scene { get; set; }
	public object? RenderInfo { get; set; }
	public int Quality { get; set; }
}
