/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriStepPushRenderTarget : TriRenderStep, IRoot {
	[BlackArray] public Tr2RenderTarget? RenderTarget { get; set; }
	public int Slot { get; set; }
}
