/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriVector : ITriVector, IPythonMethods, IPythonNumeric, IRoot {
	public float X { get; set; }
	public float Y { get; set; }
	public float Z { get; set; }
}
