/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriVectorSequencer : IRoot, ITriFunction, ITriVectorFunction {
	[BlackUseNamePool]public string? Name { get; set; } // Offset: 8, Size: 32, Type: WString, Id: 19, Class: 
	public long Start { get; set; } // Offset: 40, Size: 8, Type: Long, Id: 19, Class: 
	public Vector3 Value { get; set; } // Offset: 48, Size: 12, Type: FloatArray, Id: 19, Class: 
	public int Operator { get; set; } // Offset: 60, Size: 4, Type: Int, Id: 531, Class: 
	public List<IRoot?>? Functions { get; set; } // Offset: 64, Size: 144, Type: Collection, Id: 17, Class: IList
}
