/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriVector : IRoot, ITriVector, IPythonMethods, IPythonNumeric {
	public float X { get; set; }
	public float Y { get; set; }
	public float Z { get; set; }
}
