/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TriVariableParameter : IRoot, ITriEffectParameter, INotify, IInitialize {
	public int VariableType { get; set; }
	public string? Name { get; set; }
	public string? VariableName { get; set; }
	public bool UsedByCurrentTechnique { get; set; }
	public bool UsedByCurrentEffect { get; set; }
}
