/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TriValueBinding : ITr2ValueBinding, INotify, IRoot {
	public bool IsValid { get; set; }
	public string? Name { get; set; }
	public object? SourceObject { get; set; }
	public object? DestinationObject { get; set; }
	public string? SourceAttribute { get; set; }
	public string? DestinationAttribute { get; set; }
	public bool IsWeak { get; set; }
	public bool IsEnabled { get; set; }
	public float Scale { get; set; }
	public Vector4D<float> Offset { get; set; }
}
