/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class WodBakingScene : ITr2Scene, IRoot {
	public Tr2SkinnedObject? Avatar { get; set; }
	public int VisualizeMethod { get; set; }
}
