/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class WodPlaceableRes : IRoot {
	public Tr2Model? VisualModel { get; set; }
	public float NearFadeDistance { get; set; }
	public float FarFadeDistance { get; set; }
	public bool IsShadowCaster { get; set; }
	public List<IRoot?>? CurveSets { get; set; }
}
