/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class AudEmitter : AudGameObjResource, IBlueEventListener, IBluePlacementObserver, ITr2AudEmitter {
	public bool NormalizeAttenuationScaling { get; set; } // Offset: 472, Size: 1, Type: Boolean, Id: 19, Class: 
	public float MinNormalizedValue { get; set; } // Offset: 476, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxNormalizedValue { get; set; } // Offset: 480, Size: 4, Type: Single, Id: 19, Class: 
	public float MinNormalizedScalingFactor { get; set; } // Offset: 484, Size: 4, Type: Single, Id: 19, Class: 
	public float MaxNormalizedScalingFactor { get; set; } // Offset: 488, Size: 4, Type: Single, Id: 19, Class: 
	public Vector3 DebugPosition { get; set; } // Offset: 492, Size: 12, Type: FloatArray, Id: 1, Class: 
	public Vector3 DebugFront { get; set; } // Offset: 504, Size: 12, Type: FloatArray, Id: 1, Class: 
}
