/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class AudEventCurve : IRoot, ITriFunction, IInitialize, ITriCurveLength {
	public string? Name { get; set; } // Offset: 24, Size: 32, Type: String, Id: 19, Class: 
	public double Time { get; set; } // Offset: 88, Size: 8, Type: Double, Id: 1, Class: 
	public float LocalTime { get; set; } // Offset: 96, Size: 4, Type: Single, Id: 1, Class: 
	[BlackUseNamePool]public string? Value { get; set; } // Offset: 104, Size: 32, Type: WString, Id: 19, Class: 
	public float Length { get; set; } // Offset: 136, Size: 4, Type: Single, Id: 1, Class: 
	public int Extrapolation { get; set; } // Offset: 144, Size: 4, Type: Int, Id: 531, Class: 
	public List<IRoot?>? Keys { get; set; } // Offset: 152, Size: 144, Type: Collection, Id: 24, Class: IList
	public IRoot? AudioEmitter { get; set; } // Offset: 304, Size: 8, Type: Object, Id: 1, Class: AudEmitter
	public IRoot? SourceTriObserver { get; set; } // Offset: 312, Size: 8, Type: Object, Id: 19, Class: ITriObserverLocal
}
