/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class AudEmitter : AudGameObjResource, IBlueEventListener, IBluePlacementObserver, ITr2AudEmitter {
	public bool NormalizeAttenuationScaling { get; set; }
	public float MinNormalizedValue { get; set; }
	public float MaxNormalizedValue { get; set; }
	public float MinNormalizedScalingFactor { get; set; }
	public float MaxNormalizedScalingFactor { get; set; }
	public Vector3 DebugPosition { get; set; }
	public Vector3 DebugFront { get; set; }
}
