/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class AudGameObjResource : IInitialize, IListNotify, INotify, IRoot {
	public float MaxAttenuationRadius { get; set; }
	public long ID { get; set; }
	public string? Name { get; set; }
	[BlackUseNamePool] public string? EventPrefix { get; set; }
	[BlackUseNamePool] public string? EventName { get; set; }
	public List<IRoot?>? Parameters { get; set; }
	public bool IsVisible { get; set; }
	public bool ListenerInRange { get; set; }
	public bool IsUsed { get; set; }
	public bool Playing2DSound { get; set; }
	public bool PlayingVitalSound { get; set; }
	public bool ForceCullingState { get; set; }
	public float DistanceFromListener { get; set; }
	public float AdditionalCullingWeight { get; set; }
	public float CumulativeWeight { get; set; }
	public float ScalingFactor { get; set; }
}
