/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class AudParameter : IRoot, INotify {
	[BlackUseNamePool]public string? Name { get; set; } // Offset: 16, Size: 32, Type: WString, Id: 3, Class: 
	public float Value { get; set; } // Offset: 48, Size: 4, Type: Single, Id: 7, Class: 
}
