/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class StretchAudio : IInitialize, ITr2DebugRenderable, IStretchAudio, IRoot {
	[BlackUseNamePool] public string? OutburstEvent { get; set; }
	[BlackUseNamePool] public string? ImpactEvent { get; set; }
	[BlackUseNamePool] public string? StretchEvent { get; set; }
	public AudEmitter? SourceEmitter { get; set; }
	public AudEmitter? DestinationEmitter { get; set; }
	public AudEmitter? StretchEmitter { get; set; }
}
