/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlackWriter : IRoot {
	public int CurrentVersion { get; set; } // Offset: 0, Size: 0, Type: Int, Id: 1, Class: 
}
