/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueSysInfoTaskTimes : IRoot {
	public double UserTime { get; set; }
	public double SystemTime { get; set; }
}
