/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BluePyOS : IRoot, IBluePyOS {
	public List<IRoot?>? CpuUsage { get; set; } // Offset: 176, Size: 144, Type: Collection, Id: 1, Class: IList
	public bool MarkupZonesInPython { get; set; } // Offset: 320, Size: 1, Type: Boolean, Id: 3, Class: 
	public int TimesliceWarning { get; set; } // Offset: 324, Size: 4, Type: Int, Id: 3, Class: 
	public int BeNiceSlice { get; set; } // Offset: 328, Size: 4, Type: Int, Id: 3, Class: 
	public int PerformanceUpdateFrequency { get; set; } // Offset: 332, Size: 4, Type: Int, Id: 3, Class: 
	public TaskletTimer? TaskletTimer { get; set; } // Offset: 344, Size: 608, Type: Collection, Id: 1, Class: TaskletTimer
	public int Softspace { get; set; } // Offset: 980, Size: 4, Type: Int, Id: 3, Class: 
	public bool Packaged { get; set; } // Offset: 984, Size: 1, Type: Boolean, Id: 1, Class: 
	public bool InterpreterMode { get; set; } // Offset: 985, Size: 1, Type: Boolean, Id: 1, Class: 
}
