/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class BluePaths : IRoot, IBluePaths {
	[BlackUseNamePool]public string? InitialWorkingDirectory { get; set; }
	public bool CacheFileExistance { get; set; }
}
