/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueLogInMemory : IRoot {
	public bool IsActive { get; set; }
	public int Capacity { get; set; }
	public int Threshold { get; set; }
	public bool SaveOnQuit { get; set; }
}
