/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueAsyncRes : IRoot, IBlueResource {
	public bool IsGood { get; set; }
	public bool IsPrepared { get; set; }
	public bool IsLoading { get; set; }
	[BlackUseNamePool]public string? Path { get; set; }
	[BlackUseNamePool]public string? Ext { get; set; }
}
