/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueNetworkStream : IRoot, IBlueStream {
	public long Size { get; set; } // Offset: 0, Size: 0, Type: Long, Id: 1, Class: 
}
