/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueSysInfoOs : IRoot {
	public int Platform { get; set; }
	public int MajorVersion { get; set; }
	public int MinorVersion { get; set; }
	public int BuildNumber { get; set; }
	public string? Patch { get; set; }
	public int Suite { get; set; }
}
