/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueCpuUsage : IRoot {
	public long Timestamp { get; set; }
	public long UserThreadCpuUsage { get; set; }
	public long UserProcessCpuUsage { get; set; }
	public long KernelThreadCpuUsage { get; set; }
	public long KernelProcessCpuUsage { get; set; }
	public long VirtualMemory { get; set; }
	public long PythonMemoryUsage { get; set; }
	public long WorkingSetSize { get; set; }
	public long PageFaultCount { get; set; }
	public double Fps { get; set; }
	public long TaskletsProcessed { get; set; }
	public long TaskletsYielding { get; set; }
	public long TaskletsSleeping { get; set; }
	public float TaskletsSchedulerDuration { get; set; }
	public long TaskletsQueued { get; set; }
}
