/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueObjectProxy : IRoot, IBlueObjectProxy {
	public object? Object { get; set; }
	public bool Temporary { get; set; }
	public bool IsResident { get; set; }
	public object? Builder { get; set; }
	public int ObjectMarker { get; set; }
}
