/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class BlueResMan : IRoot, IBlueResMan {
	public bool LoadObjectCacheEnabled { get; set; }
	public MotherLode? LoadObjectCache { get; set; }
	public float LoadObjectTimeSlice { get; set; }
	public long BackgroundLoadMemoryBudget { get; set; }
	public long BackgroundLoadMemoryInUse { get; set; }
	public int PendingLoads { get; set; }
	public int PendingPrepares { get; set; }
	public int PreparesHandledLastTick { get; set; }
	public int PreparesHandledPerTickMax { get; set; }
	public int PreparesHandledTotal { get; set; }
	public int MaxAllowedInPrepareQueue { get; set; }
	public float LoadQueueTimeAverage { get; set; }
	public float LoadQueueTimeMax { get; set; }
	public float PrepareQueueTimeAverage { get; set; }
	public float PrepareQueueTimeMax { get; set; }
	public float MainThreadTimeSlice { get; set; }
	public float MainThreadMaxTime { get; set; }
}
