/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class MemStream : IRoot, IBlueMemStream, IBlueStream, ICacheable {
	public long Size { get; set; } // Offset: 32, Size: 8, Type: Long, Id: 1, Class: 
	public long Pos { get; set; } // Offset: 48, Size: 8, Type: Long, Id: 1, Class: 
}
