/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class MemStream : IBlueMemStream, IBlueStream, ICacheable, IRoot {
	public long Size { get; set; }
	public long Pos { get; set; }
}
