/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class MotherLode : IRoot, IMotherLode {
	public long MaxMemUsage { get; set; }
	public long MemUsage { get; set; }
	public bool Verbose { get; set; }
}
