/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class TaskletTimer : ITaskletTimer, INotify, IRoot {
	public int TimesliceWarning { get; set; }
	public bool Active { get; set; }
	public bool TelemetryOn { get; set; }
}
