/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class TaskletTimer : IRoot, ITaskletTimer, INotify {
	public int TimesliceWarning { get; set; } // Offset: 16, Size: 4, Type: Int, Id: 3, Class: 
	public bool Active { get; set; } // Offset: 544, Size: 1, Type: Boolean, Id: 7, Class: 
	public bool TelemetryOn { get; set; } // Offset: 545, Size: 1, Type: Boolean, Id: 3, Class: 
}
