/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class YamlReader : IRoot, IRootReader, IBlueObjectBuilder, ICacheable {
	public bool IsStrict { get; set; }
	public bool DoInitialize { get; set; }
}
