using System.Diagnostics;
using System.Text;
using System.Text.Json;
using Jackdaw.Blue;
using Serilog;

namespace Jackdaw.Codegen.Black;

internal class Program {
	private static readonly string[] IgnoredTypes = ["IWeakObject", "IRoot", "_ClassDef", "object", "IBlueStructureList", "IList"];

	// ReSharper disable once UnusedMember.Local
	private static string FormatComment(string comment, string indent) {
		if (string.IsNullOrEmpty(comment)) {
			return string.Empty;
		}

		var lines = comment.Split('\n');
		var builder = new StringBuilder();
		builder.Append(indent);
		builder.AppendLine("/// <summary>");
		foreach (var line in lines) {
			builder.Append(indent);
			builder.Append("/// ");
			builder.AppendLine(line);
		}

		builder.Append(indent);
		builder.Append("/// </summary>");

		return builder.ToString();
	}

	private static string FixName(string fieldName) {
		var parts = fieldName.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
		var str = new StringBuilder();

		foreach (var part in parts) {
			str.Append(char.ToUpper(part[0]));
			str.Append(part[1..]);
		}

		return str.ToString();
	}

	private static void Main(string[] args) {
		if (args.Length < 2) {
			Console.WriteLine("Usage: Jackdaw.Codegen.Black <path/to/types.json> <path/to/output>");
			return;
		}

		Log.Logger = new LoggerConfiguration().MinimumLevel.Verbose().WriteTo.Console().CreateLogger();

		var types = JsonSerializer.Deserialize<List<BlueClass>>(File.ReadAllText(args[0]))!;
		var output = args[1];

		var buildInterfaces = new HashSet<string> {
			"IRoot",
		};
		var realClasses = new HashSet<string>();
		var typeLists = new Dictionary<string, (List<string> Interfaces, List<string> Fields)>();

		foreach (var type in types) {
			var interfaces = type.Interfaces.Select(x => x.Name).ToList();
			var parent = type.Id == "IRoot" ? "" : "IRoot";
			if (!string.IsNullOrEmpty(type.Parent)) {
				parent = type.Parent.Split('.', StringSplitOptions.TrimEntries)[^1];
			} else if (interfaces.Contains("EveChildContainer")) {
				parent = "EveChildContainer";
			} else if (interfaces.Contains("Tr2AudioStretchBase")) {
				parent = "Tr2AudioStretchBase";
			} else if (interfaces.Contains("EveSOFDataHullLightSetItem")) {
				parent = "EveSOFDataHullLightSetItem";
			} else {
				parent = interfaces.FirstOrDefault(x => x[0] != 'I', parent);
			}

			var interfaceList = interfaces.Where(x => x != parent && x != "IRoot").ToList();
			buildInterfaces.UnionWith(interfaceList);

			interfaceList.Insert(0, parent);
			typeLists[type.Id] = (interfaceList, type.Fields.Where(x => x.Type is not (BlueTypeId.ScriptCallback or BlueTypeId.PyObjectPtr or BlueTypeId.IRootWeakRef)).Select(x => x.Name).ToList());
		}

		var totalNames = new HashSet<string>();
		totalNames.UnionWith(typeLists.Keys);
		totalNames.UnionWith(buildInterfaces);

		foreach (var type in types) {
			type.Description = type.Description?.Trim();

			var group = "class";
			var name = type.Id;
			if (IgnoredTypes.Contains(name)) {
				continue;
			}

			var ns = "Blue";
			if (type.ClassId.Contains('.', StringComparison.Ordinal)) {
				var parts = type.ClassId.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
				if (parts.Length != 2) {
					Debugger.Break();
				}

				ns = parts[0].Trim('_');
				ns = ns switch {
					     "d3dinfo" => "D3DInfo",
					     "evelocalization" => "EveLocalization",
					     "eveplanetresources" => "EvePlanetResources",
					     "pyfsd" => "FSD",
					     "videoplayer" => "VideoPlayer",
					     _ => char.ToUpper(ns[0]) + ns[1..],
				     };
			}

			var nsOutput = ns.Length == 0 ? output : Path.Combine(output, ns);
			Directory.CreateDirectory(nsOutput);

			realClasses.Add(name);

			if ((type.Fields.Count == 0 && string.IsNullOrEmpty(type.Parent) && name[0] == 'I') || name == "EveEntity") {
				group = "interface";
			}

			var interfaces = typeLists[name].Interfaces;
			var interfaceListString = $": {string.Join(", ", interfaces.Concat(["IRoot"]).Distinct().Where(x => x != name))} ";
			Log.Information("Generating {Type} {InterfaceList}", name, interfaceListString);

			using var writer = new StreamWriter(Path.Combine(nsOutput, $"{name}.cs"));
			writer.WriteLine("/// <auto-generated/>\n#nullable enable\n\nnamespace Jackdaw.Black;\n");
			writer.Write($"public {group} {name} {interfaceListString}{{");

			var inheritedFields = new HashSet<string>();
			foreach (var @interface in interfaces.Distinct().Where(x => x != name)) {
				FindAllFields(typeLists, @interface, inheritedFields, []);
			}

			var fields = type.Fields.Where(x => x.Type is not (BlueTypeId.ScriptCallback or BlueTypeId.PyObjectPtr or BlueTypeId.IRootWeakRef) && !inheritedFields.Contains(x.Name)).ToList();

			if (fields.Count == 0) {
				writer.WriteLine(" }");
				continue;
			}

			writer.WriteLine();

			foreach (var field in fields.OrderByDescending(x => x.Offset).DistinctBy(x => x.Name).OrderBy(x => x.Offset)) {
				field.Description = field.Description?.Trim();

				var fieldName = FixName(field.Name);

				var attribute = string.Empty;
				var fieldType = "object?";

				// ReSharper disable once SwitchStatementMissingSomeEnumCasesNoDefault
				switch (field.Type) {
					case BlueTypeId.Int:
						fieldType = "int";
						break;
					case BlueTypeId.UnsignedInt:
						fieldType = "uint";
						break;
					case BlueTypeId.Single:
						fieldType = "float";
						break;
					case BlueTypeId.Double:
						fieldType = "double";
						break;
					case BlueTypeId.Boolean:
						fieldType = "bool";
						break;
					case BlueTypeId.Long:
						fieldType = "long";
						break;
					case BlueTypeId.UnsignedLong:
						fieldType = "ulong";
						break;
					case BlueTypeId.FloatArray:
						fieldType = field.Size switch {
							0 when field.ClassType == "Matrix" => "Matrix4X4<float>",
				            0 when field.ClassType == "Color" => "Vector4D<float>",
							0 when field.ClassType == "Rotation" => "Quaternion<float>",
							0 when field.ClassType == "Vector2" => "Vector2D<float>",
							0 when field.ClassType == "Vector3" => "Vector3D<float>",
							0 when field.ClassType == "Vector4" => "Vector4D<float>",
				            0 when string.IsNullOrEmpty(field.ClassType) => "Vector3",
							0 when !string.IsNullOrEmpty(field.ClassType) => field.ClassType,
							4 => "float",
				            8 => "Vector2D<float>",
				            12 => "Vector3D<float>",
				            16 => "Vector4D<float>",
				            24 => "Matrix3X2<float>",
				            36 => "Matrix3X3<float>",
				            64 => "Matrix4X4<float>",
				            _ => null,
						};
						if (fieldType == null) {
							fieldType = "float[]?";
							attribute = "BlackArray(4)";
						}
						break;
					case BlueTypeId.DoubleArray:
						fieldType = field.Size switch {
							0 when field.ClassType == "Vector2d" => "Vector2D<double>",
							0 when field.ClassType == "Vector3d" => "Vector3D<double>",
							0 when field.ClassType == "Vector4d" => "Vector4D<double>",
							0 when string.IsNullOrEmpty(field.ClassType) => "Vector3D<double>",
							0 when !string.IsNullOrEmpty(field.ClassType) => field.ClassType,
							8 => "double",
							16 => "Vector2D<double>",
							24 => "Vector3D<double>",
							32 => "Vector4D<double>",
							48 => "Matrix3X2<double>",
							72 => "Matrix3X3<double>",
							128 => "Matrix4X4<double>",
							_ => null,
						};
						if (fieldType == null) {
							fieldType = "double[]?";
							attribute = "BlackArray(8)";
						}
						break;
					case BlueTypeId.IntArray:
						fieldType = field.Size switch {
							0 when field.ClassType == "Vector3i" => "Vector3D<int>",
							0 when !string.IsNullOrEmpty(field.ClassType) => field.ClassType,
							4 => "int",
							8 => "Vector2D<int>",
							12 => "Vector3D<int>",
							16 => "Vector4D<int>",
							24 => "Matrix3X2<int>",
							36 => "Matrix3X3<int>",
							64 => "Matrix4X4<int>",
							_ => null,
						};
						if (fieldType == null) {
							fieldType = "int[]?";
							attribute = "BlackArray(4)";
						}
						break;
					case BlueTypeId.StdString:
					case BlueTypeId.SharedString:
					case BlueTypeId.StringPtr:
						fieldType = "string?";
						break;
					case BlueTypeId.CharArray:
						fieldType = "string?";
						attribute = "BlackArray(1)";
						break;
					case BlueTypeId.StdWideString:
					case BlueTypeId.SharedWideString:
					case BlueTypeId.WideString:
					case BlueTypeId.WideStringPtr:
						fieldType = "string?";
						attribute = "BlackUseNamePool";
						break;
					case BlueTypeId.BinaryBlock:
						fieldType = "byte[]?";
						attribute = "BlackArray(1)";
						break;
					case BlueTypeId.Byte:
						fieldType = "byte";
						break;
					case BlueTypeId.Short:
						fieldType = "short";
						break;
					case BlueTypeId.IRoot:
					case BlueTypeId.IRootPtr:
					case BlueTypeId.IRootWeakRef:
						switch (field.ClassType) {
							case "IList":
								fieldType = "List<IRoot?>?";
								switch (fieldName) {
									case "IndexBuffers":
										attribute = "JsonIgnore";
										break;
								}

								break;
							case "IBlueDict":
								fieldType = "Dictionary<string, IRoot?>?";
								attribute = "BlackExperimental"; // never seen this before
								break;
							case "IBlueStructureList":
								fieldType = "byte[][]?";
								attribute = "BlackArray"; // polymorphic
								break;
							default: {
								if (!string.IsNullOrEmpty(field.ClassType) && totalNames.Contains(field.ClassType)) {
									fieldType = field.ClassType + "?";
								}

								break;
							}
						}

						break;
					default:
						throw new InvalidOperationException();
				}

				attribute = !string.IsNullOrEmpty(attribute) ? $"[{attribute}] " : string.Empty;

				writer.WriteLine($"\t{attribute}public {fieldType} {fieldName} {{ get; set; }}");
			}

			writer.WriteLine("}");
		}

		foreach (var buildInterface in buildInterfaces) {
			if (realClasses.Contains(buildInterface)) {
				continue;
			}

			File.WriteAllText(Path.Combine(output, "Blue", $"{buildInterface}.cs"), $"/// <auto-generated/>\nnamespace Jackdaw.Black;\n\npublic interface {buildInterface} {{ }}\n");
		}
	}

	private static void FindAllFields(Dictionary<string, (List<string> Interfaces, List<string> Fields)> typeLists, string name, HashSet<string> inheritedFields, HashSet<string> seen) {
		if (name == "IRoot" || !typeLists.TryGetValue(name, out var value)) {
			return;
		}

		if(!seen.Add(name)) {
			return;
		}

		var (inherited, fields) = value;
		inheritedFields.UnionWith(fields);

		foreach (var @interface in inherited) {
			FindAllFields(typeLists, @interface, inheritedFields, seen);
		}
	}
}
