using System.Diagnostics;
using System.Text;
using System.Text.Json;
using Jackdaw.Blue;
using Serilog;

namespace Jackdaw.Codegen.Black;

internal class Program {
	private static readonly string[] IgnoredTypes = ["IWeakObject", "IRoot", "_ClassDef", "object", "IBlueStructureList", "IList"];

	// ReSharper disable once UnusedMember.Local
	private static string FormatComment(string comment, string indent) {
		if (string.IsNullOrEmpty(comment)) {
			return string.Empty;
		}

		var lines = comment.Split('\n');
		var builder = new StringBuilder();
		builder.Append(indent);
		builder.AppendLine("/// <summary>");
		foreach (var line in lines) {
			builder.Append(indent);
			builder.Append("/// ");
			builder.AppendLine(line);
		}

		builder.Append(indent);
		builder.Append("/// </summary>");

		return builder.ToString();
	}

	private static string FixName(string fieldName) {
		var parts = fieldName.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
		var str = new StringBuilder();

		foreach (var part in parts) {
			str.Append(char.ToUpper(part[0]));
			str.Append(part[1..]);
		}

		return str.ToString();
	}

	private static void Main(string[] args) {
		if (args.Length < 2) {
			Console.WriteLine("Usage: Jackdaw.Codegen.Black <path/to/types.json> <path/to/output>");
			return;
		}

		Log.Logger = new LoggerConfiguration().MinimumLevel.Verbose().WriteTo.Console().CreateLogger();

		var types = JsonSerializer.Deserialize<List<BlueClass>>(File.ReadAllText(args[0]))!;
		var output = args[1];

		var buildInterfaces = new HashSet<string> {
			"IRoot",
		};
		var realClasses = new HashSet<string>();
		var typeLists = new Dictionary<string, (List<string> Interfaces, List<string> Fields)>();

		foreach (var type in types) {
			var interfaces = type.Interfaces.Select(x => x.Name).ToList();
			var parent = type.ClassId == "IRoot" ? "" : "IRoot";
			if (type.Parent.Length > 0) {
				parent = type.Parent.Split('.', StringSplitOptions.TrimEntries)[^1];
			} else if (interfaces.Contains("EveChildContainer")) {
				parent = "EveChildContainer";
			} else if (interfaces.Contains("Tr2AudioStretchBase")) {
				parent = "Tr2AudioStretchBase";
			} else if (interfaces.Contains("EveSOFDataHullLightSetItem")) {
				parent = "EveSOFDataHullLightSetItem";
			} else {
				parent = interfaces.FirstOrDefault(x => x[0] != 'I', parent);
			}

			var interfaceList = interfaces.Where(x => x != parent && x != "IRoot").ToList();
			buildInterfaces.UnionWith(interfaceList);

			interfaceList.Insert(0, parent);
			typeLists[type.ClassId] = (interfaceList, type.Fields.Where(x => x.Type is not (BlueTypeId.PythonFunction or BlueTypeId.PythonValue or BlueTypeId.PythonBinding)).Select(x => x.Name).ToList());
		}

		var totalNames = new HashSet<string>();
		totalNames.UnionWith(typeLists.Keys);
		totalNames.UnionWith(buildInterfaces);

		foreach (var type in types) {
			type.Description = type.Description.Trim();

			var group = "class";
			var name = type.ClassId;
			if (IgnoredTypes.Contains(name)) {
				continue;
			}

			var ns = "Blue";
			if (type.Id.Contains('.', StringComparison.Ordinal)) {
				var parts = type.Id.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
				if (parts.Length != 2) {
					Debugger.Break();
				}

				ns = parts[0].Trim('_');
				ns = ns switch {
					     "d3dinfo" => "D3DInfo",
					     "evelocalization" => "EveLocalization",
					     "eveplanetresources" => "EvePlanetResources",
					     "pyfsd" => "FSD",
					     "videoplayer" => "VideoPlayer",
					     _ => char.ToUpper(ns[0]) + ns[1..],
				     };
			}

			var nsOutput = ns.Length == 0 ? output : Path.Combine(output, ns);
			Directory.CreateDirectory(nsOutput);

			realClasses.Add(name);

			if ((type.Fields.Count == 0 && type.Parent.Length == 0 && name[0] == 'I') || name == "EveEntity") {
				group = "interface";
			}

			var interfaces = typeLists[name].Interfaces;
			var interfaceListString = $": {string.Join(", ", interfaces.Distinct())} ";
			Log.Information("Generating {Type} {InterfaceList}", name, interfaceListString);

			using var writer = new StreamWriter(Path.Combine(nsOutput, $"{name}.cs"));
			writer.WriteLine("/// <auto-generated/>\n#nullable enable\n\nnamespace Jackdaw.Black;\n");
			writer.Write($"public {group} {name} {interfaceListString}{{");

			var inheritedFields = new HashSet<string>();
			foreach (var @interface in interfaces) {
				FindAllFields(typeLists, @interface, inheritedFields);
			}

			var fields = type.Fields.Where(x => x.Type is not (BlueTypeId.PythonFunction or BlueTypeId.PythonValue or BlueTypeId.PythonBinding) && !inheritedFields.Contains(x.Name)).ToList();

			if (fields.Count == 0) {
				writer.WriteLine(" }");
				continue;
			}

			writer.WriteLine();

			foreach (var field in fields.OrderByDescending(x => x.Offset).DistinctBy(x => x.Name).OrderBy(x => x.Offset)) {
				field.Description = field.Description.Trim();

				var fieldName = FixName(field.Name);

				var attribute = string.Empty;
				var fieldType = "object?";

				// ReSharper disable once SwitchStatementMissingSomeEnumCasesNoDefault
				switch (field.Type) {
					case BlueTypeId.Int:
						fieldType = "int";
						break;
					case BlueTypeId.Single:
						fieldType = "float";
						break;
					case BlueTypeId.Double:
						fieldType = "double";
						break;
					case BlueTypeId.Boolean:
						fieldType = "bool";
						break;
					case BlueTypeId.Long:
						fieldType = "long";
						break;
					case BlueTypeId.FloatArray:
						fieldType = field.Size switch {
							            0 when field.ClassType == "Matrix" => "Matrix4x4",
							            0 when field.ClassType == "Color" => "Vector4",
							            0 when field.ClassType == "Rotation" => "Quaternion",
							            0 when string.IsNullOrEmpty(field.ClassType) => "Vector3",
							            8 => "Vector2",
							            12 => "Vector3",
							            16 => "Vector4",
							            24 => "Matrix3x2",
							            36 => "Matrix3x3",
							            64 => "Matrix4x4",
							            _ => throw new InvalidOperationException(),
						            };
						break;
					case BlueTypeId.String:
					case BlueTypeId.UTF8String:
						fieldType = "string?";
						break;
					case BlueTypeId.WString:
					case BlueTypeId.UTF16String:
						fieldType = "string?";
						attribute = "BlackUseNamePool";
						break;
					case BlueTypeId.Buffer:
						fieldType = "int[]?";
						attribute = "BlackArray(4)";
						break;
					case BlueTypeId.Byte:
						fieldType = "byte";
						break;
					case BlueTypeId.Short:
						fieldType = "short";
						break;
					case BlueTypeId.Collection:
						switch (field.ClassType) {
							case "IList":
								fieldType = "List<IRoot?>?";
								if (fieldName == "IndexBuffers") {
									attribute = "JsonIgnore";
								}

								break;
							case "IBlueDict":
								fieldType = "Dictionary<IRoot, IRoot?>?";
								attribute = "BlackExperimental";
								break;
							case "IBlueStructureList":
								fieldType = "byte[][]?";
								attribute = "BlackArray";
								break;
							default: {
								if (field.ClassType.Length > 0 && totalNames.Contains(field.ClassType)) {
									fieldType = field.ClassType + "?";
									attribute = "BlackArray";
								}

								break;
							}
						}

						break;
					case BlueTypeId.Object:
						if (field.ClassType.Length > 0 && totalNames.Contains(field.ClassType)) {
							fieldType = field.ClassType + "?";
						}

						break;
					default:
						throw new InvalidOperationException();
				}

				attribute = !string.IsNullOrEmpty(attribute) ? $"[{attribute}] " : string.Empty;

				writer.WriteLine($"\t{attribute}public {fieldType} {fieldName} {{ get; set; }}");
			}

			writer.WriteLine("}");
		}

		foreach (var buildInterface in buildInterfaces) {
			if (realClasses.Contains(buildInterface)) {
				continue;
			}

			File.WriteAllText(Path.Combine(output, "Blue", $"{buildInterface}.cs"), $"/// <auto-generated/>\nnamespace Jackdaw.Black;\n\npublic interface {buildInterface} {{ }}\n");
		}
	}

	private static void FindAllFields(Dictionary<string, (List<string> Interfaces, List<string> Fields)> typeLists, string name, HashSet<string> inheritedFields) {
		if (name == "IRoot" || !typeLists.TryGetValue(name, out var value)) {
			return;
		}

		var (inherited, fields) = value;
		inheritedFields.UnionWith(fields);

		foreach (var @interface in inherited) {
			FindAllFields(typeLists, @interface, inheritedFields);
		}
	}
}
