/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class VideoPlayer : IRoot {
	public int State { get; set; }
	public bool Is_paused { get; set; }
	public ITriTextureRes? Bgra_texture { get; set; }
	public long Media_time { get; set; }
	public long Duration { get; set; }
	public long Downloaded_media_time { get; set; }
	public IAudioSinkExposed? Audio_sink { get; set; }
}
