/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class Capsule : IRoot {
	public long Id { get; set; }
	public Ballpark? Park { get; set; }
	public bool IsMoribund { get; set; }
	public double Ax { get; set; }
	public double Ay { get; set; }
	public double Az { get; set; }
	public double Bx { get; set; }
	public double By { get; set; }
	public double Bz { get; set; }
	public float Radius { get; set; }
}
