/// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Jackdaw.Structs.Trinity.Generated;

public class ClientBall : Ball, ITriQuaternionFunction, ITriVectorFunction, IEveReferencePoint {
	public double CenterDist { get; set; }
	public double SurfaceDist { get; set; }
	public float MaxAngle { get; set; }
	public float SpeedModifier { get; set; }
	public float MinimumAngularVelocity { get; set; }
	public bool ShowBoxes { get; set; }
}
