/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class MiniBall : IRoot {
	public long Id { get; set; }
	public float Radius { get; set; }
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
}
