/// <auto-generated/>
#nullable enable

namespace Jackdaw.Black;

public class SettingsConfiguration : IRoot {
	public long CollisionMaxIterations { get; set; }
	public bool UseIterativeCollision { get; set; }
	public bool UseDynamicalOrientation { get; set; }
	public bool DisableDynamicalOrientationForMissiles { get; set; }
	public bool UseNewOrbit { get; set; }
}
